### ISSUE TITLE
Discontinued Course - Information Security: Context and Introduction

### ISSUE THREAD

**Issue by t-miller** [ossu/computer-science#1041]
I received an email this morning informing me that the [Information Security: Context and Introduction](https://www.coursera.org/learn/information-security-data) course currently in Core Security will stop accepting new enrollment on June 6. They offer a replacement course starting on June 6, but the link in the email does not redirect to a course.

![image](https://user-images.githubusercontent.com/19845698/171185061-fa7eab06-5c09-446c-bf6e-fed269bcc8a7.png)

**Comment by waciumawanjohi** [comment]
The course that Coursera promised would be available in June has still not materialized. The best replacement that I have found is [RIT's Cybersecurity Principles](https://www.edx.org/course/cybersecurity-fundamentals).

As our current link is broken, I'm going to make an immediate change to the RIT course. I'll open an RFC on the change so that contributors can take time to discuss the strengths and weaknesses of this change, as well.

Thank you @t-miller for noting this unavailable course!
