### ISSUE TITLE
RFC: Make an exception for C

### ISSUE THREAD

**Issue by romanbird** [ossu/computer-science#1078]
**Problem:**

For Core Systems, a strong understanding of the C Programming Language is expected in a way that is not currently reflected by the curriculum. 

**Duration:**
1 month

**Background:**
Although OSSU justifiably doesn't favour teaching languages, I think an exception should be made for C due to its key role in the teaching of core systems. Right now, despite being a soft prerequisite for Nand2Tetris and a hard prerequisite for O3EP, C is only implicitly taught. I think making an exception about language courses (spirit of the law etc..) in this instance would lead to a more "complete" curriculum in line with OSSU's original intentions, and minimise the risk of people picking up bad C habits from low quality resources or skipping Core Systems because of a lack of appropriate preparation. 

**Proposal:**
- At the very least, open a new discussion on the best way that C should be taught.
- Add the outcome of this discussion to the start of the core systems curriculum as a new course. (alternative given below)

**Alternatives:**
- Don't label it a "course", but add a one-off "section" to the Core Systems section explaining the importance of good C preparation and link to this considered resource.

**Comment by FaselAhmadwani** [comment]
C should be taught

**Comment by waciumawanjohi** [comment]
Unlike the other courses in the curriculum, OSTEP has [a course page dedicated to it maintained by OSSU](https://github.com/ossu/computer-science/tree/master/coursepages/ostep). On that page learners will read:
> Prerequisites
> This class requires a lot of experience programming in C. You should finish one of the C books listed in the resources below before starting this course...

and 

> Please don't try to learn C from sites like GeeksforGeeks...

and

> We recommend learning C by working through (the entirety of) Jens Gustedt's Modern C, which is freely available online...

and

> While the book above is our default recommendation, we also recommend K.N. King's [C Programming: A Modern Approach](http://www.knking.com/books/c2/) as a second, more beginner-friendly option...

and

> Additional (optional) resources include:...

To me, this sounds like a robust preparation guide for OSTEP and C. What do you feel is lacking here?

I will note, I don't agree with your statement that knowing C is a soft prerequisite for Nand2Tetris. For example, from the [course's page](https://www.nand2tetris.org/copy-of-cool-stuff):
> The course prerequisites depend on your objectives. If you wish to build the computer's hardware platform (also known as "Nand to Tetris Part I"), you can do it without any prior knowledge. If you wish to build the computer's software stack (also known as "Nand to Tetris Part II"), you need programming knowledge at the level of a typical Introduction to CS course.

**Comment by romanbird** [comment]
Learning C well carries a significant time investment, one longer than many of the courses already on here. It’s completely unlike any other prerequisite, and should be given course status or at the very least something in between course and prerequisite. Instead of burying this massive C expectation let’s put in on the course page under core systems.  On 1 Oct 2022, at 17:52, waciumawanjohi ***@***.***> wrote:﻿
Unlike the other courses in the curriculum, OSTEP has a course page dedicated to it maintained by OSSU. On that page learners will read:

Prerequisites
This class requires a lot of experience programming in C. You should finish one of the C books listed in the resources below before starting this course...

and

Please don't try to learn C from sites like GeeksforGeeks...

and

We recommend learning C by working through (the entirety of) Jens Gustedt's Modern C, which is freely available online...

and

While the book above is our default recommendation, we also recommend K.N. King's C Programming: A Modern Approach as a second, more beginner-friendly option...

and

Additional (optional) resources include:...

To me, this sounds like a robust preparation guide for OSTEP and C. What do you feel is lacking here?
I will note, I don't agree with your statement that knowing C is a soft prerequisite for Nand2Tetris. For example, from the course's page:

The course prerequisites depend on your objectives. If you wish to build the computer's hardware platform (also known as "Nand to Tetris Part I"), you can do it without any prior knowledge. If you wish to build the computer's software stack (also known as "Nand to Tetris Part II"), you need programming knowledge at the level of a typical Introduction to CS course.

**Comment by waciumawanjohi** [comment]
> It’s completely unlike any other prerequisite

Why? 

> Learning C well carries a significant time investment, one longer than many of the courses already on here

Learners are reasonably interested in knowing the time estimate for courses. I'm would support a re-examination of the time estimate for OSTEP in light of likely needing to do prep work.

The curriculum is meant to reflect the requirements for an undergraduate curriculum in Computer Science. I'm not convinced that requires learning C (but I welcome contributors to use our [curricular guidelines](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md) to prove the point).

**Comment by angle943** [comment]
maybe for `Duration` and `Effort` we can have something like `10 - 12 weeks (10 + n - 12 + m weeks if you don't know C)` and such, to make it:

1) more apparent that if you don't know C, you need to take a course on C before taking the course
2) give a better estimator for those who are using our `Duration` and `Effort` columns to track how long it will take to finish OSSU

**Comment by romanbird** [comment]
> maybe for `Duration` and `Effort` we can have something like `10 - 12 weeks (10+n - 12+m weeks if you don't know C)` and such, to make it:


Yeah something like this is a good idea (I think this could go further though). But its more than just C (like the C covered in CS50), learning C well enough to do a systems course is a significant project and more than a quick bit of pre-reading.

>I'm not convinced that requires learning C (but I welcome contributors to use our [curricular guidelines](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md) to prove the point).

Obviously it doesn't fit, but I think an exception should be made (like the one made for CS Tools for example). Right now we've got a weird middle ground where we say C shouldn't be necessary because of existing principles but then implicitly expect a very high-level understanding of it. C doesn't make sense as part of CS2013 but it does make sense in our adaptation of CS2013.

**Comment by waciumawanjohi** [comment]
> C doesn't make sense as part of CS2013 but it does make sense in our adaptation of CS2013.

Which in turn is tied to our choice of an operating systems class. OSTEP is the best open OS course that we've identified, but we shouldn't create arbitrary impediments to replacing it with something more suitable in the future, nor should we create artifacts of its inclusion that would outlive its place in the curriculum. Including the material necessary for learning C in the pre-reqs of OSTEP rather than in a separate course in the curriculum, accomplishes these goals.

> an exception should be made (like the one made for CS Tools for example)

An important distinction is that familiarity with version control (git), debugging, etc are skills that can aid students both in most future classes as well as in essentially all work that relies on a Computer Science degree. And to be clear,[they are part of the core curriculum in CS2013](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=181).

> But its more than just C (like the C covered in CS50), learning C well enough to do a systems course is a significant project and more than a quick bit of pre-reading.

I'm not sure what this sentence is in reference to. [The OSTEP course page reads](https://github.com/ossu/computer-science/tree/master/coursepages/ostep#c):

> CS 50 doesn't quite cover enough C for OSTEP

As my thumbs up above indicates, I support angle943's duration proposal.

**Comment by riceeatingmachine** [comment]
> Unlike the other courses in the curriculum, OSTEP has [a course page dedicated to it maintained by OSSU](https://github.com/ossu/computer-science/tree/master/coursepages/ostep). 

This needs to be made prominent, somehow I never knew it existed. 

---

Otherwise, I am in favor of this proposal, simply because seeing C as a prerequisite to OSTEP helps students plan the time commitment it takes to do OSTEP. 

In general, I think for a lot of the courses present, we can offer less rigorous alternatives for people who would otherwise skip that topic altogether considering the utility to length ratio. For example, calculus so far has not proven particularly useful for any of the topics it was listed as a prerequisite in (machine learning and math for cs), so I could have gotten by with 6 weeks on Khan Academy instead of the 26 weeks of MIT's courses.

So, for example, we can say 

Operating Systems: OSTEP for high rigor, requires C (read this textbook). 200 hours combined.
Low rigor: [this course](https://www.educative.io/courses/operating-systems-virtualization-concurrency-persistence), 40 hours. 

We can do something similar for Core Security too and reduce courseload.

**Comment by waciumawanjohi** [comment]
> This needs to be made prominent, somehow I never knew it existed.

It's a relatively new change. It's about as prominent as you can get, if you click on the link for OSTEP on the main page it takes you to our course page, not directly to the class.

> we can offer less rigorous alternatives for people who would otherwise skip that topic altogether considering the utility to length ratio

In general if there's a low rigor course that actually covers requirements, that should be the recommended Core class and the more in depth course should be in Advanced. RFCs for replacement courses that meet our reqs and lower overall workload are always welcome! (There's a reason that the first line of the OSTEP course page is "First, we should be frank: it's really hard to find a good self-contained online course on operating systems. OSTEP is the best course we've found so far, but it does have some issues.")

> Low rigor: [this course](https://www.educative.io/courses/operating-systems-virtualization-concurrency-persistence), 40 hours. 

Heads up, it looks like everything but the first week of that course is behind a paywall.

**Comment by Alaharon123** [comment]
Suggestion: Make the "strong C programming" text in the prerequisite column also link to the course page so people click on that and see that we have suggestion already for how to get strong C programming rather than being on their own to figure that out before clicking the OSTEP link

**Comment by waciumawanjohi** [comment]
> Suggestion: Make the "strong C programming" text in the prerequisite column also link to the course page so people click on that and see that we have suggestion already for how to get strong C programming rather than being on their own to figure that out before clicking the OSTEP link

That's a non-substantive change that makes a big improvement. Carried out!

(To be clear, that doesn't close this discussion)

**Comment by riceeatingmachine** [comment]
@waciumawanjohi @spamegg1 @palladian1 

I found another course that teaches C that might be more useful to us than the one listed:

https://cs.uwaterloo.ca/~plragde/flaneries/IYMLC/index.html

It's a creative commons book and it's meant for people who already know Racket based on HtDP.

> But it does assume that you have programmed in Racket before, perhaps in a course based on [How To Design Programs](https://www.htdp.org/) (HtDP)

It uses "C Programming: A Modern Approach" as an optional textbook, which is the recommendation on the OSTEP page.

> Not surprisingly, the textbook ("C Programming: A Modern Approach" by K.N. King) that I chose to support the coverage of programming in C in our CS 136 course was not written for students who have had a first course using Racket. It is written in a self-contained manner, assuming students either have had no experience with computing, or have had experience with another imperative language. For students with only Racket experience, some parts will seem too easy, and others somewhat mysterious. The chapters have to be read out of order, which causes further complications.
> The next sections list ways to match the King textbook with this material. If you don’t plan to use the book, you can skip it.

This course seems like it "fits" into our curriculum seamlessly as it builds on Racket and HtDP. And it's also shorter than our current recommendation (Modern C).

**Comment by waciumawanjohi** [comment]
> I found another course that teaches C that might be more useful to us than the one listed:
> https://cs.uwaterloo.ca/~plragde/flaneries/IYMLC/index.html

Off to a [strong if VERY slow start on Goodreads](https://www.goodreads.com/book/show/57220902-if-you-must-learn-c). The [author](https://uwaterloo.ca/computer-science/people-profiles/prabhakar-ragde) seems legit. As with any new resource, quality is an important question.

**Comment by spamegg1** [comment]
@riceeatingmachine That's nice, but really far from sufficient for OSTEP projects. You should take a deep look into xv6 code. It uses a lot more advanced complicated C than the book you linked. There is simply no way around the roadmap laid out by palladian (who used K.N. King by the way). We had to go through some of the code together for hours to figure out what it was doing, because it's straight up written in assembly, or, due to memory limitations, bit-wise arithmetic ("dark magic" in palladian's words).

I'd be fine with adding it to the OSTEP course page under "Additional resources" as: "here's a nice place to start, it's written by the How to Design Programs/How to Code people, uses Racket to teach some of the ideas (which you're familiar with), but it's far from enough, you'll still need to learn more after that." 

I'm totally fine with increasing the time estimate. For OSTEP, there is still a TON more to learn after C anyway (learning C is arguably the easier part): how x86 assembly works, how xv6 works, how Makefiles work, how preprocessing and linking work...

***Reporting from the active front lines:***

I am more and more convinced that Modern C doesn't really cut it either, K.N. King seems absolutely necessary. Some learners on Discord reported difficulty understanding parts of Modern C that's written a bit too tersely and left up to the reader. We had to recommend Modern C because it's free. Requiring a non-free book would be... I don't know. I don't want to deliberately push people toward piracy.

Making an "exception" or making it more "prominent" or whatever is not going to change anything either. We can't do anything about the people who come straight to our Discord and ignore our Github page entirely (or look at a really old fork of someone). I had to direct quite a few learners: "please read this page first, it has everything you need" (even though it's pinned). Some Discord users don't even know what Github is, but ***somehow heard of OSTEP and decided to do it***. :fearful: The world is a weird place.

Honestly, I am starting to consider this stupid C/OSTEP problem near unsolvable and I'm starting to get depressed. Maybe someone in the future will make an awesome super cool online operating systems course in Rust that's gentle, self-contained, auto-graded and easily doable. Given the personality types of OS people (and the overall difficulty of the subject) I'm not very hopeful though. OS knowledge is by its nature very arcane, poorly documented, hidden in academic offices, or spread out to wikis, old webpages from the 1990s, and the heads of a few developers who are extremely introverted. Hack the Kernel has graders, but it has low quality lectures, code base is 10x the size of xv6 (around 40000 lines), much much harder and requires a ton of MIPS assembly and quadruple pointers! We're probably stuck with C/OSTEP for a good while.

**Comment by riceeatingmachine** [comment]
@spamegg1 What do you think of [this course](https://www.educative.io/courses/operating-systems-virtualization-concurrency-persistence)? (Just see the topics) 

> I am more and more convinced that Modern C doesn't really cut it either, K.N. King seems absolutely necessary. Some learners on Discord reported difficulty understanding parts of Modern C that's written a bit too tersely and left up to the reader. We had to recommend Modern C because it's free. Requiring a non-free book would be... I don't know. I don't want to deliberately push people toward piracy.

Regarding this, please check my RFC #1079 I think it might be the way forward.

**Comment by riceeatingmachine** [comment]
> I'm starting to get depressed. Maybe someone in the future will make an awesome super cool online operating systems course in Rust that's gentle, self-contained, auto-graded and easily doable. 

The reason I bring up the [educative.io](https://www.educative.io/courses/operating-systems-virtualization-concurrency-persistence) course above it because it's made by the Authors of OSTEP (Andrea and Remzi). 

From [this source](https://milled.com/educative-us/operating-systems-virtualization-concurrency-and-persistence-7r7b42obKlUkJXyC): 

> This course is great for you if you’re new to operating systems, or even if you need to brush up on them. This is one of our more robust courses and will dive deep into the inner workings of an OS. It is extremely detailed and covers essentially everything you would want to know. Everyone from beginners to OS pros will find this course extremely useful. 

The downside is as pointed out earlier - it's paid.

**Comment by romanbird** [comment]
> I am more and more convinced that Modern C doesn't really cut it either, K.N. King seems absolutely necessary. Some learners on Discord reported difficulty understanding parts of Modern C that's written a bit too tersely and left up to the reader. We had to recommend Modern C because it's free. Requiring a non-free book would be... I don't know. I don't want to deliberately push people toward piracy.

As someone who is fine with using paid books stuff like this is kinda worrying, I was planning to use that book! If something's not sufficient we should know right?

**Comment by spamegg1** [comment]
> If something's not sufficient we should know right?

Don't worry. It's just my opinion, I can be wrong. A few others said Modern C is fine. We can't really know if it's sufficient or not. Very few have completed this course. So it's adventurous territory. We are just doing what we can, to the best of our knowledge. King explains things much better (but it's much longer) so we added it as the best recommendation.

**Comment by waciumawanjohi** [comment]
I want to bookmark this somewhere and this thread has become a bit of a discussion about the suitability of OSTEP. Stanford used to have a course `CS 110: Principles of Computer Systems`. It was a precursor to their `CS 140: Operating Systems` course, and followed `CS 107: Computer Organization & Systems`. (So 107 -> 110 -> 140) More recently [Stanford has combined 140 and 110 into CS 111](https://web.stanford.edu/class/cs111/spring22/110/).

That history aside, there exists a [course site for a summer run of CS 110](http://web.stanford.edu/class/cs110/summer-2021/) and a youtube set of [lectures from a Spring](https://www.youtube.com/playlist?list=PLu77E6J7s6Ko3Ft4XcOX1yKW6iX3eEFqS) run. There are assignment, labs and assessments, where labs and assessments have solution pages.

The class is all C++ based and the prereq course is all C based, so it doesn't solve the issue at the top of this issue. But wanted to point it out here since all the OS interested folks are getting notifications.

**Comment by romanbird** [comment]
> I want to bookmark this somewhere and this thread has become a bit of a discussion about the suitability of OSTEP. Stanford used to have a course `CS 110: Principles of Computer Systems`. It was a precursor to their `CS 140: Operating Systems` course, and followed `CS 107: Computer Organization & Systems`. (So 107 -> 110 -> 140) More recently [Stanford has combined 140 and 110 into CS 111](https://web.stanford.edu/class/cs111/spring22/110/).
> 
> That history aside, there exists a [course site for a summer run of CS 110](http://web.stanford.edu/class/cs110/summer-2021/) and a youtube set of [lectures from a Spring](https://www.youtube.com/playlist?list=PLu77E6J7s6Ko3Ft4XcOX1yKW6iX3eEFqS) run. There are assignment, labs and assessments, where labs and assessments have solution pages.
> 
> The class is all C++ based and the prereq course is all C based, so it doesn't solve the issue at the top of this issue. But wanted to point it out here since all the OS interested folks are getting notifications.

This looks really cool! I'm gonna put this in for after 3EP so we can see if it's worth adding.

**Comment by spamegg1** [comment]
@waciumawanjohi I think people are OK with the suitability of OSTEP course/book overall, but not with the kernel programming assignments and their prerequisites. **To do operating systems programming, there is simply no way around several hundreds of hours of work. There. Just. Isn't.** The course you linked seems nice, but you're right it doesn't solve this issue. It looks just as hard and time-consuming as our current option.

(I also think that "the C issue" is a bit related to the reverence C has, and people's desire to see it "represented", but I'll leave that on the side.)

There are many universities whose operating systems courses don't require lab assignments. There are also some whose do. Usually the most prestigious ones (Stanford, MIT, Harvard etc.) I don't believe that lab/programming assignments are necessary to fulfill our curriculum requirements. I've read through CS 2013 guidelines (page 135) and the only part that requires *implementing* or *programming* something is "Implement a simple device driver" which is an elective. 

If we make `xv6` assignments optional, we can side-step this C/x86 issue. That's what I suggested in #1083

**Comment by spamegg1** [comment]
> Learning C well carries a significant time investment, one longer than many of the courses already on here.

Reading the textbook+HW and skipping the projects does not require much C learning. It's the projects that require it.

We currently say on the course page:
> What this means for you is that if you're under a significant time crunch, or you're just not all that interested in systems programming and OS development, there's no shame in skipping this course and coming back to it later. You could also do only a part of the course (e.g. you might choose to skip the homework and/or projects).

I suppose the issue is that **nobody reads the course page carefully**. Reading is super hard! Everyone just keeps on scrolling.

I wrote a draft to clarify it here: [comment](https://github.com/ossu/computer-science/issues/1083#issuecomment-1274564725) This should make it abundantly clear that you don't have to learn much C or do the projects.

**Comment by romanbird** [comment]
Happy with how this resolved 👍
