### ISSUE TITLE
Possible future of the OSSU as a blockchain based online University (basically a DAO).

### ISSUE THREAD

**Issue by Mesum-Hussain** [ossu/computer-science#1142]
Now that we have a curriculum and courses in place, I think there's a possibility of OSSU becoming a blockchain based online University, if we figure out testing, grading and crediting systems.

Perhaps we can use blockchain to store the progress of the students and provide them with a Degree after the successful completion of the curriculum.

Here are some ideas I came up with while brainstorming:

1) Every test should be like a standardized test in which the candidate just needs to mark the correct answer instead of writing anything (objective type questions..... Something like SAT). And even if testing some concepts absolutely require the candidate to write an answer (require a subjective type question..... Asking their opinion or requiring an essay), then perhaps the answer can go through ChatGPT and then evaluated by a volunteer too (although I really wouldn't recommend having any subjective type questions in the first place). 

2) Tests should be available on demand.....we can have an "encrypted" repository (loosely saying this..... didn't think much about how we can handle the test questions repository) in which the volunteers who already qualified the course can submit questions, which could be peer reviewed for quality, and then a question paper is provided to the candidate on demand by selecting questions from that repository at random. 

3) The test should ideally not be time bound, but once started, should be completed in one session. This way we can have around 200 questions per test to ensure the quality of knowledge of the candidate (because we are really not sure if the candidate actually went through the courses or not, and less number of questions will increase the probability of the answers being just a fluke). We can also have a negative marking system to discourage candidates from guessing the answers.

4) We can have questions that are not easily searchable on the internet, and perhaps use a special browser (something like what Amazon and others does during their online recruitment tests) for avoiding malpractice (open to more better ideas on this).

5) For CS lab exams, we can perhaps provide a secure and monitored VM in which candidate can do the tasks required for the exam, and that VM will automatically qualify the candidate if all the test cases are passed.

6) We can also introduce the concept of *Skill Degradation*, which is a percentage indication of quality of skill, which is 100% immediately after a test (depending on the marks obtained) and then decrease (perhaps following a Bell curve) over time until refreshed by taking a retest perhaps evey couple of years (this would be so much better indicator of the skills as compared to the traditional Universities test system which gives a lifetime degree just based on a few tests written decades ago). This need not be mandatory though.....it should be totally up to the candidate to refresh their Skill Percentage Score.

7) We can also provide volunteers with a cryptocurrency (preferably something already well established like ETH) for participating in the evaluation and testing process.

For the Textbooks referred to in the curriculum, it would be wonderful if we as a community can make our own alternative ones taking inspiration from the popular ones..... preferably in the Jupyter Notebook format, and have them licensed under Creative Commons. This would completely ensure that we are not encouraging piracy by any means.

**Comment by robbrit** [comment]
Some comments:

1. One of the primary difficulties with online testing is verifying the identity of the person taking the test. MOOC companies like Coursera and Udacity require you to take the test using a camera where you show your government-issued ID to confirm that it's actually you, and not you paying someone else to do it. In the US, many online self-study programs (NASM personal trainer certificates, for example) require you to go to a physical testing facility where they check your ID and then let you in to use a computer to take your test.
2. Multiple-choice SAT questions would be pretty terrible for university-level education; LinkedIn already does these types of assessments and they don't correlate very well with actual knowledge. It's possible ChatGPT could help here, but a proof-of-concept would be necessary.
3. I'd skip on #6, it's a complication that I don't think adds any value. Instead you can just put the year of when they completed the course, and then let anybody evaluating the credential decide how useful it is. It works well enough for regular degree programs.
4. #7 is complicated because once you pay people you can't really consider them "volunteers" anymore, with all the messiness that comes from that. The first challenge is getting the money in the first place (we don't charge tuition, nor receive money from any government), then you have to deal with tax implications, money-laundering, etc. And also: the majority of people probably have no interest in getting paid in crypto.
5. The last thing is that this proposal would require significantly more labour to do it. OSSU volunteers are already stretched pretty thin simply maintaining the curriculum and moderating the Discord server, introducing all this extra load would be far more work than we'd be able to handle.

**Comment by Mesum-Hussain** [comment]
Can we at least start with making Libre Books for our curriculum?
Something like Wikipedia, but in a Jupyter Notebook format? 
Actually I saw Qiskit do it for Introductory Quantum Computing, and I was really fascinated by the idea. 
We can perhaps maintain a GitHub repository of such books which are tailored to our curriculum.

**Comment by aliaxan1** [comment]
We can  use an **AI** system to verify the person taking test using camera on device

**Comment by waciumawanjohi** [comment]
As pointed out by Robbrit:
> this proposal would require significantly more labour to do it. OSSU volunteers are already stretched pretty thin simply maintaining the curriculum and moderating the Discord server, introducing all this extra load would be far more work than we'd be able to handle.

Closing this issue. Can be reopened when there is capacity to take on this work.

**Comment by Mesum-Hussain** [comment]
> As pointed out by Robbrit:
> > this proposal would require significantly more labour to do it. OSSU volunteers are already stretched pretty thin simply maintaining the curriculum and moderating the Discord server, introducing all this extra load would be far more work than we'd be able to handle.
> 
> Closing this issue. Can be reopened when there is capacity to take on this work.

I think we can start with creating Creative Commons Jupyter Notebook Textbooks for the curriculum which are inspired by the popular textbooks. ChatGPT can help in my opinion..... I will try to do it, but I can only take this up after February 2024.

**Comment by Wizardibrahim4** [comment]
@Mesum-Hussa
good
