### ISSUE TITLE
RFC: Update to the 2023 curricula

### ISSUE THREAD

**Issue by eytangut** [ossu/computer-science#1256]
**Problem:**
OSSU says in the curricular guidelines that it uses the 2013 curricula, and that the 2023 one is being written. however, the 2023 one is complete
[3664191.pdf](See the new curricular guidelines here)

**Duration:**
I do not know what to write here, as this is my first issue in this project, and the issue template says to write one month but I guess that updating the whole curriculum would take more than a month

**Background:**
I suggest using the new curricular guidelines. just reading them would be a task as they are about 450 pages, but to try and see what is in there before reading this whole thing I used ChatGPT. Now, I know it is not very reliable. Please do not shout at me "But ChatGPT is an idiot!" because I know that already. The only reason I used ChatGPT is to try to get a sense of what needs adding before actually reading this huge file, I do not intend to use that as the actual template of what to add, only to try to get a sense of what needs adding. I sent ChatGPT the readme.md, the 2013 curricula, and the 2023 curricula, and asked him how to update it. What he told me to add was: To the core CS section, to add a course on machine learning fundamentals and a course in introduction to AI. In the core systems section, he suggested adding a course about Cybersecurity fundamentals, and a course about Introduction to quantum computing.  In core theory, he suggested adding a course about Advanced Algorithms for ML and AI. In core security, he suggested adding a course on Ethics in AI and Security. In core applications, he suggested adding a course on Data Science Fundamentals and a course about Big Data Technologies. In core ethics, he suggested a course on Responsible AI and Data Privacy. In advanced CS he suggested a course on Advanced Machine Learning, In advanced systems he suggested adding a course on Advanced Machine Learning, And in advanced information security he suggested adding a course about Modern Cryptography. He also had some ideas for electives in the final project: Machine Learning, Natural Language Processing, Robotics, Compilers, Cryptography, Computer Security, Software Verification, Advanced Computer Graphics, Parallel Computing, Distributed Computing, Data Mining, Real-Time Systems, Computational Biology, etc.
I will update this issue once I read the 2023 curricula however it might take me some time.
**Proposal:**
Update the courses to the 2023 guidelines. Also, we should read them which is a task by itself, but I gave here ChatGPT`s suggestion so we would have an idea of what would we need to add.

**Alternatives:**

- Do nothing and stay on the 2013 guidlines

**Comment by pulkitkrishna00** [comment]
Copying from [Bradley's message on discord](https://discord.com/channels/744385009028431943/744682430853808178/1103464410950926337):

**Q: Is OSSU going to switch to referencing the new CS2023 version of the ACM/IEEE Computer Science Curricula guide? When will this happen?**

**A:** Not right away. CS2023 -- like CS2013, the edition before it and the current curricular guide for OSSU -- is a prospective guide. It does not describe the current state of CS curricula; it describes where the ACM (an industry trade group of computer scientists) would like future CS curricula to go. Many leading computer science programs worldwide spent several years gearing up to the CS2013 guide; many others are still catching up.

**Q: But doesn't this mean OSSU is now an obsolete curriculum? Won't following this put me substantially far behind the state of the art?**

**A:** No. ACM computing standards aren't like PyCon or React Summit. Change happens slowly, recommendations aren't adopted immediately, and it turns out academic faculty have their own competing opinions. 

Besides that, universities haven't even adopted this yet, and they likely won't for several years. And because OSSU courses are provided by universities, we will need to follow their lead.  In order for that to happen, several other things have to happen first:

- Universities will need to decide if they want to implement CS2023 (they do not have to -- as CS2023 is a vision document and not an accreditation standard).
- Universities will need to decide what parts of CS2023 they want to implement
- Universities must then task professors who will need to design courses around those parts
- They will need to release those courses and have them be successful in-seat
- They will then need to decide to open-source those courses
- They then have to film them, produce them, and put them out

After all of that, OSSU will get involved:
- first we will need to learn of their existence
- then we need volunteers to test them, vet them, and make sure they meet our needs
- then we need to recommend them for adoption

**So this may take a while.** 

**Q: But I want it now!**

**A:** Tough. CS2023 is, at this point in time, nothing but a Christmas wishlist. ACM makes a list of what they want to see in CS programs. It's up to Santa (i.e. Santa State University) to make it happen, if and only if it wants to.

**Comment by UltiRequiem** [comment]
> It's up to Santa (i.e. Santa State University) to make it happen, if and only if it wants to.

Ngl,  I googled it lol
