### ISSUE TITLE
OSU Calculus Courses to End in September 2018

### ISSUE THREAD

**Issue by leungleoqin** [ossu/computer-science#465]
The course sent out an email on 28 Feb, announcing that [Calculus One](https://www.coursera.org/learn/calculus1) and [Calculus Two](https://www.coursera.org/learn/advanced-calculus) by Ohio State University on Coursera will be ending in September, and new enrollment will end in March. The email reads:

> Thank you for participating in our Calculus One course. You made it through all the lessons and fully completed the course...and for that, we commend you!
> 
> We are reaching out to let you know that this course will be closing on September 30, 2018. (Enrollment in new sessions will close on March 30th)
> 
> Even though you've already completed the course, you still have the opportunity to access the learning materials until 9/30/18.
> 
> After that date, if you'd still like to access the course content, Ohio State offers this calculus course material, and more, for free at ximera.osu.edu. There are also many calculus related courses available through Coursera, many of which you can find here.
> 
> Thank you for your interest and contributions to this course. If you would like to know more about the many open learning opportunities through The Ohio State University, click here to subscribe to our quarterly newsletter.
> 
> Happy Learning,
> 
> The Ohio State University Open Learning Team

The course content will be migrated to [https://ximera.osu.edu/](https://ximera.osu.edu/), but based on what I see now, they don't contain the video lectures - which IMO is the best part of the course. We should see if we want to use this version of the course or find an alternative to replace it.

**Comment by jeremy-gray** [comment]
How about this series of courses? OSSU Data Science curriculum uses these.
Calculus 1A: [https://www.edx.org/course/calculus-1a-differentiation-mitx-18-01-1x-0?source=aw&awc=6798_1521199800_35ecec882e6bfc4fa58e28f088b5c008&utm_source=aw&utm_medium=affiliate_partner&utm_content=text-link&utm_term=301045_https%3A%2F%2Fwww.class-central.com%2F]
Calculus 1B: [https://www.edx.org/course/calculus-1b-integration-mitx-18-01-2x-0?utm_campaign=mitx&utm_medium=partner-marketing&utm_source=direct&utm_content=18-01-1x-to-18-01-2x]
Calculus 1C: [https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-mitx-18-01-3x-0]

**Comment by jkuzmanovik** [comment]
Profesor Leonard Calculus (1,2,3)..Trust me these are one of the best courses on this topic..Profesor Leonard is best professor in math..(my opinion)

**Comment by hanjiexi** [comment]
@jeremy-gray We've discussed those courses previously in #437, and I had brought up that the MIT calculus courses are extremely long. In my opinion, calculus isn't important enough for a general, especially programming-focused computer science curriculum to spend 36 weeks on it. Great courses I'm sure, but I'm looking for something shorter.

**Comment by waciumawanjohi** [comment]
I understand where @hanjiexi is coming from, we shouldn't burden students with topics that will not be important for them.

Even so, I think the MIT course (or 3 course offering) is the proper direction. When a student has mastered that course, they will have covered all that will be expected of them from a single-variable calculus course. Currently, a student that completes OSSU will pursue one or more of 5 advanced CS tracks. 4/5 of those tracks have courses for which calculus is a pre-req. That suggests calculus is important enough to know thoroughly.

**Comment by hanjiexi** [comment]
We absolutely do need a high quality and rigorous calculus course. My question is whether the same can be accomplished with the U Penn Calculus course.

It is shorter (21 weeks, plus whatever time is needed for a calculus prep course), but quite rigorous:
> The course is split into five separate chapters: function, differentiation, integrations, applications, and discretization with a grand total of 53 lectures (54 if you count the introduction). The videos average about 15 minutes of length and EVERY video is followed by a problem set of roughly 10 problems. In other words, by the time you complete this course you will have done over 500 problems, not including the chapter tests and final exam.

http://moocsreviews.blogspot.com/2013/08/coursera-single-variable-calculus-upenn.html

**Comment by unnir** [comment]
All video lectures are available on youtube, check the website: https://mooculus.osu.edu/lectures

**Comment by waciumawanjohi** [comment]
Looking at the UPenn course, it's very interesting from a CS point of view. The first of the five courses introduces the study of asymptotics (Big-O notation). The fifth course is all about calculus in the discrete domain. This sort of focus is particularly useful for the student of computer science.

I am a bit concerned that the focus on conceptual understanding comes at the expense of teaching how to calculate. The lecture on differentiation rules is 17 minutes long and does not walk through a single concrete example:
https://youtu.be/hyF6pw5BTdU

The homework with that lecture is just 12 questions.
To Pass: 60% or higher
Attempts: 3 every 8 hours
It's not clear that the questions change significantly if you get one wrong and need to retest for mastery.

The lectures also seem to assume the student has studied calculus previously. Note that the lecture I linked begins, "From your previous exposure to calculus, you probably learned how to compute derivatives quickly without the definition by following a certain set of rules or laws."

This seems like a very interesting offering, and the visualizations bolster an intuitive understanding of what is going on. But I'm concerned that students who only took this course would be underprepared for a course which listed Calculus I as a pre-req (say, the MIT Calculus II course in Advanced Math or Electricity and Magnetism in Advanced Systems).

**Comment by hanjiexi** [comment]
> The lectures also seem to assume the student has studied calculus previously.

That is what I meant about the need for a calculus prep course before U Penn Calculus can be taken. I'm thinking either [Pre-University Calculus](https://www.edx.org/course/pre-university-calculus-delftx-calc001x-2) or a selection from Khan Academy.

**Comment by waciumawanjohi** [comment]
Ah, gotcha. An interesting idea. But how much time will that save?

[UPenn Calculus](https://www.youtube.com/playlist?list=PLKc2XOQp0dMwj9zAXD5LlWpriIXIrGaNb): 18 hours
+
[Udelft PreCollege Calc](https://www.youtube.com/channel/UCgYNtSoa0fJwj2JndrUlEow/videos): 8 hours
[Khan Academy Calculus](https://www.youtube.com/playlist?list=PL19E79A0638C8D449): 33 hours

vs

[MIT Calculus](https://www.youtube.com/playlist?list=PL590CCC2BC5AF3BC1): 30 hours
(Note: This is the length of the recorded Calc 1 classes, which is not the same set of videos from the edX course)

**Comment by Nixerrr** [comment]
I've tried some Calculus resources and here are my experiences:

- **Khan Academy**: Both the Calculus AB and Calculus BC playlists of Khan Academy are really good and extensive with loads of exercises. They could be viable candidates as primers for the U Penn Calculus course.
- **MIT Calculus on edX**: These are well produced and high quality, but very demanding as well. I did the first course and I needed to supplement it with extra material to fully grasp everything.
- **MIT Calculus on OCW**: It is what it is - video lectures with notes. Its edX counterpart is way better.

After being frustrated with online resources, I ended up using the Steward Calculus textbook, and I've been extremely happy with it. I can recommend it wholeheartedly if someone decides to study Calculus offline.

**Comment by hanjiexi** [comment]
@Nixerrr Thanks for the feedback!

@waciumawanjohi I tend to use the highest total estimated effort rather than the total length of course videos, as we have to take time needed for exercises into account.

Pre-University Calculus: 6 weeks @ 6-8 hours/week, max 48 hours
MIT Calculus 1A: 13 weeks @ 6-10 hours/week, max 130 hours
MIT Calculus 1B: 13 weeks @ 5-10 hours/week, max 130 hours
MIT Calculus 1C: unspecified, assuming it's the same as 1A and 1B
U Penn Calculus part 1: 4 weeks @ 6-8 hours/week, max 32 hours
U Penn Calculus part 2: 3 weeks @ 6-8 hours/week, max 24 hours
U Penn Calculus part 3: 4 weeks @ 6-8 hours/week, max 32 hours
U Penn Calculus part 4: 5 weeks @ 6-8 hours/week, max 40 hours
U Penn Calculus part 5: 5 weeks @ 6-8 hours/week, max 40 hours

MIT Calculus total: 390 hours, or 39 weeks
Delft Pre-University Calculus + U Penn Calculus total: 216 hours, or 27 weeks

Khan Academy doesn't give any effort estimates, but I wasn't suggesting using all of Khan Academy Calculus, merely that Pre-University Calculus be supplemented with Khan Academy as needed to close any gap towards U Penn Calculus.

MIT Calculus is definitely the *simplest* option — from the perspective of curriculum maintenance. We can be sure the quality is high and the content is thorough. The difference to the student is: will they want to spend half a year learning calculus geared towards CS students, or three-quarters of a year learning pure calculus?

**Comment by waciumawanjohi** [comment]
It feels like it is time to pull the trigger on one of these options. New enrollments to our current calculus recommendations are closed, which means the curriculum is out of date.

If we're forgoing the MIT course, the option that appeals most to me is Khan Academy Calculus followed by UPenn calculus. The former will ensure that students have had practice with the actual calculations in question. The latter will be a review of the high level concepts, and will extend calculus from the continuous to discrete domain.

On using Khan Academy to supplement the Delft course: That seems like quite a bit of effort and it's not clear what that effort is in pursuit of. If the Delft course is insufficient, why try to custom make tweaks and fixes rather than recommending a course that is sufficient?

**Comment by kisonecat** [comment]
All of my video lectures are available on the [MOOCulus YouTube playlist](https://www.youtube.com/user/kisonecat/playlists?shelf_id=4&view=50&sort=dd).

But I'd also appreciate feedback on [the various Ximera activities](https://ximera.osu.edu/mooculus/calculus1/rulesOfDifferentiation/digInBasicRulesOfDifferentiation).  These have the advantage of being exactly what the Ohio State students use, so feedback would be helpful.  (Also [the source for the activities is on GitHub](https://github.com/mooculus/calculus/blob/master/rulesOfDifferentiation/digInBasicRulesOfDifferentiation.tex) so pull requests are also helpful...)

**Comment by hanjiexi** [comment]
@kisonecat Professor Fowler, before I continue, let me speak on behalf of OSSU when I say that your contribution to our curriculum, and to open education in general, is immensely appreciated!

Ximera confused me the first time I looked at it; it looked like both a project page for converting LaTeX to HTML as well as an interactive textbook for math. (From a purely marketing and UX perspective, these probably should be separate websites.) When opening that textbook, I saw a big grid of tiles, with no obvious visual indication of where to start or which direction I should go in (right vs. down). It's natural for me as a native English speaker to start in the top left and move to the right, and upon closer inspection I can verify that this is correct because the section numbers increase when moving in this order, but I (much too hastily) dismissed the website because I worried students will be confused by it, and also by the lack of video instruction which they may have come to expect from the rest of OSSU CS.

However, after your post, I took a second look at Ximera and I'm impressed at what it's accomplishing. It's a *lot* more interactive than Khan Academy and most any other video-oriented calculus course, and it includes Calculus 1-3.

My reservations about the user interface remain — I think a simple, linear outline would be a lot clearer than the dynamic tiles. And I also hope there would be a clear indicator of when exactly in the sequence one could watch the (optional) video lectures you made. But these are just cosmetic/UX issues. In the short term, OSSU CS can mitigate these concerns to some extent by having an explanation of how to proceed through the course; in the long term, it's useful that Ximera and the courses are on GitHub so that we can directly influence its direction.

@waciumawanjohi do you see any academic/pedagogical reasons why we shouldn't use Ximera?

**Comment by waciumawanjohi** [comment]
I don't read anything that changes my opinion of Ximera. The one thing that we've learned is that users can make pull requests to improve the Ximera site. But the one request that everyone is making (integrate the videos into the curriculum), @kisonecat addresses (dismisses) by pointing out we can find the videos elsewhere.

If we look at the OSSU students in this thread, we see clear trends.

1) Students feel that the move of Mooculus to Ximera degrades the educational experience:
@leungleoqin "they don't contain the video lectures - which IMO is the best part of the course."
@hanjiexi "that Ximera site looks terribly designed" "It's a lot more interactive than Khan Academy and most any other video-oriented calculus course, and it includes Calculus 1-3... My reservations about the user interface remain"

2) Students value the MIT offerings:
@jeremy-gray "How about the Calculus courses listed on the OSSU Data Science curriculum?"
@jkuzmanovik "Trust me these are one of the best courses on this topic..Profesor Leonard is best professor in math"
@Nixerrr "These are well produced and high quality, but very demanding as well. I did the first course and I needed to supplement it with extra material to fully grasp everything."

3) Khan Academy does a good job ensuring that students learn how to do Calculus calculation.
@Nixerrr "Both the Calculus AB and Calculus BC playlists of Khan Academy are really good and extensive with loads of exercises. They could be viable candidates as primers for the U Penn Calculus course."

You (@hanjiexi) write, "OSSU CS can mitigate these concerns [lack of video integration] to some extent by having an explanation of how to proceed through the course" I point to my earlier comments, "That seems like quite a bit of effort and it's not clear what that effort is in pursuit of. If the [Ximera] course is insufficient, why try to custom make tweaks and fixes rather than recommending a course that is sufficient?"

You compare Ximera and Khan Academy, so I looked to do the same. I looked at one topic, the Squeeze Theorem. How is this topic handled by Ximera and Khan Academy?

Instruction:
The Ximera page states "The Squeeze theorem allows us to exchange difficult functions for easy functions." Then there is a sentence restating that. Then the theorem is written. Then students are asked questions. There is no attempt to give an introduction or an intuitive explanation of the Squeeze Theorem. If you want to find Fowler lecturing about the Squeeze Theorem, you have to search Youtube and find the video "What is the limit of (sin x)/x? - Week 1 - Lecture 7 - Mooculus". I was able to find it only because a search picked up user comments asking questions that included the term "Squeeze Theorem". Neither the title nor the description mention the theorem introduced in the video.

The Khan Academy page begins with an intuitive explanation for the theorem. The next video is an example problem solved with the theorem. Two additional videos are available (they are ordered after the assessment, so they are presumably optional).

Assessment:
Ximera begins with a multiple choice question. If the student answers correctly, they are told, "Correct". If they are incorrect, they are told "Try again". No additional feedback is given. There are then 3 example problems where students fill in values as they are walked through a problem. At each step they are told that their answer is either right or wrong. There is no additional feedback. There are no additional problems.

Khan Academy expects students to correctly answer 4 questions about the Squeeze Theorem. A student can get a hint if they are having trouble with a problem. If they attempt the problem and get it wrong, they can see a walk-through of how to solve the problem. If the student gets 75% of the questions correct, the subject is marked "Practiced". If they score below 75%, they are encouraged to try again with 4 new problems. Once a topic is marked "Practiced", students will be encouraged on future days to try a problem or two to ensure that they remember what they learned.

The Ximera examples are more complicated than the Khan Academy questions. The Khan Academy questions ask students to identify the limit given a graphical representation of three functions and also when given two known polynomial equations bounding an unknown. The Ximera questions all involve trig functions, one involves the behavior of the exponential.

Coverage:
One important aspect that I didn't compare is coverage. In the past I have had issues with both Khan Academy and Mooculus not adequately covering topics. Regarding Mooculus, the OSSU curriculum recommends students take an MIT course on parametric equations and polar coordinates because the Mooculus Coursera course did not cover that material. Regarding Khan Academy, in the past I have been frustrated that a number of trig identities were not covered in their pre-calculus material. Without further study of the current platforms I can't say one is better than the other regarding coverage. (I did note that both platforms have sections on polar coordinates and parametric equations)

Time:
One of the positive aspects that you point to is that the Ximera course includes more than it did previously ("it includes Calculus 1-3"). But the reason Mooculus remained in the curriculum was because it was shorter than the MIT courses (in part by covering less). It's unclear how long it would take students to progress through the newly organized material. Without surveying students who have attempted all of the material on both platforms, it's hard to see how to judge the time until completion. It's not clear that we should assume students will master calculus faster by studying the Ximera material rather than studying the Khan Academy or MIT material.

Conclusion:
Khan Academy does a better job than Ximera on both instruction and assessment. Lectures are tightly integrated in Khan Academy, while the Ximera site does not attempt video or text explanations of a concept. Khan Academy offers more assessment questions than Ximera, more feedback on those questions, more opportunities to demonstrate mastery, and requires more consistency. I would certainly prefer that Khan Academy include some questions of increasing difficulty, such as the ones that Ximera offers. But this does not outweigh the other advantages.

Based on all of this, I think OSSU should recommend either Khan Academy or MIT/edX for calculus. The original benefits of the Mooculus course (engaging lectures and a short timeline) have been watered down. The strengths of the other platforms remain apparent.

**Comment by kisonecat** [comment]
As a lead developer for https://github.com/XimeraProject/server this is very helpful.  A goal of Ximera is to empower learners with the ability to click edit, to "look under hood," and to contribute to the curriculum, so I am always deeply appreciative of feedback.  We still have further to go with UX.

I didn't intend to be dismissive about the lack of videos.  I really like my videos, and I'd like them to be part of the Ximera content.  Our online students at Ohio State actually access Ximera from within a Canvas course which includes links to homework exercises and videos in addition to the links to the textbook.  We haven't unified that content within ximera.osu.edu but that is definitely a goal.

Another project to help with videos is [CuratedCourses](https://curatedcourses.org/) which proposes tagging resources (like videos) and similarly tagging textbooks, so that the right margin of a textbook like the one on ximera.osu.edu can be populated with the most effective videos (along with other curated OER resources).  This is an NSF-funded project (DUE-1505246) and we'll be organizing a workshop at UT-Austin in August 2018 to continue work on this.  Let me know if you'd like to be involved!

**Comment by hanjiexi** [comment]
Thanks @kisonecat for those clarifications. I think we will definitely include Ximera under OSSU's extras/readings section, and consider reinstating it into the main curriculum if all of the concerns are eventually addressed.

I haven't had enough time to do an in-depth evaluation of all these different options. I am still interested in somehow utilizing U Penn Calculus in the future due to its computational focus, but this requires further analysis to see what would be needed to prepare students for this course. However we need to fix the broken curriculum, so let's go with MIT Calculus for now and re-evaluate later. I will make the update myself unless @leungleoqin or @waciumawanjohi are interested in making a PR. (Let me know within the next 24 hours.)

**Comment by kisonecat** [comment]
No problem.

And Ghrist's calculus course is really neat; hopefully you can include it.

And if the OSSU crowd is interested in Ximera more broadly, we'll be running an event in Columbus, Ohio on July 9-10 at Ohio State ([register here](http://go.osu.edu/xw5application)) and another event in October 2018 in Gainsville, Florida ([register here](http://go.osu.edu/xw6application)).  UFlorida is sponsoring the October event and hoping to provide funding for interested participants.

**Comment by kisonecat** [comment]
No problem.

And Ghrist's calculus course is really neat; hopefully you can include it.

And if the OSSU crowd is interested in Ximera more broadly, we'll be running an event in Columbus, Ohio on July 9-10 at Ohio State ([register here](http://go.osu.edu/xw5application)) and another event in October 2018 in Gainsville, Florida ([register here](http://go.osu.edu/xw6application)).  UFlorida is sponsoring the October event and hoping to provide funding for interested participants.

**Comment by hanjiexi** [comment]
I put OSU Calculus (now called Ximera) into extras/readings; MIT Calculus is now our recommended course. Thanks everyone!
