### ISSUE TITLE
Resource to learn haskell for free video 

### ISSUE THREAD

**Issue by Abhi18022** [ossu/computer-science#471]
https://onlinecourses.nptel.ac.in/noc18_cs22/preview

have a look at this i think this can be really usefull. :)

**Comment by waciumawanjohi** [comment]
An interesting find. There's currently an Intro to Haskell course in extras/courses:
https://www.seas.upenn.edu/~cis194/fall16/

Are you planning to take one of these courses? If you do, could you also do a survey of the other course for comparison's sake?

Once you've done that, will you share with us which you think is the better course for OSSU? Feel free to ping other students that would be interested (try reaching out to people in the gitter chat room) in joining you in that!

**Comment by Abhi18022** [comment]
https://onlinecourses.nptel.ac.in/noc18_cs22/preview : This course provide video lectures that's why quite more benifical for slow readers like me.(This one will be more preferable by me as a indian)  

https://www.seas.upenn.edu/%7Ecis194/fall16/ : No doubt this source is also awesome to learn haskell.

**Comment by hanjiexi** [comment]
For everyone's information: I will leave our current Haskell resource as-is until we can get some feedback on both this and the resource in #472. Ideally we would be able to replace Learn You a Haskell for Great Good (since I understand it's pretty out of date now, plus it's a book not an interactive course), but I want to make sure we're choosing the best resource.

**Comment by hanjiexi** [comment]
I'm continuing the conversation on this in #472
