### ISSUE TITLE
Pre calculus alternatives

### ISSUE THREAD

**Issue by SplotCoding** [ossu/computer-science#474]
Hi everybody,
I used some years ago this book and it's a good start for a "calculus journey": http://www.stitz-zeager.com/

There is also another book: CALCULUS LIFESAVER. I think it's not free but it has an old but good video course on its website: https://press.princeton.edu/video/banner

Bye

**Comment by ashraymallesh** [comment]
Hi. I worked through Axler's "Precalculus" (He's the author of the famous linear algebra textbook "Linear Algebra Done Right"). I'd say that it is a rigorous primer for a calculus course. After working through something like this, you should be good to take Calc I courses (but not UPenn obviously)

**Comment by hanjiexi** [comment]
Thanks for the suggestions, I think the Zeager book on precalculus could be added since its license fully permits redistribution. I am not so clear on Axler's *Precalculus*; it looks like you would have to buy it.

@SplotCoding Feel free to open a pull request to include the free precalculus book under extras/readings.md. I am closing this issue for now.
