### ISSUE TITLE
Few more things needed to added.

### ISSUE THREAD

**Issue by Abhi18022** [ossu/computer-science#476]
I am a computer science and a IT enthusiast since last few years. 
On basis of my research and experince i have noticed some significant difference between being a CS guy and being a IT guy. 
but i strongly belive that a combination of CS and a IT will be awesome.
the fundaments difference between a CS and a IT guy is that CS guys knows the skeleten part of the computer's very well like physics and maths behind computers and a IT guy knows to use the Computer tools really well. 
as said in nand2tetris most of the IT guys just deal with the API level of Computers. 

Sites like Udemy , cbt-nuggets are for the IT guys and sites like edx.org and MITOCW and MOOCS are for CS guys. 
but development in both the fileds is actually required to be a successfull computer engineer. 

I have some alternatives to udemy like spoken-tutorial.org which provides tutorials on tools of computers. I think some of these kinds of sites which provides free skill set's on increasing yours typing speed , using tools , and other IT stuffs can be added in next level.

There are lot's of computer science students i know don't even have a good typing speed. LOL
I hope i have made my point enough visible.

**Comment by robbrit** [comment]
Many CS graduates end up going into "IT" fields like Devops, SRE, or infosec. It's a great way to make a living, since there are many more jobs than pure CS.
There are plenty of resources for learning this stuff online, like [Google's SRE book](https://landing.google.com/sre/book.html).

The problem with IT fields are that they tend to go obsolete pretty quickly. IT has changed significantly in the 10 years since I finished my CS degree (Devops didn't even exist back then), and I don't doubt it will change again in the next 10 years. CS on the other hand is still mostly the same - you still have trees and recursive algorithms, etc. When moving into IT the most important thing isn't any specific tech you learn, but your ability to pick up new things quickly. If you can't do that, you probably won't have a long career.

**Comment by Abhi18022** [comment]
@robbrit exactly and i agree with you but now a day's a lot of teen are just jumping into the IT field rather then having a CS base first and people who have a CS base don't seem's to be quite productive in short tearm because of there lack of basic skill set's with computer. 
Computer too is like a musical instument where you may have studied all the math's and physics behind yet you need to spend a lot of time with it to learn to play it.
