### ISSUE TITLE
Some edX courses now paywalled

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#478]
@andrewtcooper pointed out to me in #422 that some edX courses, even without certificate, now cost $9. I have checked all our course links and found that following courses are now paywalled:
- How to Code: Complex Data
- Software Construction: Object-Oriented Design
- Software Development Capstone Project

Paywalling How to Code: Complex Data hurts. It's one of the best courses we have and now we have to remove it. I understand that edX had to make [a business decision](https://blog.edx.org/furthering-the-edx-mission) to support themselves, but it really messes up our curriculum as is and creates uncertainty about whether we can rely on any edX courses to stay free-to-access.

This underscores the need to replace all proprietary content in our curriculum with open-source content and ultimately to self-host our content as much as possible. How to Code: Complex Data is actually under a [semi-open license](https://creativecommons.org/licenses/by-nc-sa/4.0/), so hypothetically we could host parts of it ourselves. (I am less concerned about the other two courses, in fact I don't care at all about losing Software Construction.)

Self-hosting open-source content is a big deal and a ton of work, and we would face some funding questions ourselves. Discussion about that should go in #422. For right now, in order to maintain as much stability in our curriculum as we can, I'm thinking to:
- temporarily replace "How to Code" with the book upon which it's based ([*How to Design Programs*](http://www.ccs.neu.edu/home/matthias/HtDP2e/))
- completely remove Software Construction; I'm not finding any good alternatives and we do have some coverage of object-orientation elsewhere in the curriculum
- replace the Software Development Capstone Project course with our own required capstone project

Objections? Suggestions?

**Comment by raialok** [comment]
Some courses (How to Code: Simple Data & How to Code: Complex Data) are very good and even unique. They focus on how to think about the structure of data that leads to a good program.

I don't think the curriculum should be 100% free. Rather, the focus should be providing a cheap (preferably free), high quality, content. In this case, the courses are of exceptional quality and should not be removed until there is an acceptable alternative. 

One possible choice is How to Design Programs textbook but I feel that the course takes far less time and is far more approachable than  the book.

**Comment by jlollis** [comment]
It looks like you can still enroll to audit How to Code: Complex Data for
free, without the verified certificate. I don't see any content that is
hidden behind the paywall. I hope that doesn't change.

**Comment by hanjiexi** [comment]
How can the full course be audited for free, and if it can, what does it
mean to unlock the full course for $9? Does the $9 just buy access to the
final project?

I see that there is a link to try it out, but I can't tell what that does.
I already took the course so there's no way for me to test it myself.

**Comment by andrewtcooper** [comment]
I first noticed the paywall due to a reddit thread on r/learnprogramming a few days ago. At the time, edX seemed to be playing around with which courses were being paywalled and which ones were not, so the courses in question kept flipping back and forth between saying "Free" and saying "$9". At one point, I got it to let me enroll in the How to Code: Complex Data course while it said it was free, which I'm still enrolled in; however, they have retroactively implemented the paywall for that course. What that appears to mean is that you have access to a small portion of the course for free, but to access the majority of it, you need to pay. See screenshots: https://imgur.com/a/e9sC9uU

My opinion (as someone who is just starting out in this endeavor, currently working on pset1 of CS50x) is that I definitely understand the point being made about wanting to keep it entirely free due to it being a slippery slope if paid material starts being included, and where do you draw the line etc. I would not pay $9 for a garbage course (i.e. the apparent consensus on Software Construction) but I would pay $9 for an excellent course (i.e. the apparent consensus on How to Code: Complex Data). I am just one person, and am fortunate enough to be working a full-time white collar office job in a first-world country, so $9 isn't very much to me for something worthwhile. There are certainly people out there, though, who could have an interest in OSSU, to whom $9 is a lot. 

The question is, are they going to start paywalling everything, and will it stay at $9 for the foreseeable future, or could that steadily start to increase? Who knows, but I think that coming up with a permanent solution of some kind is definitely a worthwhile longterm goal, and the fact that this is happening certainly imparts a sense of urgency to the matter. 

As for me, I am going to continue on with the curriculum as it is now, and when I get to the point where I would be taking this course, if there is no suitable replacement at that time and the course costs $9, I'll probably just pony up the cash.

**Comment by hanjiexi** [comment]
Thanks @andrewtcooper; your screenshot confirms that the course is truly paywalled after a student's free trial expires.

> I am just one person, and am fortunate enough to be working a full-time white collar office job in a first-world country, so $9 isn't very much to me for something worthwhile. There are certainly people out there, though, who could have an interest in OSSU, to whom $9 is a lot.

I agree. My current working assumption is that OSSU is of the greatest benefit to two types of people:
1. Those who are already affluent enough to afford plenty of free time to study after work so they can change their careers
2. Those who have much potential to be great computer scientists or programmers but for some reason need an alternative means of getting there (perhaps financial hardship, or in some countries the education system is inflexible)

The former category can afford to buy courses — and they should, as I believe instructors deserve to get paid by those who can afford it. We should assume the latter category cannot afford to do so. A common model is to give the latter category a free education and some kind of soft job guarantee, and then require the student to pay back their debts after getting a job, but this has a very high administrative/legal overhead and it's not clear to me if that model has been successful.

We would need full community consensus if we were to start allowing paid courses into the main/required curriculum. I suspect we will not get that consensus, but I'm open to being proven wrong.

**Comment by a1h05** [comment]
There could be 2 options for each subject:
1 - free(always provided)
2- paid(only if free option is behind in quality) 

Pros: Curriculum will be affordable for all groups of students. Curriculum quality will be preserved(or even become better)
Cons: Harder to maintain/read.

**Comment by jlollis** [comment]
Did you see the option to audit when you first signed up? After I clicked
"Audit this Course", everything is unlocked. I'm not sure if that is
different for different regions though. The verified certificate costs $125
from what I can see.

See instructions here:
https://support.edx.org/hc/en-us/articles/206914937-How-do-I-take-a-course-for-free-


I hope this is helpful and applicable to your situation.

**Comment by hanjiexi** [comment]
It looks like all the courses in the [Software Development MicroMasters](https://www.edx.org/micromasters/software-development) have just been flipped back to the way they were before. This seems to be consistent with @andrewtcooper mentioning that edX keeps flipping courses back and forth. So our short-term problem is temporarily solved... until edX decides to flip them back again...

**Comment by timeneverdie** [comment]
I found _How to Code: Simple Data_ is not paywalled, but the enrollment is only once. Maybe you should register more accounts to take part in the course.
