### ISSUE TITLE
UBCx: HtC2x How to Code: Complex Data - cost 9 dollars

### ISSUE THREAD

**Issue by xnortk** [ossu/computer-science#480]
I'm not exactly sure of the cost criteria for a course to be recommended as part of the curriculum, but I got very upset to learn that my path to a free self-taught education will be incomplete, I'll just skip this one.

Anyways, UBCx: HtCx How to Code: Simple Data  was free to enroll.

Thanks

**Comment by hanjiexi** [comment]
To me it appears to be free. Is edX still switching it back and forth...?

**Comment by hugoribeiros** [comment]
Oh!, I see, I'm sorry. It might be the country I'm in? Do you have access to the week 8a: Two One-of Types? 
![screen shot 2018-05-20 at 18 56 53](https://user-images.githubusercontent.com/25829432/40284127-806fab2c-5c60-11e8-9298-6672f6d8079e.png)

**Comment by tiffany-washburn** [comment]
I tried opening "How to code: complex data" on mobile, and am still hitting a paywall, unfortunately.

**Comment by netship02** [comment]
In India it is free try to enrol with some vpn.

**Comment by Ruzo** [comment]
I hope that I'm not the only one who's ok with paying for a quality course. I'm not really sure when "free" became a requirement since it's not listed as one in the description. Maybe there should be a free course as an alternative when the main one is behind a paywall? I think that a paid course could still be a much more accessible option than an on-site one at a University.

**Comment by hanjiexi** [comment]
Having paid alternatives/upgrades is fine, but our current policy is that
there has to be a free track because the point of the curriculum is to have
the highest quality possible "do it yourself" style education. We have no
idea what the economic situations are of OSSU students; $9 may be a lot for
some people, even if they somehow have access to a computer (perhaps
they're borrowing one in a library).

**Comment by oldink** [comment]
Indeed Jack Ma founder of Ali Baba had a monthly salary of $10. He had to eat and fulfill the necessities of life within that.

**Comment by ShirazSuleman** [comment]
Can't we not have the free option but also list a paid alternative, for people who can afford it?

**Comment by hanjiexi** [comment]
That's my intention for now. We will have to replace How to Code with the book it's based on in the official curriculum, but with a note that students can take the (possibly paid) course as an alternative.

**Comment by amorriscode** [comment]
@hanjiexi I think a book really isn't a fantastic replacement for a full course.

1) Some people might not have access to the book at their library, or even access to a library at all.
2) I doubt that any computer science books can be snatched up for under $9 (the price of the edX courses).
3) More personal but following along with _just_ a book is more difficult for me.

Due to the three reasons above, I don't think a book is really the perfect alternative for a "free" option.

**Comment by hanjiexi** [comment]
@amorriscode You're right, it's not a good replacement, but edX is leaving us little other choice. We came to depend on them and now they're de-stabilizing their pricing. Here is the reply I received from edX:

> I apologize for the confusion. This is a soft paywall which we are testing at the moment. Some students will see this others won't since it is still very much in the testing phase. Please keep in mind that this $9 soft paywall is **optional**, so anyone who sees it is welcome to bypass it and still access the course for free.

I don't know how students are supposed to bypass the paywall; he didn't give instructions for doing this.

Regarding the book, it is [entirely free](http://www.htdp.org/).

The "How to Code" courses are based on *How to Design Programs*, which itself is an attempt at rethinking the pedagogical approach of *The Structure and Interpretation of Computer Programs*. Another option is using a course based on SICP such as this [MIT OCW course](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/), but that course's links to the online textbook are broken.

However, using an SICP-based course would change the curriculum even more than using the HtDP textbook, which would at least vaguely preserve the same topics.

**Comment by ChrisTsou** [comment]
i checked again the course today and the paywall disappeared for me.

**Comment by Sanius** [comment]
ucbx course Software Construction data abstraction is also not free for my account.
I searched the keyword 'Software Construction' on edx and found 2 courses from MITX: [Software Construction in Java](https://www.edx.org/course/software-construction-java-mitx-6-005-1x) and [Advanced Software Construction in Java](https://www.edx.org/course/advanced-software-construction-java-mitx-6-005-2x). 2 courses are archived already, but they're free.
Are these courses able to replace 2 software construction courses from ucbx?

**Comment by hugoribeiros** [comment]
Not to be annoying guys, but the UBCx: Software Construction: Data Abstraction also does cost 9 dollars now here where I am (I ended up paying and did the UBCx: HtC2x How to Code: Complex Data, btw)

**Comment by hanjiexi** [comment]
Is it still unavailable for free for anyone? I'm unable to verify as they all appear to be totally free for me.

**Comment by anoddduck** [comment]
Under my old edx account, which has several completed courses, some of
which I paid for a certificate, — HtC2x requires $9 to access full course.
I created a new edx account three weeks ago, the full course is appeared as
free.

**Comment by hanjiexi** [comment]
@anoddduck Are you suggesting that they make some free courses appear as paywalled to users have paid before? I wasn't able to verify this with my account but it could still be true.

**Comment by anoddduck** [comment]
@hanjiexi -- I thought the paywall may have remained for accounts enrolled
at a specific time when paywall introduced, or for accounts that completed
HtC1x.
I just checked my old account, and the paywall has now been removed.
May have occurred within the last 1.5 weeks, as I checked my old account
during that time to avoid repeating first coursework section.

I also created my new account in a new region - due to moving.  To test, I
just created a new account via VPN in Europe, and declared European
residence on account. No paywall appears for the new account.

**Comment by hanjiexi** [comment]
Thanks @anoddduck, I'm closing this for now until more evidence turns up that edX have started paywalling again.

**Comment by dancek** [comment]
I enrolled today. The course is now visible only for a limited time for free:

> Audit Access Expires Sep 23, 2019
> You lose all access to this course, including your progress, on Sep 23, 2019.
Upgrade by Aug 26, 2019 to get unlimited access to the course as long as it exists on the site.

Additionally all the quizzes are hidden unless you pay.

<img width="1101" alt="Questions are only available for Verified Track learners" src="https://user-images.githubusercontent.com/245394/62463884-df8ac580-b793-11e9-9b77-fbecc42f9a1c.png">

**Comment by kenuxi** [comment]
@dancek I have the same. Tried from a couple of other countries and it seems there is only the option of buying it for $125.... I'd be happy to pay $9 for it but this is just a bit much for some basic coding. Looks like the whole micromaster now costs $900

**Comment by s7oev** [comment]
Same. I'd be fine with paying $9, but $125 for a whole course is a bit too much, IMO. And it's a shame, since I've been planning to take it from some time, but apparently this change is very recent. I signed up for it in February, just to check the content, and now I've lost the access to it. I do think a new account should solve that.

But, going back to @dancek 's post: can someone that knows the course comment on whether the situation was the same with the quizzes before as well? I.e., it does say to pay for graded assignments, which makes sense. But, is it new that they are completely hidden? Does this make taking the free version of the course useless?

**Comment by waciumawanjohi** [comment]
I've opened an RFC about How to Code. Please comment! https://github.com/ossu/computer-science/issues/588
