### ISSUE TITLE
Why was "CS 162: Operating Systems and Systems Programming" removed?

### ISSUE THREAD

**Issue by silvirus12** [ossu/computer-science#499]
I would like to know why this course was deleted?

**Comment by MohamedMandouh** [comment]
I'm not sure if it was ever here ,
but I'd like to know what do you think of it .
I had three courses on programming  CS50 and how to code : simple , complex data
I already taken an introductory course on OS at college 
and taken Computation structures of MIT
Do you think I've what it takes to take it ?
thanks in advance @silvirus12

**Comment by hanjiexi** [comment]
I think it was removed before I joined the project. However, looking at the [website](https://cs162.eecs.berkeley.edu/) for CS162, it looks like much of the material isn't available, because it's the actual course website and they don't release the relevant material until the appropriate day.

**Comment by MohamedMandouh** [comment]
there's a website
http://infocobuild.com/education/audio-video-courses/computer-science/cs162-spring2014-berkeley.html
which has all video lectures for all offerings since 2011 until 2015

at the end of the page there's a link to the courses page that contains all the material you need

however , this course requires a group project to be done in a group of 5 
that means you can't achieve full benefit from the course if taken individually

**Comment by hanjiexi** [comment]
Thanks for pointing this out to me. The website looks a bit shady though; I'm concerned that those videos might not be authorized reproductions...

The course looks good content-wise but I don't think we can use it in its current state.
