### ISSUE TITLE
Changes in README not reflected in CHANGELOG

### ISSUE THREAD

**Issue by jstnlester** [ossu/computer-science#515]
I noticed that CS50, once a course under Introduction to Computer Science, has been moved to Core Systems as a prerequisite to Nand2Tetris. However, the CHANGELOG does not reflect this substantive change.

**Comment by hanjiexi** [comment]
I know, no worries. Ever since we started using the `dev` branch for live changes and only occasionally merging into `master`, we've been batching the updates to the changelog (and to the curriculum's version number). We are preparing for v9 and the changelog will reflect all changes since v8 once it's tagged.
