### ISSUE TITLE
Edx experimental paywall and how to avoid it

### ISSUE THREAD

**Issue by Ridten** [ossu/computer-science#534]
Some edx courses now uses paywall in test like in screenshot below
![paywall](https://user-images.githubusercontent.com/10984003/48782587-31172100-ece7-11e8-9c2c-c97c507084ec.png)

Here a way to remove it.
Open developer tools by Ctrl + Shift + I, then go to Application -> Cookies, find `partner_experiment_exclusion`  and change value to `false`

![paywall-remove](https://user-images.githubusercontent.com/10984003/48782588-31afb780-ece7-11e8-8767-30a07cfb9be0.png)

After edition just refresh page
![paywall-removed](https://user-images.githubusercontent.com/10984003/48782590-31afb780-ece7-11e8-84c3-7009c1f024a4.png)

**Comment by hanjiexi** [comment]
Thank you! This is exactly what I've been looking for.

Can anyone else verify that this trick works? It is hard/impossible for me because I have never encountered the paywall before. (I haven't yet figured out the logic of how they decide upon whom to inflict the experimental paywall.)

Once I get some more verification, the instructions can be incorporated directly into the repo.

**Comment by MemDem** [comment]
Hi,

I confirm that trick works like a charm on both Chrome and Firefox.

________________________________
Gönderen: hanjiexi <notifications@github.com>
Gönderildi: 27 Kasım 2018 Salı 03:31
Kime: ossu/computer-science
Bilgi: Subscribed
Konu: Re: [ossu/computer-science] Edx experimental paywall and how to avoid it (#534)


Thank you! This is exactly what I've been looking for.

Can anyone else verify that this trick works? It is hard/impossible for me because I have never encountered the paywall before. (I haven't yet figured out the logic of how they decide upon whom to inflict the experimental paywall.)

Once I get some more verification, the instructions can be incorporated directly into the repo.

**Comment by jturner421** [comment]
This no longer appears to be a valid option.  The cookie referenced earlier does not appear in the panel.

**Comment by anickrik** [comment]
anyone has something similar to it cause i facing the same issue!

**Comment by daniel65dj** [comment]
Can't find the cookie either. You have to take into consideration that this cookie was when the paywall was "experimental" and almost all new courses are paid or free for audit only.

**Comment by Ridten** [comment]
@daniel65dj can you provide example of curse free for audit?

**Comment by daniel65dj** [comment]
The how to code series:
![image](https://user-images.githubusercontent.com/20648137/79980518-c4cbbe80-8492-11ea-9778-913cb72b96f4.png)

**Comment by stoyko90** [comment]
You have to click audit the course, that's free as is the case for most of
these courses, don't expect to be able to submit assignments and get
certificates and to still have everything free. There is nothing 100% free
in this world.
