### ISSUE TITLE
Calling all students: what was your favorite introduction to computer science?

### ISSUE THREAD

**Issue by hanjiexi** [ossu/computer-science#548]
Hello everyone,

For the next version of the curriculum, I am currently planning for the "Intro CS" section to consist of a small number of community-generated recommendations. Since experience has shown that it is impossible to arrive at a consensus for "one intro to rule them all", I'm looking for a handful of resources that cover a wide spectrum of student backgrounds. New students should be able to choose *one* resource out of these recommendations, probably by matching their own personal backgrounds to the backgrounds of the people who recommended a certain resource.

The purpose of Intro CS is to get students' feet wet and inspire them to continue with the rest of the curriculum. Besides the fact that it does need to be some sort of introductory resource, I don't have specific requirements for what content is taught or the manner/format of teaching, as long as it's not irrelevant. The rest of the curriculum starting with Core CS won't make any assumptions about what content students did or did not learn in Intro CS.

My requirement is instead that the Intro CS material be of high overall quality, unlikely to disappear from the Internet, and emotionally engaging/inspiring for *you*, given your background, interests, and tastes. So **I'm asking that you share your story, including what background you had in CS and/or programming before starting the material, and what it was about the resource that inspired you to pursue studies in CS**. We might directly share some student testimonials whose purpose would be to indicate to a new student whether this is the right resource for them to choose.

In the last week of December we'll select 3-5 to put into Intro CS, with the criteria for selection based on variety. Specifically:
- Each video-based course we select should be very different
- Each text-based resource (which could be a book or a tutorial) should be very different
- However, we can group text-based resources together with video-based, i.e. same content for the same backgrounds, but different formats for different learning styles (or bandwidth limitations)

**Comment by bradleygrant** [comment]
### If you're like me...

**Perhaps you come from a technical background, but you never learned any coding** – or you did it so long ago, you forgot nearly everything you learned. You see data all day long at your day job, and Excel just isn’t cutting it anymore… but you don’t (yet) know where to go from there.

**Math may or may not be your friend, but you can multiply and divide**, and you know what squares and square roots are (even if you haven’t done them in a while). If you vaguely remember logs and exponents, or sines and cosines, it’s helpful, but not necessary. If you’re a math whiz, all the better; if not, it’s okay.

**You suspect that numbers and statistics have a story to tell, if only you can learn how to read them.** Your interests might lie in analysis, data science, machine learning, or maybe even web apps. You’re attracted to OSSU because you suspect that a deep knowledge of algorithms and databases is the key to solving all the problems you want to solve. You’ll get there in time…

**But for right now, you just want to learn to code.** You want to get up to speed in a language widely used in industry and in practice. Once you leave this course, you want to be able to actually **do something** with the knowledge you’ve gained. And you want to start today, if possible.

**You work best in small, quick hits.** You don’t have the time, or the patience, or the concentration, or the sheer force of will, to sit down and watch 90-minute lectures or read some boring book about code. You get your motivation through a long series of quick wins. You want to get your hands dirty and do lots of little practice examples. You want to see yourself getting progressively better, more competent week after week.

**But you don’t want the bootcamp experience – all fluff, no substance.** You want to understand WHY you’re doing what you’re doing – after all, you’re interested in *computer science*, not *just* programming – and you want to learn principles that you can take to other languages.

**Most of all, you need a course that doesn’t assume anything** – it teaches you from the ground floor, step by step, building all the way. It doesn’t throw you to the wolves and expect you to keep up.

I can’t tell you what to do – but I can tell you what worked for me…

…and if you’re like me, then maybe it’ll work for you too.

### Here's what I'd recommend

**Step 1:** Take the Georgia Tech CS1301 Computing In Python series on EdX.

*Why these courses?* CS1301 is a very beginner-friendly introduction to fundamental computer science principles and to the Python language, and doesn't assume any prior CS or programming knowledge. Its biggest strength is the sheer number of 3-5 minute coding problems which help you retain knowledge and build confidence as a programmer. Homework assignments and end-of-unit tests help you see how far you've come. The course is self-paced with open entry; you can begin today.

Courses | Duration | Effort
:-- | :--: | :--:
[Computing In Python, Part I: Fundamentals and Procedural Programming](https://www.edx.org/course/computing-in-python-i-fundamentals-and-procedural-programming-0) | 4 weeks | 10 hours/week
[Computing In Python, Part II: Control Structures](https://www.edx.org/course/computing-in-python-ii-control-structures-0) | 4 weeks | 10 hours/week
[Computing In Python, Part III: Data Structures](https://www.edx.org/course/computing-in-python-iii-data-structures-0) | 4 weeks | 10 hours/week
[Computing In Python, Part IV: Objects & Algorithms](https://www.edx.org/course/computing-in-python-iv-objects-algorithms-0) | 4 weeks | 10 hours/week

**Step 2:** Take the MIT 6.00 Introduction to Computer Science series on EdX.

*Why these courses?* 6.00.1x has long been the gold standard OSSU introduction course, but many found it to be too challenging as a first course. Taking this course extends the knowledge gained in CS1301 while providing more practice on harder problem sets. The second course, 6.00.2x, describes how one might use computer science to solve real-world problems in optimization and statistics. It provides context for further study in computer science, and is especially relevant for those interested in data science and machine learning. *6.00.2x does require significant comfort with mathematics through college algebra; the course provides a working introduction to probability and statistics.*

Courses | Duration | Effort
:-- | :--: | :--:
[Introduction to Computer Science and Programming using Python](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-10) | 9 weeks | 15 hours/week 
[Introduction to Computational Thinking and Data Science](https://www.edx.org/course/introduction-computational-thinking-data-mitx-6-00-2x-2#!)| 9 weeks | 15 hours/week

**Step 3:** Proceed to the [OSSU Core CS Curriculum](https://github.com/ossu/computer-science#core-cs), starting with How To Code: Simple Data.

*Optionally:* Dual-enroll or transfer to the [OSSU Data Science Curriculum](https://github.com/ossu/data-science#python) to continue developing familiarity with Python.

**Comment by navimac** [comment]
Hello everyone,
I followed ossu while CS50 was still in intro to CS with MIT introduction to CS with python. I did both courses and found them very instructive. At first I planned to finish all cs50 but I have to agree with recommendation to abandon it whet it leaves C. 
Here is my overview of both classes: 
1. Intro to CS from MIT:
* Week 1 introduces you to the world of computation. It makes you think about program as a recipe, idea of abstraction, branching and iterative programs...
* Week 2 is about basic data types, functions for abstracting piece of computation, recursion algorithm (strong emphasis on this although I think iterative algorithms are more efficient)
* Week 3 more complex data abstractions although they are objects which are more powerful then mere data containers but this is for somebody with more knowledgeable to explain in more details
* Week 4  testing and debugging which is not explained well in my opinion. For example only after HTC: Simple data I started to test my functions
* Week 5 OOP --> mixed feelings about this
* Week 6 big O very well explained
2. CS 50
* Week 0 about computation, imperative knowledge,...
* Week 1 lot of topics from how is C source code compiled to program, primitive data types (including arrays), branching, loops, variable scope, constants, command line args, debugging tools
* Week 2 sorting algorithms, binary search algorithm
* Week 3 memory organization (stack, heap, ...), pointers, file pointers, stdin/stderr/stdout
* Week 4 more about memory. compound data (struct), data structures (linked list, heap, trie )
* Week 5 here they started to get too broad --> trying to explaine TCP/IP network stack, CSS, HTML,...
* Week 6 dynamic programming (I understand it but having trouble to implement it --> idea is to build look up table for known values if computation and use them as heuristics), very very rough intro to python
* Week 7 very rough intro to building web apps with Flask framework. Here I stopped because I noticed that it adds now value to fundamentals and introduces to much abstraction that I don't understand how they worked so I stopped

Also I am doing HTC:Simple data and I think it is also recommended as a entry course into OSSU but in my opinion this is not introductory course and it would be best taken after some intro course as it adds systematic approach to design programs and some experience of writing programs before would be great as a foundation to this course
This is it guys hope it helps!

**Comment by Zaphain** [comment]
I'm not finished with 6.00.1x MIT's Intro to CS with Python yet and am on the problem set for Week 5, however, I felt the need to speak about this a bit even if this information might not be needed anymore. This is the first time I've been really engaged and motivated to keep up with an introductory CS course. I feel the material and the way it is represented as well as the charisma of the instructor, Eric Grimson, and the difficulty of the problem sets has just been a perfect experience. For whatever reason I found I really couldn't keep myself motivated for CS50 and never got that far in it so I'm really thankful that OSS has pointed me to this.

**Comment by doct0rX** [comment]
I would go with CS50... it's the way i started and the way I recommend...
CS50 is a bit heavy than MIT 6.00.1 as it discuss more topics and introducing a variety of topics in computer science so you can have a wide view of the field and how it looks like! unlike 6.00.1 is focused on one area which i don't recommend as an intro.

**Comment by waciumawanjohi** [comment]
Lots of great thought here. It has led to an RFC on adding Intro to Programming options to the beginning of the curriculum. Comments welcome! https://github.com/ossu/computer-science/issues/589

**Comment by lowendgamer** [comment]
@bradleygrant Thanks for the CS1301 recommendation, I will try it this week. 

Honestly, I struggled so much with Mitx 6.00.1x pset1, especially the 3rd the question. Hopefully this will prep me up more to handle it better next time.
