### ISSUE TITLE
I completed CS50, should I start Introduction to Computer Science and Programming using Python

### ISSUE THREAD

**Issue by Rita1** [ossu/computer-science#550]
I completed CS50 and now wondering if I should start intro course: "Introduction to Computer Science and Programming using Python"  or skip it? CS50 was my first course about programing. Would be intro course useful for me?

**Comment by waciumawanjohi** [comment]
@Rita1 as noted in the curriculum, Intro CS is recommended "for students to try out CS and see if it's right for them". If you completed CS50 and found yourself interested in learning more, I recommend diving into Core CS. I also suggest that if you have more questions about individual approach (rather than suggested changes to the curriculum) that you post in the [OSSU CS Gitter](https://gitter.im/open-source-society/computer-science). There are often individuals there who will be happy to talk about their experience and offer advice.
