### ISSUE TITLE
All EdX courses are now limited

### ISSUE THREAD

**Issue by W-Alizee** [ossu/computer-science#552]
https://openlearning.mit.edu/news-events/blog/statement-regarding-edx-platform-updates-long-term-sustainability

It seems that EdX is now going to charge all users who wish to

a) access a course after it's archived
b) access graded materials

I have not seen an option to pay ~$9 for access but instead only see paying the full price for a verified certificate. I just began these paths so I don't even know how to use GitHub so I hope this is in the right place. I'm just beginning AP CS50 (HarvardX) for school and Introduction to Computer Science and Programming using Python as part of the OSSU curriculum and would like to complete the entire curricula soon within 4 or 5 years :)

I'm not sure if there's a way around this. I tried editing EdX's partner exclusion cookie like a user suggested for a different version of the paywall but I'm not sure if this will let me access archived courses now.

Thank you

**Comment by hanjiexi** [comment]
The good: now they will finally be *clear* about what is free and what's not instead of the constant flip-flopping.

The bad: many universities may choose to just paywall all their graded material.

For MITx courses, however, they make this promise:
> MITx will maintain all content that supports learning as part of the free, audit track. Our faculty will determine which assignments in their courses are integral to the learning process and make this work available to all learners. As always, learners will be able to enroll in the audit track for free and upgrade to the verified track before the published deadline; work that they have already done is then counted toward their grade. In many MITx courses, graded quizzes and exams with a primary purpose of assessing whether learners are qualified to earn their certificate will now only be available on the verified track.

So it may still be safe to use MITx courses (assuming their instructors make good choices), and experience will have to tell us whether other universities are as generous as MIT.

In the short-term, we may just have to accept that some courses will cost money for a good experience.

**Comment by hanjiexi** [comment]
It is kind of amazing that the traditional MOOC platforms lasted as long as they did under the old model, with edX being the last to fall. The whole concept was just ridiculous and completely ignored everything that's been learned about consumers.

Building a sustainable online business means either getting a small number of people to pay a lot of money or a huge number of people to pay small amounts each. The only way to get people to buy something is to offer something of value that you can't easily get if you don't pay. If there is a convenient workaround, the masses will use it. (Piracy is usually inconvenient.)

So if what you're selling is *content*, then you have to paywall almost all of it. I believe this has been working just fine for Udemy since day one. In the old days, the content on Coursera and edX was all free, and what they were selling was certificates. But the certificates were almost completely worthless; at most, students who purchased them had a slight bump in completion rates, but they weren't usable for anything else.

For a free MOOC business model to work, you would need to offer something that is genuinely worth it for a relatively small number of parties (not necessarily students) to spend enough money to completely sustain the entirety of free users. And if you have the additional bottom line of being sustainable, like OSSU does, then there cannot be a tight coupling between the business and the operations. It would need to be possible to sustain the entirety of its operations on the shoestring budget of most ordinary open source projects. The business, if there would be one, would just be something "off to the side" and totally optional, even invisible to most community members.

As has been proven in the collapse of the old model of Coursera and now edX, the old model was not economical. The new model probably doesn't go far enough to be economical; producing MOOCs can be very expensive and I expect most universities will move towards more paywalling.

**Comment by W-Alizee** [comment]
> It is kind of amazing that the traditional MOOC platforms lasted as long as they did under the old model, with edX being the last to fall. The whole concept was just ridiculous and completely ignored everything that's been learned about consumers.
> 
> Building a sustainable online business means either getting a small number of people to pay a lot of money or a huge number of people to pay small amounts each. The only way to get people to buy something is to offer something of value that you can't easily get if you don't pay. If there is a convenient workaround, the masses will use it. (Piracy is usually inconvenient.)
> 
> So if what you're selling is _content_, then you have to paywall almost all of it. I believe this has been working just fine for Udemy since day one. In the old days, the content on Coursera and edX was all free, and what they were selling was certificates. But the certificates were almost completely worthless; at most, students who purchased them had a slight bump in completion rates, but they weren't usable for anything else.
> 
> For a free MOOC business model to work, you would need to offer something that is genuinely worth it for a relatively small number of parties (not necessarily students) to spend enough money to completely sustain the entirety of free users. And if you have the additional bottom line of being sustainable, like OSSU does, then there cannot be a tight coupling between the business and the operations. It would need to be possible to sustain the entirety of its operations on the shoestring budget of most ordinary open source projects. The business, if there would be one, would just be something "off to the side" and totally optional, even invisible to most community members.
> 
> As has been proven in the collapse of the old model of Coursera and now edX, the old model was not economical. The new model probably doesn't go far enough to be economical; producing MOOCs can be very expensive and I expect most universities will move towards more paywalling.


"EdX currently has 14 million learners, up 10 million learners in 2016. These learners accounted for more than 50 million course enrollments, 16 million of which came about in 2017."

Currently owler.com shows their annual revenue at ~14 million USD but I don't know if that's accurate... even at $2 per course they'd have way more than 14 million USD.... re-distribute the money according to the number of enrollments like Amazon's Kindle Unlimited, maybe?


I don't know if the information above is correct or not but $50 to $125 per certificate seems a bit much, but maybe that's because I'm an orphan/ward of the government :/ at least until I aged out and I've kind of been struggling along ever since.

At least there's financial aid if things get really bad, but they limit it to 5 courses per 12 months!


I hope OSSU's curriculum can find suitable replacements if things get totally paywalled though :/

Thank you for your reply, by the way! :)

**Comment by Alaharon123** [comment]
How would that be feasible in the long term? Sounds expensive plus you'd need to get permission for every course and you'd lose out on the forums in the official courses.

Side note, I wonder how they'd fare with Wikipedia-style pleas for donations. Might be a harder sell since afaik they're not non-profit, but idk.

**Comment by hanjiexi** [comment]
Static hosting of content costs nothing (i.e. GitHub), and some content is licensed under terms permitting redistribution, e.g. https://ocw.mit.edu/terms/#cc. However, I have not done any comprehensive review of the content licenses and don't intend to anytime soon. For right now the priority is building a strong curriculum and promoting a community of learners who support each other.

**Comment by cinephile85** [comment]
It looks like they're now going to force you to go verified unless you can complete courses in about a month and a half on the audit track.

I guess it's gonna be books and YouTube for some of us.

**Comment by cinephile85** [comment]
Just a thought. If significant portions of the curriculum now require payment, it might be prudent to update "free" to "low-cost". Full disclosure kind of thing. I hope this gets worked out. I was really looking forward to some of the courses I won't be able to afford to take.

**Comment by W-Alizee** [comment]
> > "EdX currently has 14 million learners, up 10 million learners in 2016. These learners accounted for more than 50 million course enrollments, 16 million of which came about in 2017."
> > Currently owler.com shows their annual revenue at ~14 million USD but I don't know if that's accurate... even at $2 per course they'd have way more than 14 million USD.... re-distribute the money according to the number of enrollments like Amazon's Kindle Unlimited, maybe?
> 
> Haha, you're right. I don't know if the numbers are accurate either, but if they are, and we assume each course costs $100 (I think they range from $50-350), that would mean they only have 140,000 paying users per year... which is insane if it's anywhere close to the real number.
> 
> My goal for a long time now has been for OSSU to self-host all content, to a certain extent. It is not feasible in the short-term.

I intended to imply Amazon Kindle Unlimited style funding. Basically, you pay a monthly fee for unlimited access and the funds are distributed to content creators based on how many people are reading their books. For example, if you buy "Sample Book #1" the author gets paid based on how many pages you read. If EdX adopted that style, I was hoping it could lower the price point instead of paying per certificate and then divide the money based on which courses are being used more. So if you enroll in 50000 courses, only the courses you're actually using will be paid, which reflects usage and therefore the cost EdX must pay to host the course and the courses that nobody wants to enroll in can be identified and improved upon or removed. And by limiting the number of courses that way, the funds can be divided in such a way that the creators actually get paid reasonable sums. For example, Kindle Unlimited costs $10 per month and the average author gets only $2 per book and anyone can create an ebook and dilute the "pot" of money and reduce payouts even further. By capping the number of courses, EdX could avoid this problem and keep payouts enough to fund creators and so on.


But, anyway, uh... what if you replaced a lot of EdX courses with something like Lynda.com or PluralSight courses? VisualStudio is open to new developers and gives plenty of free trials and has a referral program that means you can get one month free for every user who joins via a referral l ink, and although it's not very proper or developer-friendly, there are quite a lot of torrents for those who truly can't afford it.

On the other hand, as an alternative to PluralSight, Lynda.com has an organization subscription. Many libaries in the USA offer library cards for free to their patrons and many of these libraries offer Lynda.com unlimited subscriptions with their library card, so their patrons can get lynda.com for free. I know many libraries also allow non-residents to buy annual library cards with unlimited access as well. For example, one local library system I know offers a $99 annual library card which gives out-of-state or non-resident persons complete access to complete library resources, which include lynda.com, a tutoring subscription which gives tutoring in calculus and college subjects like programming and IT certifications, 12 free ebooks per month through Hoopla and other ebook providers like OverDrive, scholarly books and more.  http://orion.pbclibrary.org/online-research 

This might be doable for most people, financially speaking.

**Comment by waciumawanjohi** [comment]
This conversation appears to have run its course. Closing.
