### ISSUE TITLE
Software Construction in v9 draft

### ISSUE THREAD

**Issue by Alaharon123** [ossu/computer-science#553]
In the [v9 draft of Core Programming](https://github.com/ossu/computer-science/wiki/Core-Programming-draft#imperative-computation), MIT Software Construction in Java on edX replaces UBC Software Construction from v8. I see two problems with this. Note that this is coming from someone who looked at the structure of both, but the content of neither so I don't know if one is actually of significantly higher quality or whatever.

1. MIT Software Construction in Java is an archived course and all the Java Tutor parts are no longer available. This appears to mean that the course no longer teaches Java and assumes that you already have that knowledge.

2. The obvious solution would be to instead use the ocw version. This is definitely a better idea; after all, it does include 2 pages intended to teach Java. https://ocw.mit.edu/ans7870/6/6.005/s16/getting-started/java.html and https://ocw.mit.edu/ans7870/6/6.005/s16/classes/02-basic-java/. However, and someone else can say if this is actually enough to learn Java, it seems pretty cursory to me. MIT even offers a class (not on OCW) specifically to prepare students for 6.005 called 6.178 Introduction to Software Engineering in Java plus a prerequisite of 6.01. All of which means to say, it doesn't seem like the best fit for ossu.

On the other hand, UBC Software Construction only assumes that you've done How to Code: Simple and Complex Data, which are already on the OSSU curriculum. On campus as well, the only prerequisite is cpsc 110, their version of How to Code. UBC Software Construction seems to be a much better fit for the OSSU curriculum than the MIT equivalent.

**Comment by hanjiexi** [comment]
Thanks for the heads-up about MIT's course not being fully available anymore. I knew it would likely be too advanced, but I had it there as a placeholder as I do need some kind of Java course to bring students up to speed on Java to the extent needed for the courses on parallelism and concurrency. I haven't found better alternatives yet, but these topics are too important to exclude just because the resources are sparse.

UBC Software Construction is unfortunately kind of bad. Due to the UBC Software Development MicroMasters being designed for people who just want to quickly jump into a new career, the UBC Software Construction courses tend not to take a very shallow approach to teaching Java, not really explaining the semantics in a deep or effective way. Two problems with this:
- They don't provide a useful transition from SPD (which uses an almost purely functional style). The major changes to program semantics and data design that occur when moving from functional to imperative style are never explicitly laid out. (It is non-trivial to convert from one style to another as typically one style has to dominate the types.)
- They ask students to wade into unfamiliar codebases in a language they barely know. It is certainly useful to practice diving into unfamiliar codebases but this skill is not relevant at this point in the curriculum, and it's not effective when you don't know the language.

They also (at least in the first course of the pair) teach discredited design principles that came from the old days of the OOP fad, and they use some of the worst analogies I've ever heard, like (if I remember correctly) comparing abstraction boundaries / interfaces to the tip of an iceberg...

I will have to take a look at Helsinki's Java materials. It might be just what's needed. Thanks!

**Comment by Alaharon123** [comment]
Interesting! I kind of just assumed (unlike 6.005 where I took a somewhat closer look) that UBC's would be good since it officially relies only on HtC so that's good to know that that's not the case. I was going to take UBC regardless of what OSSU does; now I'm going to take Helinski regardless of what OSSU does.

**Comment by Marc5x** [comment]
Hi I just finished Software Construction: Data abstraction from UBC. What do you recommend continuing with Software Construction: Object-Oriented Programming or switch to the MIT course on OOP or Helsinki's?

**Comment by Alaharon123** [comment]
@hanjiexi I think I found the perfect resource. I looked through all the colleges that use HtDP to see what they do next and Worcester Polytechnic Institute has the course material for its next course online for free. The professor who changed their CS1 course to use HtDP, Kathi Fisler, is co-director of Bootstrap, an organization whose directors include one of the authors of HtDP and are getting HtDP into middle schools. Anyway, she also created a CS2 course that builds on HtDP and though she has switched to Brown, WPI still uses her material and it's all available online at http://web.cs.wpi.edu/~cs2102/b16/

I also found an article by another of the authors of HtDP, Matthias Felleisen, detailing Northeastern's approach to teaching Computer Science (which uses HtDP in CS1). At the end of the article he lists some other places that have adapted/adopted this curriculum and has this to say about WPI's implementation.

>Kathi Fisler mapped out an adaptation of our first-year curriculum at WPI. Her adaptation improved on several aspects of Fundamentals II (CS2)

The article is also super interesting: http://www.ccs.neu.edu/home/matthias/Thoughts/Developing_Developers.html

**Comment by Alaharon123** [comment]
@Marc5x I apologize that I don't have an answer for you. I was really hoping someone else would answer. On the side of UBC's course, you're already halfway through a two course sequence so you may as well finish it up, on the other hand it's apparently a bad course. On the side of MIT's course, you've already done some Java so you may as well switch over and do a course that's actually good and you can just do the Java tutorials it links to and you'll probably be fine, on the other hand, you're restarting from the starting and will likely cover some material you've already learned. On the side of Helsinki's course, it's pretty much the definitive resource for noobs to learn Java so you may as well start there, on the other hand, it's for noobs so you've probably learned many of the concepts it's teaching even if not specifically in Java. On the side of WPI's course, it's actually meant to continue on from the equivalent of How to Code: Simple and Complex Data so you'll learn the material in a way that makes sense and builds on your HtC knowledge, on the other hand, you're restarting and it doesn't really cover the same material as the UBC and MIT courses and maybe that's actually something that the curriculum wants to be covering now (though it doesn't sound like it from @hanjiexi's comments here.

So I hope that gave you some idea of what the pros and cons might be, but I can't really give you any advice here. I'm guessing at this point you've probably already made an arbitrary decision and are just going with it.

**Comment by Marc5x** [comment]
@Alaharon123 also ask if it's better doing the MIT course skipping the material I've already done than doing the second part of UBC.

**Comment by Alaharon123** [comment]
Idk from a curriculum perspective, but there's a week 0 type thing in the parallel programming course that asks you to program some things and says if you're comfortable with what it's asking then you're ready to take the course. Or something like that.

**Comment by Alaharon123** [comment]
Can't comment on MIT vs UBC. You're the one doing the actual course so you'd be able to see how well they line up.

**Comment by Marc5x** [comment]
Okay thanks anyway!

**Comment by Alaharon123** [comment]
I got the entirety of http://web.cs.wpi.edu/~cs2102/b16/ put on the wayback machine so if it gets taken down at some point, there's a copy from February 2, 2019

**Comment by dleister77** [comment]
fyi, i noticed that mit previously did 6.005x on edx (back in 2016) and materials are available archived.  They broke it into 2 courses.  haven't tried them yet, but wanted to make sure you were aware they were still available.
https://www.edx.org/course/advanced-software-construction-java-mitx-6-005-2x
https://www.edx.org/course/software-construction-java-mitx-6-005-1x

**Comment by Alaharon123** [comment]
That's what I'm referring to in the op

**Comment by waciumawanjohi** [comment]
Closing this issue because:
1) There have not been any new comments in 10 months.
2) There is a new timeboxed RFC on Software Construction for the current curriculum.
