### ISSUE TITLE
Python 2 in extras/courses

### ISSUE THREAD

**Issue by Alaharon123** [ossu/computer-science#554]
The following courses in extras are still being taught in Python 2.
- [Introduction to Computer Science (Udacity)](https://www.udacity.com/course/intro-to-computer-science--cs101)
- An Introduction to Interactive Programming in Python (part of the [Fundamentals of Computing Specialization](https://www.coursera.org/specializations/computer-fundamentals))

The second one can be replaced by the [Introduction to Scripting in Python Specialization](https://www.coursera.org/specializations/introduction-scripting-in-python) taught by the same people, but the first one has no replacement afaik. Is it time to remove these courses from extras/courses?

**Comment by waciumawanjohi** [comment]
Python 2 [end of life date is 2020](https://www.python.org/dev/peps/pep-0373/#id2). Numerous courses are still taught in Python 2. And a [sizable minority](https://www.jetbrains.com/research/python-developers-survey-2018/#python-3-adoption) of programmers still use Python 2 as their primary version.

What's more, we aim to evaluate courses on their academic qualifications rather than their tooling. If a course has a flawed approach to CS, we should look for an alternative. But an excellent course that uses a slightly older language is... an excellent course.
