### ISSUE TITLE
Do I need to do the coding assingments with Linear Algebra - Foundations to frontiers?

### ISSUE THREAD

**Issue by riceeatingmachine** [ossu/computer-science#577]
I'm dong Linear Algebra - Foundations to frontiers.

It appears to be overly focused on running DSL matlab code.

I was wondering if this is a necessary part of the OSSU, or just a skipable quirk of that course.

**Comment by MohamedMandouh** [comment]
@OmarElawady can you help?

**Comment by ArmarCoder** [comment]
i think you should solve some problems in linear algebra to make sure that you understand the concepts

**Comment by riceeatingmachine** [comment]
Thank you so much for the reply. I really appreciate your time/

I was inuring regarding the slicing and dicing and the coding of the MATLAB functions to compute matrices efficiently. Are those necessary? It just seems wildly unrelated and just a quirk of that particular course.

I understand the concepts. Its just that doing those repetitive matlab programs doesn't seem to be a good use of time.

**Comment by OmarElawady** [comment]
Solving the programming problems in general helps in actually seeing the cost of the operations in terms of memory accesses and flops, and to get a better intuition about the steps of the algorithm. I did the first few and it was more like copying a template and filling in the voids rather than actual programming and both the analysis and the algorithms described in the course were pretty simple and I got accustomed to it by solving the problems in the homework, so I skipped the rest.

**Comment by riceeatingmachine** [comment]
Thank you for your input @OmarElawady
