### ISSUE TITLE
Competitive Programming

### ISSUE THREAD

**Issue by ganesh003** [ossu/computer-science#584]
At what point of the curriculum will I able to take part in competitive programming contests, what courses should i finish before i will be ready for spoj , codechef and topcoder sites?

**Comment by waciumawanjohi** [comment]
https://www.spoj.com says that it is for individuals to _Learn how to code and build efficient algorithms_. I would say this is a site to try out as you are working on the algorithms courses in OSSU.

https://www.codechef.com has a banner that reads _New to Programming and don't know where to start?_ I would try it out right away.

https://www.topcoder.com advertises that it's goal is to _Design and build high-quality software with crowdsourcing._ I would begin this after having some success on other platforms.

I didn't use any of these sites, but I did start doing coding problems online after completing my first course.

I'm curious what other students think. When did you take the plunge into a coding challenge platform or into a competition? Is it possible to try too early? I'll leave this issue open for a week to get a variety of voices.

**Comment by Vallerious** [comment]
I’d say, in the starting phase, then take up something else when you get comfortable with the language and solving problems. Then, I’d say, just before interview and after you passed maths and algos.

**Comment by aquaruiz** [comment]
I believe it's hard to decide. If you start too early and fail - you might get discouraged for a long time period. But, if you are eager enough, you will try again soon.
Me? I am still idle.

**Comment by pachecohjr** [comment]
Yeah, the atypical person could tackle these problems head on, especially when they are only using basic paradigms because every once in a while, you can call a certain library or function to help you. I was certainly discouraged early and failed. But, now after having went through college, I feel more confident given the algorithm courses and math courses taken. 

I would suggest definitely to go through a big Algorithms course first, with some background in discrete math.

**Comment by pachecohjr** [comment]
Also, do look into the other several sources. I got one big one resource link for you. Every college normally has an Association of Computing Machinery (ACM) club. since they hold national to world competitions like ACM-IPC every year. 

http://programmingprogress.blogspot.com/2014/11/competitive-programming-sites-by.html This list is updated pretty regularly.

https://www.mycplus.com/featured-articles/programming-contests-and-challenges/

My favorite site: https://algorithm.city/Home

This is a very good intro to competitive programming book: Competitive Programming 3 The New Lower Bound of Programming Contests by Steven Halim, Felix Halim

**Comment by pachecohjr** [comment]
Also, do look into the other several sources. I got one big resource link for you. Every college normally has an Association of Computing Machinery (ACM) club. since they hold national to world competitions like ACM-IPC every year.

http://programmingprogress.blogspot.com/2014/11/competitive-programming-sites-by.html This list is updated pretty regularly.

https://www.mycplus.com/featured-articles/programming-contests-and-challenges/

My favorite site: https://algorithm.city/Home

This is a very good intro to competitive programming book: Competitive Programming 3 The New Lower Bound of Programming Contests by Steven Halim, Felix Halim

**Comment by amanWamda** [comment]
I used hackerrank, i think you can solve easy problems in java and solving problem sections after you finish fìrst and second courses from core cs, try to solve problem first and read disscussion then, your skills will be better by completing remai courses and still practice
