### ISSUE TITLE
are all the courses at least before the advanced section self-paced and free ????

### ISSUE THREAD

**Issue by ahmedbenammar029** [ossu/computer-science#597]
are all the courses at least before the advanced section self-paced and free ???? and I noticed that some courses require java or C, will I have to learn em before enrolling to fully grasp the course?

**Comment by waciumawanjohi** [comment]
At the moment, no. edX has recently changed their audit policy, which means that a number of early courses are now very limited without payment. We are currently discussing what to do about the earliest such course in the curriculum.

https://github.com/ossu/computer-science/issues/588

As for java and C, I see that Programming Languages A currently recommends Java and C as a pre-req. I think this is a "nice to have" and would recommend taking Programming Languages A directly, rather than stopping to study those languages. C is more important for _Core Systems_, which is why we recommend CS50 as a primer for the language. There is also an open issue on switching CS50 for another resource:

https://github.com/ossu/computer-science/issues/516
