### ISSUE TITLE
Add repo to computer science in brazilian portuguese

### ISSUE THREAD

**Issue by SEdilson** [ossu/computer-science#603]
Hey guys, i wanted to contribute with the project by translating the content of this repo to brazilian portuguese. What you think?

**Comment by osvaldoabel** [comment]
i think it's a good a good idea!

**Comment by waciumawanjohi** [comment]
@SEdilson If you write it, I would be happy to merge in such a pull request. I'll leave this issue open for 2 weeks so that you can get a sense of how much interest there is from other users.

OSSUnians, if you want to encourage the translation of the curriculum, show your support by adding a thumbs up to @osvaldoabel's comment.

**Comment by victorwestmann** [comment]
+1 for this suggestion! I could help review the contents in a distant future.

**Comment by SEdilson** [comment]
Great, i intend to start as quickly as possible, perhaps next week i'll have something to share with you guys.

**Comment by waciumawanjohi** [comment]
Sounds good @SEdilson 
Thanks for putting work into making OSSU more accessible to students!
I'm going to close this issue (since you have an answer to your original question). Those of you who have commented should keep an eye out for a pull request here:
https://github.com/ossu/computer-science/pulls

**Comment by Luleps** [comment]
I can hardly believe this will happen, I'm very excited and willing to help
with that

Em qua, 25 de set de 2019 às 00:16, waciumawanjohi <notifications@github.com>
escreveu:

**Comment by victorwestmann** [comment]
Together we are stronger! Let's help more people access this content while studying this material ourselves. ;-)
