### ISSUE TITLE
Question about Design Patterns

### ISSUE THREAD

**Issue by DevJ5** [ossu/computer-science#619]
So far Im really enjoying this curriculum and I appreciate all the hard work that went into this. I have a question about design patterns, from my understanding they are not part of the curriculum. Is this intentional? I have gotten the impression that they are a big topic in CS, could you please enlighten me? Thank you.

**Comment by gab-dev** [comment]
I think a lot of them are learned indirectly through the courses.
In the reading list there is a reference to the most important book about them.
This is a good answer about design patterns https://www.quora.com/What-are-the-most-important-design-patterns-to-master-for-a-programmer/answer/Tim-Mensch?ch=10&share=10364fd2&srid=uos5g

**Comment by waciumawanjohi** [comment]
@DevJ5 
Design Patterns are a very important topic in software engineering, which is a bit distinct from Computer Science. An example of a computer scientist could be someone very interested in computability, exploring what kinds of questions can and cannot be computed by any theoretical computer. A software engineer, on the other hand, is interested in writing programs that do useful things.

Design Patterns are strategies for writing programs so that they are easy to change and modify. This is solidly in the wheelhouse of the software engineer.

The book in the readings is known as the Gang of Four book. It is a very well known text and is a touchstone patterns catalogue. However, I recommend that you read Head First Design Patterns. This book is aimed at learners and is very approachable.

I'll leave this issue open for a week to let others weigh in on your question.
