### ISSUE TITLE
"Introduction to Computer Networking" closes March 26

### ISSUE THREAD

**Issue by MRensen** [ossu/computer-science#635]

**Comment by waciumawanjohi** [comment]
Interesting. It looks like this is the case for all long running courses on Stanford Lagunita.

This article suggests that the materials should stay available:
https://stanfordonline.zendesk.com/hc/en-us/articles/203244640-When-courses-run

I've reached out to Stanford Online through their helpdesk tool. I hope to hear back soon. We'll have to keep an eye out for whether the materials remain available in April. Closing this issue for now, but we should reopen it if course materials are not available on March 27.

**Comment by Phylake1337** [comment]
a gentle reminder to check the course link, it's not working.

**Comment by waciumawanjohi** [comment]
This is the current link in the curriculum:
[Computer Networking: a Top-Down Approach](http://gaia.cs.umass.edu/kurose_ross/online_lectures.htm)

It directs to an available site with instructional content and quizes. The curriculum further has links to labs for students. If you see a different link, make sure you use the curriculum at cs.ossu.dev rather than duplicates of old material (of which there are a number).
