### ISSUE TITLE
I meet a big problem: Core theory needs Mathematics for Computer Science

### ISSUE THREAD

**Issue by timeneverdie** [ossu/computer-science#683]
Okay, I know math is very important and I am always studying it.

However, if I want to learn core theory, the first course needs **Mathematics for Computer Science**. But Mathematics for Computer Science needs the **Calculus 1C**. Calculus 1C needs **from Calculus 1A to the end**!

So I cannot learn core theory until I finish nearly all the core math? Is it right?

I need your help!

And also, why not add the specific lessons for algorithms and data struct?

I recommend these two courses:

Algorithms: MIT 6.00.6 (Youtube has full video and maybe EDX will have the latest version)
Data structure: https://www.youtube.com/playlist?list=PLpPXw4zFa0uKKhaSz87IowJnOTzh9tiBk

**Comment by aryzach** [comment]
I'd say Calculus might help with Mathematics for Computer Science, but you should be able to take Mathematics for Computer Science without it. It's a hard class, but I don't think it relies on any Calc explicitly. Algorithms might rely on calc a bit though. I haven't taken core theory yet. But I would probably recommend at least taking Math for CS before Algorithms just based on what I know about algorithms outside of that class.

**Comment by idrissathiam01** [comment]
What about adding this specialization from Coursera?
https://www.coursera.org/specializations/discrete-mathematics

**Comment by daniel65dj** [comment]
![image](https://user-images.githubusercontent.com/20648137/77834050-5e30da80-714a-11ea-8b62-41b19a7a23ba.png)

**Comment by spamegg1** [comment]
I would not get stuck on silly requirements if I were you. Tim Roughgarden's courses are self-contained and cover all the required math. Hell, he basically teaches you Graph Theory from scratch, making Math for CS redundant IMO. I learned much more Graph Theory from the Algo classes than the Math for CS class.

Math for CS depends on Calculus because of Probability calculations in it. However the Probability calculations required in Core Theory are completely self-contained and taught from scratch by Roughgarden. No Calculus knowledge required. All you do is some analysis of randomized Quicksort, where you calculate some discrete probabilities "by hand" (kinda like coin toss/dice throw), and then sum over a finite set of possibilities by using the independence of random variables. THAT'S IT.

The whole requirement thing is WAY overblown in my opinion.

**Comment by waciumawanjohi** [comment]
Lots of suggestions in this thread. In addition, there is the suggestion of the curriculum, which is to study discrete math before studying algorithms. If you still would like feedback on alternatives to the curriculum, the [gitter](https://gitter.im/open-source-society/computer-science) is a great place to ask.
