### ISSUE TITLE
OStep Videos + projects

### ISSUE THREAD

**Issue by netship02** [ossu/computer-science#707]
http://pages.cs.wisc.edu/~remzi/Classes/537/Spring2018/
http://pages.cs.wisc.edu/~remzi/Classes/537/Spring2018/Discussion/videos.html
I think this is better then current one
It has same homework(as book), same professor, and projects with test scripts, also lot of discussion videos.

**Comment by waciumawanjohi** [comment]
I support this change. Material is substantively the same. Lectures are delivered by the author of the textbook. Information is all organized on fewer pages, simplifying navigation for the student.

Will leave this issue open until June 5 for comments. If there are no objections, I'll merge in a change.

@netship02 would you like to create a pull request now that reflects the change you envision? This can help others have a clear understanding of the change that you're proposing.

**Comment by waciumawanjohi** [comment]
@netship02 It is now June 5 and I've heard no objections. If you make a [pull request](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) for this change, I'll merge it in.

**Comment by Heasummn** [comment]
@waciumawanjohi I made a pull request editing the course if you'd like to take a look at it and approve it. I think it lines up with what @netship02 intended.

**Comment by waciumawanjohi** [comment]
@Heasummn thanks for reminding me that this change is overdue to be merged in. I was waiting on @netship02 because I wanted the contributor section to reflect that he had proposed this improvement to the curriculum.

As the videos are linked on the 2018 course page, I think it makes the most sense to have just a single link. Rather than do a back and forth asking you to alter your pull request, or creating multiple commits to reflect what is truly one change, I'm just making a commit and closing your pull request. I hope you don't mind.

And as I said, good on you for jumping in to get this improvement committed!

**Comment by Heasummn** [comment]
That's all good. I actually found the OSSU and contributed to it a long time ago when it was Eric maintaining the project, but after I had gone through the main curriculum I stepped back. I've been looking at it and the newer recommendations in recent years now that we've all got more free time and just wanted to dip my feet into contributing again.

**Comment by waciumawanjohi** [comment]
Glad to hear! Are you on [gitter](https://gitter.im/open-source-society/computer-science)? I'd love to have a 1-1 and hear what you've been up to and how you'd like to contribute to OSSU!
