### ISSUE TITLE
Update 'Missing Semester' info

### ISSUE THREAD

**Issue by aryzach** [ossu/computer-science#715]
I just 'finished' the course. I've taken 14 or so OSSU classes and found this very helpful and wish I'd taken it earlier (especially the Vim chapter). The class is laid out and meant to be completed in 11 class days and 18 calendar days. I half-heartedly tried to keep up with their schedule (videos and exercises), and found it somewhat impractical. The videos take 45 mins - 1 hour, and the exercises vary in number and time required. Roughly 2 - 10 exercises some taking 5 minutes while others could take 2+ hours. 

From what I remember, the class assumes you're on Linux, so I often found I didn't have the programs installed (on Mac), which made some exercises take a lot longer (install time, install issues, etc). Also, lots of the exercises required some research to learn the tool / how to do the task which is good, but can take a lot of time depending on the task.

The two issues I see are:
 - we don't assume OSSU students are running linux
 - suggesting completion of all exercises is not what I think the class creators intended, and also is a potentially non-trivial distraction from continuing with the Core CS curriculum 

Some examples and thoughts from my experience:
 - Intro/Shell: not much to say (suggested exercises: 1 - 9)
 - Shell tools: not much to say (suggested exercises: 1 - 3)
 - Vim: I use Vim regularly, and thought this part was really great. That said, learning to use and customize Vim is an incremental process. New users would be not be helped by all the exercises because you need to use Vim regularly to become efficient and have perspective on what you'd like customized (suggested exercises: 1, 2, 4, 5)
 - Data wrangling: had lots of install systems with these exercises, and even problems with their specific Mac workaround suggestions (suggested exercises: 1, 2)
 - CLI: I'm on an old computer with limited memory, so I couldn't install any VMs (suggested exercises: possibly all of these)
 - Version control: git is similar to Vim as it's iterative learning (suggested exercises: 1, 2, 5)
 - Debugging and profiling: I had a lot of install issues here and didn't do any exercises, so I can't comment
 - Metaprogramming: I didn't quite have the context for this section to be that useful. It demystified 'make' a little bit, and can't comment on the exercises

After this I read / watched but stopped doing exercises.

Overall, I think at this point in the curriculum (2 - 3 basic programming classes), students won't quite have the context to understand a lot of this (I felt like I didn't when I took it). However, I definitely think it should stay at the current place. I think the purpose of this course should be to introduce students to these tools and serve as a reference, and I think the course designers intended that, too. I see three options rectify these problems: 

 1. Increase the duration / effort from 2 weeks at 12hrs/week to 3 weeks at 15+hrs/week (but tbh, the time required is unbounded if you complete all exercises because of OS/system problems possible with some tools). The problem with this is that I don't think this class is intended to be fully completed on first pass, and that it would be too large of a detour from Core CS.
 

 2. Add to the OSSU course description: 
"This class isn't meant to be fully completed. Watch all the videos (or read the notes), and only do the few exercises that seem interesting in each chapter. This class is meant to introduce you to topics so you know they exist and have a resource to learn if the need later arises. (link to some suggested exercises, and an explanation about possible install issues and what to do if you encounter them)"

I think this option sticks with what this class was set out to be - an introduction and a resource, but not an end in itself

 3. Move the course to later in Core CS. I don't think this is a good idea because students should be introduced to some of the topics ASAP (notably Vim and Git), and even later in Core CS, I don't think the problem of having context gets solved. I think the best way to get context for all of these tools is to build large, real world projects, which we don't do in Core CS

**Comment by Chuphay** [comment]
My opinion as a practicing software engineer is that many of the tools in this course are totally necessary but can also be learned on the job. 
I think this course is aptly titled, because most curriculum are "missing" it (and we should too).

**Comment by mattjperez** [comment]
This might seem a bit unorthodox, but what spreading individual lectures across the total curriculum, wherever they'd be most relevant or useful? They could also be listed as required or supplemental depending on the individual lecture content. 

For example, shell, git, and vim could be listed as required before Core CS with Potpourri and Q&A listed as optional. The security lecture listed as an optional first lecture in the Core CS Security segment. 

Shell tools, scripting, CLI and debugging could be listed in segments where people feel they're most relevant.

This format isn't very 'course' like, but unlike traditional universities, we have the advantage of pre-recorded/self-contained content. We should take advantage of that if we can.

**Comment by aweasadbek** [comment]
I support adding the description to the course. Students should know about ideas given in that course. Description should say something like:
" This course serves as an introduction to the important ideas in programming. It's very likely that you cannot comprehend and solve the problems of this course - do not worry. You should know that the technologies taught in this course exist. You can learn these technologies later when you ready"

**Comment by hanjiexi** [comment]
> I'm on an old computer with limited memory, so I couldn't install any VMs
The recommended approach these days for Windows users is to install WSL. For macOS users, I have no idea — a macOS user would need to chime in here.

Some universities provide Unix/Linux machines for the CS students to SSH into for their assignments in classes like computer systems, operating systems, parallel programming, etc. This gives them a consistent environment to use across many classes.

I somewhat like Missing Semester, although right now it doesn't fit very well into our curriculum. Some of its lectures assume users are using a Linux filesystem with the standard tooling available, but most OSSU courses, due to their MOOC nature, are designed not to assume or require that the student is using a Linux system. This means there are seldom few opportunities for the student to practice what they learned, unless they are curious and self-motivated enough to think about more command line–oriented ways of doing things.

Our recommended operating systems course appears to be the one major exception to the above. If we go with the above suggestion to spread Missing Semester out around the curriculum, perhaps a logical place for the Linux commandline-focused bits of Missing Semester, along with our own community-developed howto guide for getting a Linux system running on personal computers (e.g. WSL on Windows), is as a companion to our operating systems course. However, I think the Missing Semester's Git lecture can stay where it is so students can start contributing to GitHub, archiving their code, etc. I haven't thought much about whether this structure is preferable to keeping Missing Semester where it is, but in any case I do support the idea of adding something like the abovementioned clarifying notes to the Missing Semester.

**Comment by Exkywor** [comment]
Having finished the course, I agree that some students may not be able to get the most out of the course if they are brand new to CS. If splitting and spreading the course along the curriculum is not an option, adding the disclaimer would be the best course of action in my opinion.

**Comment by xNearX** [comment]
Mac OS is unix. Possible solution is to replace that course with a git crash course and move the Missing Semester course into extras perhaps.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by spamegg1** [comment]
Many on Discord are struggling with this course. Maybe move it to Core CS or Advanced CS?
