### ISSUE TITLE
Add MIT's 6.824 Distributed Systems

### ISSUE THREAD

**Issue by bibhashthakur** [ossu/computer-science#721]
I noticed a lack of concrete courses on Distributed Systems in the current curriculum.

Suggestion to add MIT's 6.824 Distributed Systems. The videos are on YouTube and the reading material (mostly academic papers and technical whitepapers) has been made available from the course site.

https://pdos.csail.mit.edu/6.824/schedule.html
https://www.youtube.com/playlist?list=PLrw6a1wE39_tb2fErI4-WkMbsvGQk9_UB

**Comment by aryzach** [comment]
probably would be good in advanced systems

**Comment by waciumawanjohi** [comment]
An interesting resource!

Our [curricular guideline](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md) does make clear the importance of [parallel and distributed computing](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=148). However, within that topic, distributed systems are labeled an elective course. Due to that classification, it seems the best place for this topic is in [Extras/Courses](https://github.com/ossu/computer-science/blob/master/extras/courses.md).

Some notes on the current state of the curriculum: Advanced Programming includes the course Intro to Parallel Programming. And Extras/Courses includes the course Cloud Computing Concepts, which focuses on distributed computing.

**Comment by bibhashthakur** [comment]
@waciumawanjohi I understand the CS2013 requirements and agree this should be an elective course.

Should I open a pull request to put this under Extras/Courses?

**Comment by waciumawanjohi** [comment]
Yes, if you write such a pull request, I'll merge it in. At some point we'll need to go through a more thorough vetting process for the courses in Extras (my presumption is that a course from MIT is high quality, but I've certainly seen cases where the best course comes from another institution). For now an enthusiastic recommendation from an OSSUnian clears the bar for Extras/Courses!

**Comment by spamegg1** [comment]
If I may throw in my two cents here:

The MIT course looks good. Adding it to Extras should be no problem. 

However I would not consider Intro to Parallel Programming to be taking care of the Parallel/Distributed programming requirement of the curriculum. That course is dead and abandoned, and it was impossible to do its assignments until I found that Google Colab page with the Homeworks purely by chance (we don't know how long that will stay up, and the final is still unavailable). It's still near impossible to do without peeking at some solutions; no feedback or debugging, and nobody did the final exam, so we cannot even just read solutions.

These issues seem to be a common theme in low-level, systems programming classes/languages. Easier classes with higher level languages can be OK without any support, but not low-level. This MIT class uses Go, no?

Having taken now two low-level, systems programming type classes in C/C++ and having so much pain and frustration and no support for either, I would also be wary of including this MIT course later on the "front page". I suppose it's OK to just throw it into Extras (kind of a dumping ground to be honest), but without someone actually going through the course we can't know how doable this MIT course is. It could be yet another Hack the Kernel fiasco! References to white papers/research etc. already irks me right off the bat (looking at you, LAFF) as too high-level/difficult and possibly poorly designed/supported. It would be foolish to trust quality just because it's MIT. Hack the Kernel is Harvard!

The Labs have long text instructions with commands, references to Github pages, even tests etc. but are they really doable/debuggable/testable/possible to get some sort of feedback alone, without being registered/logged into MIT and without too much pain and suffering? 

I'm totally not against this issue/pull request of course! 

But maybe it can come with a sort of warning, or something. Like, "we haven't tested this yet!" or "this promises to be very hard, and you are on your own! Move on if it proves impossible."

**Comment by waciumawanjohi** [comment]
@bibhashthakur I'm closing this issue because there haven't been any further comments. But as I said, if you [make a pull request](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) to add this to Extras/Courses, I'll merge the change in.
