### ISSUE TITLE
Update Python 2 to Python 2. 

### ISSUE THREAD

**Issue by raymond-redd** [ossu/computer-science#736]
Is there any option to update the introduction to computer programing course offered by the Rice University? The course uses Python 2 instead of Python 3. 
As Python 2 is slowly turning into to legacy edition, I feel it would be better if someone can find an alternative of the same course in Python 3

**Comment by spamegg1** [comment]
You can use the excellent 2to3 conversion tool:

https://docs.python.org/3/library/2to3.html

You'll have to ask the instructors of that Rice course to update it. I doubt they will. There are MANY MANY courses and even critical software that is stuck in Python 2 even though Python 3 was released in 2008 and people were given 12 YEARS to migrate, so many are still refusing to do it. It's just human nature.

You can alternatively take [MIT's Intro to CS and Prog with Python course](https://courses.edx.org/courses/course-v1:MITx+6.00.1x+2T2018/course/), it uses 3.5.

Otherwise just stick to Python 2 for that course. You can still install it, it's not that bad.

**Comment by raymond-redd** [comment]
Thank you so much for the clarification.
