### ISSUE TITLE
RFC: Harvard's Stats 110

### ISSUE THREAD

**Issue by Cybermise** [ossu/computer-science#738]
Harvard's Stats 110 is a well known course with a really great book that is available for **free** (it also has a lot of intersting exercices, like a lot!). All the lectures are available for free on YouTube and there's a link on their website https://projects.iq.harvard.edu/stat110/home .
Some reviews from students who took the course: https://www.quora.com/Is-Stat-110-worth-taking-at-Harvard
This course like other probability courses can be really challenging in its first parts for a beginner, so I recommend this book too: https://www.goodreads.com/en/book/show/29991429-probability , it goes through everything step by step.

Link to related pull request: https://github.com/ossu/computer-science/pull/733#issue-435876651

**Comment by spamegg1** [comment]
I support adding this as an alternative, as it gives an option to avoid edX's time restrictions, comes with a free textbook, and it seems to be of high quality. 

I looked through the Harvard textbook; it has very good appendixes that can alleviate the Multivariable Calculus prerequisites. I can't say I support the other textbook you mentioned; it doesn't seem to be free.

**Comment by kielejocain** [comment]
I happen to be taking this with my wife now; I am a math PhD and she is not mathematically inclined (though she also has an advanced degree).  I find I have to add additional comment to many topics to help her understand the story.  It may partially be that her motivation is lacking (I SWEAR it was her idea to do this), but Prof. Blitzstein assumes a fair amount of mathematical comfort (I've seen calculus and infinite series so far, and we aren't at the first midterm).

With that caveat, he does a really great job keeping the themes going; you're learning about the stories behind the various distributions, so that when you hear a problem you can recognize the distribution, translate your problem to it, and then--if you need to--simply look up the characteristics of it.  I am enjoying his presentation so far.

**Comment by waciumawanjohi** [comment]
@Cybermise Stats 110 is a go. The textbook is well loved and the course site is complete with lectures and assessments. Math experts above vouch for the quality of instruction as do the reviews that you linked.

Rather than put this in as an alternative, let's make it the solo recommendation and move the current recommended course to Extras/Courses. This will help maintain the clarity of recommended courses for students.

If you make that change to the pull request, I'll merge it in. (And if you have any objection to making the change, reply below and we can discuss it further).

**Comment by waciumawanjohi** [comment]
Resolved with 405df431aa44e049ee40f9300586a556620cbdbd
