### ISSUE TITLE
Four-year structured plan for OSSU.

### ISSUE THREAD

**Issue by azzeezz** [ossu/computer-science#756]
I'm looking for a four year structured plan for OSSU. As it would be better for newbies in CS if there were one.
TIA.

**Comment by StevenKJo** [comment]
@azzeezz  im working on something like this if you want to support it, i leave you the link here:

https://github.com/ossu/computer-science/issues/751#issuecomment-660886018

**Comment by azzeezz** [comment]
@StevenKJo I'd be very happy, if you did.

**Comment by waciumawanjohi** [comment]
Hi Azzeezz,
OSSU's structure is very straight-forward. Choose an intro point. Take every course in Intro CS and Core CS in order. Then choose 1-2 sections in Advanced CS and take every course in your chosen sections. Courses are different lengths, so we list the estimated study time for each.

It sounds like this doesn't meet your expectation of "structured". I'm curious what you feel is missing.

**Comment by waciumawanjohi** [comment]
Also note this entry in the FAQ:
https://github.com/ossu/computer-science/blob/master/FAQ.md#in-what-order-should-i-take-the-courses

**Comment by azzeezz** [comment]
Thanks for you reply.
I'm applying for Computer Engineering in a university. and I want to study Computer Science in parallel, So I need a four year plan like a one any university offers.

**Comment by waciumawanjohi** [comment]
First, best wishes with your university applications! College is great.

As for a plan that mirrors a college schedule, OSSU doesn't have something like that. Universities operate with more constraints (in some respects) and fewer constraints (in other respects).

For starters, a university is responsible for teaching students more than just the core courses of each major. Every university graduate should be able to write. So that is a constraint that universities have that OSSU does not.

On the other hand, universities completely control their schedules. All courses start on the university schedule. That is not the case for OSSU, courses have their own schedules.

Many 4 year universities assume that their students take courses full time. Many OSSU students are working or pursuing other courses. (It sounds like that describes you).

As a result we've found that listing the courses in a sequential order and giving time estimates provides guidance that suits most students. There have been some efforts to create calendars before, but I don't know of any that have been maintained. Here is a link to one such calendar. Note that the curriculum today is not the same as when this calendar was written. [Link](https://docs.google.com/spreadsheets/d/1YRbXODiDfWPYPejJVW6bSnj8KQhQ50z-UpGpyJpvlxw/edit#gid=1000458167)
