### ISSUE TITLE
Curiculum for 13 year old

### ISSUE THREAD

**Issue by human322** [ossu/computer-science#761]
I am planning to let my 13 year old get exposed to this curriculum. The focus is to orient her with CS and not master. Is there anyone that young who has already taken the path. However here are few concerns:

1. How challenging will it be for an early teenager?

2. What are ways to make it more fun? 

Any suggestions and recommendations is welcome.

**Comment by spamegg1** [comment]
This would be quite challenging for a 13 year old. These are college-level classes. There is a lot of high school math prerequisites that I'm guessing she would not know. I think she would probably struggle a lot even with the Intro CS stuff. There are probably all kinds of other more fun, kid/early teen oriented coding resources online. Those might be more appropriate. Check out code.org or tynker.com (but don't pay them any money).

**Comment by human322** [comment]
> This would be quite challenging for a 13 year old. These are college-level classes. There is a lot of high school math prerequisites that I'm guessing she would not know. I think she would probably struggle a lot even with the Intro CS stuff. There are probably all kinds of other more fun, kid/early teen oriented coding resources online. Those might be more appropriate. Check out code.org or tynker.com (but don't pay them any money).

Yes..I have been exploring all of those and I do see their potential. In fact couple of months ago I started my search online and ultimately landed at OSSU which I found the most useful almost felt like coming across hidden treasure giving me lot of clarity for myself and my 12 year old. The reason to post this is to gain any such insights/tools which I might be missing on. Also the idea is what seems tough today will seem like piece of cake after few years. And anyways even if she takes longer to finish or cut short her curriculum there is nothing to lose.

Let me also take the opportunity to commend you on your contribution regarding  "Finished OSSU, ask me anything #727" it was quiet inspiring.

**Comment by spamegg1** [comment]
Thanks, wish you and your family the best. Wish I knew more youth oriented CS stuff. Two more things that come to mind are some [Raspberry Pi projects](https://www.kidscodecs.com/raspberry-pi-projects/), and the [Scratch programming language](https://scratch.mit.edu/).

**Comment by waciumawanjohi** [comment]
I know of one student that started OSSU before entering high school. He had a positive experience and has commented this summer in [Gitter](https://gitter.im/open-source-society/computer-science).

The recommendation of Scratch is an excellent one. Scratch is the most widely used block based programming language, and is appropriate for beginning students from older elementary to college. (Seriously, Berkley coded an extension to Scratch called Snap that they use to teach an intro course)

This is a book that I used when I was starting to teach Scratch:
https://www.goodreads.com/book/show/18325450-learn-to-program-with-scratch

Another great resource is [Girls Who Code](https://girlswhocode.com/). They organize high school clubs and summer programs. The summer curriculum starts with Scratch and includes python coding, and an intro to web dev and robotics.

You've got the right perspective. At 13, the most important learning outcome is that a student knows programming is a fun and fulfilling pursuit. OSSU assumes that a student already has greater than average dedication to learning CS. If you have the time and ability to serve as a mentor to your child, I would recommend partnering with your child to choose open ended projects and giving them feedback and encouragement as they drive towards solutions.

**Comment by human322** [comment]
> Thanks, wish you and your family the best. Wish I knew more youth oriented CS stuff. Two more things that come to mind are some [Raspberry Pi projects](https://www.kidscodecs.com/raspberry-pi-projects/), and the [Scratch programming language](https://scratch.mit.edu/).

Noted..Thanks!!

**Comment by human322** [comment]
@waciumawanjohi 

That's valuable. I will work on it and kudos to enthus like you to actively prospect OSSU!!

**Comment by waciumawanjohi** [comment]
We're a mutual admiration society, glad to see you nurturing the next generation!

I'll leave this issue open for another week in case there are more suggestions from other contributors.

**Comment by spamegg1** [comment]
@waciumawanjohi You a fellow teacher too huh? Awesome! 

You might be surprised to hear that Blocks are used to explain Higher-Order Functions like `fold`, `reduce` etc. in [Parallel programming](https://www.coursera.org/learn/parprog1). I think we need blocks and visualization a lot more on the higher levels too. It's not "just for kids".

**Comment by Uniminin** [comment]
I started OSSU-CS when I was at 8th grade. And took many others courses while following OSSU-CS. Now I'm at 10th grade. It was quite difficult at the beginning but it gets easier over time. And I really enjoyed the courses I took in the past and still doing :)

**Comment by Barmp** [comment]
As said above, this is pretty heavy for a middle school child to tackle as it goes very deep in the weeds in a number of areas. There are great pedagogical reasons to teach your child to program around this age, and many free or low cost resources available to help in that regard, heck a lot of school districts are initiating STEM style courses so you may have resources available to you via that avenue as well. The first few lessons of Harvard's CS50 are oriented around Scratch and teach the basic concepts. It's been years since I've looked at that course, but it might be worth a visit.

The CS oriented coursework may be something you're better off taking in smaller steps; you didn't mention your own capacity in this area but if this is a shared interest between you that grows as she does much of this content will be suitable for you both in the next few years.

Really glad to see Girls Who Code mentioned here, they're a great organization. A few more resources I can think of off the top of my head that are freely available and/or make things more engaging for a young person:
*Adafruit (great Maker resources and plans, plenty of inspiration; an electronics vendor so things are product oriented)
*Khan Academy (once primarily a math resource, now covers a wide curriculum)
*Lego Mindstorms (similar to Scratch language, build robots. Was used in our schools a lot. Pretty costly to get into)
*FreeCodeCamp (also on Github https://github.com/freeCodeCamp/freeCodeCamp; well regarded in my circles but I haven't delved into it myself. Actually free to use)
*See if there is a local Maker Space around, your mileage may vary but they are often a good resource for finding other people with a similar interest in your community and they often have people with experience and interesting tools available that you wouldn't be able to get your hands on normally.

**Comment by human322** [comment]
@Barmp that's quiet resourceful. To some extent I am aware about the difficulty of the curriculum. Hence I am going to follow the curriculum in a diluted form wherever possible. Thanks for adding few more pointers.
