### ISSUE TITLE
RFC: Stop reporting duration and effort

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#773]
**Problem**:
OSSU contributors spend time transcribing easily found information.
 
**Duration**:
Aug 30, 2020
 
**Background**:
On every course, OSSU contributors write the duration (number of weeks) and effort (number of hours per week) expected by the course.
For the vast majority of courses, this information is simply being transcribed from the front of the course page. In these cases, the information is duplicative and a waste.
In other cases, the duration/effort have not been estimated by the course platform/instructor. In these cases, such an estimate does add information. But it often takes a significant amount of time for OSSU contributors to settle on an estimate. This should only be undertaken if it provides value to students.
Does the inclusion of duration/effort aid students? It may not. The expectation is that students will proceed in linear fashion from first course to last. In this paradigm, what is the value of calculating an individual course’s duration?
 
**Proposal**:
- Remove Duration and Effort from all courses.

**Alternatives**:

1. Estimate duration and effort only for courses such as Missing Semester and Introduction to Computer Networking which do not offer estimates.
2. Keep the curriculum as it is.

**Comment by GrantCAD** [comment]
The timing and effort estimates are valuable if you want to achieve a goal in a set time. In my case, what will I achieve before applying for a master's cs course. Additionally it can provide a reference if you're in track or not.

**Comment by krishnakumarg1984** [comment]
I think that this information need not be repeated. 

 If we absolutely need to keep it, the estimated effort could report lower and upper bounds like `+/-30%` (or add a caveat saying that these are very rough estimates).

**Comment by Exkywor** [comment]
I think it's good to keep the information so that you can get an idea of when you should be completing each course. Discipline is key to finishing this curriculum and having deadlines help. However, a disclaimer could come in handy to fix the issue.

**Comment by krishnakumarg1984** [comment]
You can view it in two ways..... For example, reporting effort such as 16 weeks etc may lead to a sense of "a mountain to climb" and the student losing the will to start the course before they even look at it.

On the other hand, it may also instil a sense of motivation and a better sense of planning to complete a certain course in a time-bound manner.  There is no universal answer since each student is different.

Ultimately, why are we repeating the information about effort and timelines? We don't repeat equally important information such as name of university, name of MOOC provider, name of instructor, next available session etc.

In one sense, it can be argued that while all the other facts I mentioned are constant, effort required is subjective. This is not a rigorous university curriculum with semester add-drop dates, exams, graduation dates and other strict timelines, but quite a few people are doing this syllabus while holding day jobs, children, elderly caring duties etc. 

Why repeat information that is already available in the course's link? After all, doesn't it violate a core CS principle viz. **Don't Repeat Yourself (DRY?)**

**Comment by GrantCAD** [comment]
Summaries highlight important information at a glance to be able to make quick decisions instead of needing to click every single link. Any report you read will include the highlights at the beginning aka abstract.

There are also cases like in CS50 where you are told not to complete the entire course and therefore the amount of time to complete is not accurate.

I am open to the proposal of surveys to create more accurate time to completion.

**Comment by krishnakumarg1984** [comment]
I feel that the maintenance overhead of reporting estimated hours may not always be worth the effort.

Additionally, this information can become outdated. For example, I have taken at least two courses in coursera, where new content have been added over the years and thus the course expanded by another 3 weeks.

Ultimately, there is no right answer and it is all subjective.  If you could argue that "estimated effort" is important, then so is the relative standing of the university or the reputation of the professor. Then the name of the university and professor could also be included in the curriculum? Ultimately, there is no right answer here.

**Comment by attackgnome** [comment]
I would remove the information.

- It's duplicated information.

-  It's one more piece of information that would have to be maintained to keep it up to date. 

- If it's anyone's responsibility to track this information, its the original providers of the course material.

**Comment by waciumawanjohi** [comment]
Comments are split between those advocating keeping the information and those advocating not maintaining it. This is valuable feedback. No change will happen immediately, but it is clear that contributors are aware that this information is a carrying cost. There may come a revision in the future that moves this information to a separate page, or which deletes the information altogether.

**Comment by pcolt** [comment]
From my personal experience I found the Duration and effort information not very comparable between different courses. Sometimes I found it very much underestimated like with Mathematics for CS. 
In general I think it would be a valuable information if it came directly form the same students following the OSSU Curriculum. But at the moment the new link to the chat channel on Discord could be a good substitute, because every student could ask (or find?) such kind of information there.
In the future could be nice to think to a kind of automatic survey that every student could fill at the completion of every course with a link available to everyone with the results. It could be an opportunity to provide and gather much more reliable, comparable and accessible information about each course....

**Comment by StevenKJo** [comment]
- **Redundancy**: Effort and Duration both have time units to provide the same objective of giving an idea of how long will the student work on the course. (Whats next, a column for minutes and then another for seconds? hahah)
- **Space**: The amount of page real state that 2 columns of the same information can be reduced to achieve a similar objective, and the extra space can be used for optional support courses and material or stuff that achieves more impact on students.
- **Convenience**: Even though its convenient to see the information right away, I believe that if they are taking the time to actually study the curriculum they are not lazy to click and see the duration provided on the course website, that will actually provide a better comprehension than two cells. 

I suggest this in my draft of [comment-660886018](https://github.com/ossu/computer-science/issues/751#issuecomment-660886018)

---

## Intro CS
**Knowledge Areas**: `SDF - Software Development Fundamentals`

If you've never written a for-loop, start here. Students who have been introduced to programming should take this course for a flavor of the material to come. If you finish the course wanting more, Computer Science is likely for you!

| KA | **Course** | **Hours**| **Optional Support** |**Prerequisites** |
|---|---|---|---|---|
| `SDF`|  [Python for Everbody](https://www.coursera.org/specializations/python "UMich edx.org") | 58 | [Fundamentals](https://www.coursera.org/specializations/computer-fundamentals "RICEx edx.org") | none
| `SDF` | [Intro to CS and Programming](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-10 "MIT mit.edu") | 135 | | [algebra](https://www.khanacademy.org/math/algebra-home)

## Core CS
### Core Theory
**Knowledge Areas**: `SP - Social Issues and Professional Practice` `DS - Discrete Structures` `SDF - Software Development Fundamentals` `PL - Programming Languages` `AL - Algorithms and Complexity` `CN - Computational Science`

[CS curriculums](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf) use calculus not as a means for domain knowledge, but more as a method for helping develop mathematical maturity and clarity of mathematical thinking to have the basis on which to then build CS-specific mathematics.

| KA | **Course** | **Hrs** | **Optional Support** | **Prerequisites** |
|---|---|---|---|---|
| `SP`|  [Learning How to Learn](https://www.coursera.org/learn/learning-how-to-learn "McMaster coursera.org") | 15 | [Mindshift](https://www.coursera.org/learn/mindshift) | none
| `DS`|  [Calculus 1A](https://www.edx.org/course/calculus-1a-differentiation "MIT edx.org") [1B](https://www.edx.org/course/calculus-1b-integration) [1C](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series) | 256 | [Khan](https://www.khanacademy.org/math/high-school-math/precalculus), [Brilliant](https://brilliant.org/calculus/) | [high school math](https://www.khanacademy.org/math/high-school-math)
| `DS`| [Probability](https://www.edx.org/course/introduction-probability-science-mitx-6-041x-2 "MIT edx.org ") | 288 | [Khan](https://www.khanacademy.org/math/statistics-probability/probability-library), [Brilliant](https://brilliant.org/discrete-mathematics/) | [high school math](https://www.khanacademy.org/math/high-school-math)
| `DS` |[Mathematics for CS](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/index.htm "MIT ocw.mit.edu")| 65 | [Discrete](https://www.coursera.org/specializations/discrete-mathematics), [Logic](https://www.coursera.org/learn/logic-introduction "Stanford coursera.org"), [Effective](https://www.edx.org/course/effective-thinking-through-mathematics-utaustinx-ut-9-01x-0), [Thinking](https://www.coursera.org/learn/mathematical-thinking), [Sets](https://www.youtube.com/playlist?list=PL5KkMZvBpo5AH_5GpxMiryJT6Dkj32H6N) |  [Calculus 1A](https://www.edx.org/course/calculus-1a-differentiation "MIT edx.org") [1B](https://www.edx.org/course/calculus-1b-integration) [1C](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series)
| `SDF`| [How to Code Part 1](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x "UBCx edx.org") [Part 2](https://www.edx.org/course/how-code-complex-data-ubcx-htc2x "UBCx edx.org") | 117 | [Book](https://htdp.org/2003-09-26/), [Basics](https://www.edx.org/course/programming-basics-iitbombayx-cs101-1x), [khan](https://www.khanacademy.org/computing/computer-programming/programming)| none
| `SDF`| [Intro to CS - CS50](https://www.edx.org/course/introduction-computer-science-harvardx-cs50x#! "Harvard edx.org ") | 132 | [I](https://www.edx.org/course/computing-in-python-i-fundamentals-and-procedural-programming-0), [II](https://www.edx.org/course/computing-in-python-ii-control-structures-0), [III](https://www.edx.org/course/computing-in-python-iii-data-structures-0), [IV](https://www.edx.org/course/computing-in-python-iv-objects-algorithms-0) | none
| `SDF` | [CS Missing Semester](https://missing.csail.mit.edu/ " MIT mit.edu") | 24 | [IT Support](https://www.coursera.org/learn/technical-support-fundamentals?specialization=google-it-support#syllabus) | -
| `PL`| [PL Part A](https://www.coursera.org/learn/programming-languages "UW coursera.org") [Part B](https://www.coursera.org/learn/programming-languages-part-b "UW coursera.org") [Part C](https://www.coursera.org/learn/programming-languages-part-c "UW coursera.org")| 66 |  [Java](https://www.coursera.org/specializations/java-programming#courses), [Book 1](http://cs.brown.edu/~sk/Publications/Books/ProgLangs/), [Book 2](https://papl.cs.brown.edu/2018/) | `SDF` , [Instructor's](https://www.coursera.org/lecture/programming-languages/recommended-background-k1yuh)
| `AL` | [Algorithms](https://www.coursera.org/specializations/algorithms "Stanford coursera.org") | 96 | [Khan](https://www.khanacademy.org/computing/computer-science/algorithms), [UCSD](https://www.coursera.org/specializations/data-structures-algorithms), [Algo](https://visualgo.net), [freecodecamp](https://www.freecodecamp.org),<br /> [geeksforgeeks](https://www.geeksforgeeks.org/fundamentals-of-algorithms/), [Princeton 1](https://www.coursera.org/learn/algorithms-part1) [2](https://www.coursera.org/learn/algorithms-part2), [MIT 1](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/index.htm) [2](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-design-and-analysis-of-algorithms-spring-2015/index.htm)|`SDF` `PL` `DS`
| `CN` |  [Theory of Computation](http://aduni.org/courses/theory/index.php?view=cw), [Videos](https://www.youtube.com/watch?v=FeT7iohSsPA&list=PLTke5lHMAdSNmi57H0DOTzClHPK6UwSTN&index=2&t=0s "aduni.org youtube.com")|  80 |[Princeton](https://www.coursera.org/learn/cs-algorithms-theory-machines), [Intro Book](https://www.amazon.com/Introduction-Theory-Computation-Michael-Sipser/dp/113318779X) |`DS` `AL`

**Comment by krishnakumarg1984** [comment]
> Comments are split between those advocating keeping the information and those advocating not maintaining it. This is valuable feedback. No change will happen immediately, but it is clear that contributors are aware that this information is a carrying cost. There may come a revision in the future that moves this information to a separate page, or which deletes the information altogether.

@waciumawanjohi I am trying to understand the "human factors" involved here from a project management viewpoint.

This issue is closed. Out of sight & out of mind. That's what a closed issue means.

There is quite a bit of cognitive load to recall closed issues from 27 months ago whenever a relevant change to the curriculum happens. 

Are the contributors going to dig through all closed issues before making changes to the curriculum? Not just this issue, but maybe there were 7 other issues that were kept for future consideration, since they had a balanced for/against feedback. I think that this is not a scalable approach.

**Comment by krishnakumarg1984** [comment]
@waciumawanjohi Can you please respond to the ways of working of this repo with regard to my previous unresolved comment? How can contributers remember which closed issue to refer to when updating the curriculum?

**Comment by waciumawanjohi** [comment]
Hey @krishnakumarg1984 
You wrote
> I think that this is not a scalable approach.

I actually agree. Practices that can work for us now aren't the same ones that would work if we had far more contributors. While I think that's a potential problem that we should keep in mind, I can't think of an instance when it has hindered work.
