### ISSUE TITLE
"How to code" have two parts, if I just read the textbook directly, will it be enough?

### ISSUE THREAD

**Issue by timeneverdie** [ossu/computer-science#777]
I mean compared with edx course and the textbook, which one is better? 

Will the edx course have more contents than the textbook? Will the textbook cover the whole two parts of the edx course?

**Comment by spamegg1** [comment]
@timeneverdie Don't worry about it, you won't be missing out anything. Follow the curriculum and take the edX courses.

The fear of "I will miss out something important!" is quite common among newcomers, especially since there are so many alternate resources. The way forward is to ignore these worries and follow the curriculum.

**Comment by waciumawanjohi** [comment]
I agree with spamegg that you need not fear missing something from the textbook if you take the online courses.

At the same time, I wouldn't worry about missing something from these two courses if you read the textbook. (That is, if you simply prefer textbooks to lectures)
