### ISSUE TITLE
RFC: Move the Missing Semester Later in the Curriculum

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#778]
**Problem**:
The Missing Semester is a challenging course early in the curriculum.
 
**Duration**:
2020-09-10
 
**Background**:
The Missing Semester is meant to teach students how to use a number of tools of computer science. These include the terminal, git, and vim.

However, numerous students have given feedback that the assignments are quite challenging. Examples can be found in [this issue](https://github.com/ossu/computer-science/issues/715). The course also occurs quite early in the curriculum.

In addition, the courses immediately after this one do not leverage the lessons learned. How to Code is taught entirely within Dr. Racket. Students will most benefit from exposure to command line environments before studying operating systems and networks.

**Proposal**:
Move The Missing Semester immediately before Core Systems.

**Alternatives**:

1. Students could be advised to study different sections of the course at different times in the curriculum.
2. The course could remain in place.

**Comment by spamegg1** [comment]
I support the proposal.

**Comment by ToniGalmes** [comment]
I also support the proposal.

**Comment by Exkywor** [comment]
This sounds like a great solution!

**Comment by cauequeiroz** [comment]
Great! I'm doing this course right now and it really has a lot of content, tools, techniques and concepts. Once I will spend the next few months at programming/math classes, probably I will forgot 70% of the content and I will need to do it all over again.

So, I like the idea of taking this class later in the curriculum.

**Comment by stormrage9100** [comment]
I completed the 4th lesson now and I strongly agree that this course should come later in the curriculum.

**Comment by Chuphay** [comment]
It sounds like cs50 has its own IDE. And I know that Nand2Tetris supplies its own software. Perhaps it'd be better to fit this in after those classes but before operating systems. (I don't know networking, so can't comment on it).

**Comment by krishnakumarg1984** [comment]
I have been using `bash` and `vim` for a really long time. Where I did my PhD, the program administrators  required that everyone in their first year of PhD (irrespective of degree enrolled), do a 2-day software carpentry training course that covered shell, automation and text editing at a command line.  I am not a CS major, but I still picked this up rather quickly, and was using them daily in my research. 

I don't know if it is so hard that it needs to be deliberately moved beyond various CS subjects. I find algorithms, programming etc hard relative to some basic filesystem moves etc at the command line.

**Comment by robbrit** [comment]
I agree that moving it later is a better option, but not because it is challenging. I agree with @cauequeiroz in that if you don't use these tools right away, you will probably forget them. Might as well teach them either immediately before or in parallel with classes that will take advantage of these skills.

**Comment by Exkywor** [comment]
My main concern with moving it later is with things that are easy to understand but require a lot of time to get comfortable with, like Vim. If you leave it too late, the projects you're gonna be working on are going to feel extra hard if you're just learning Vim, while if you begin it early you may have a bit of an easier time since the courses are not on the same level.
I myself haven't reached that far into the program so I can't really say for sure though.

**Comment by dhruvmanila** [comment]
I am in the middle of the course and yes there are a lot of tools introduced but for me, this seems like a good choice to give the students the knowledge about the existence of these tools so that they start using it. I've been using git and terminal right from the beginning of the curriculum and also created a personal repository just to test different topics of git. 

I would say to take this course as an exploration of what's possible and come back to it when you need it.

**Comment by krishnakumarg1984** [comment]
The course is all over the place in the content coverage (and hence, the "missing semester" title, I get it).

I strongly believe that one shouldn't proceed too far into the currciulum without knowing some form of version control. This can be an invaluable tool for incrementally working on homework assignments. (eg. can progressively make small commits towards attaining an optimal solution to algorithm homeworks, without worrying too much about messing up/destroying currently working code).

I think a strong substitute in the early stages are the [lessons from Software Carpentry ](https://software-carpentry.org/lessons/ ), especially git lesson  (and the Unix Shell lesson). 

Software Carpentry is a non-profit organisation founded nearly 10 years ago by a professor at Univ of Washington, and they run regular 2-day FREE workshops all over the world, where these lessons are covered. 

The material itself is licensed CC-BY.

**Comment by StevenKJo** [comment]
Its placed too early in the curriculum by being in Intro CS. It has pretty useful knowledge, but I did it later in the curriculum because I had already started OSSU when you guys suggested it, so it made a better impact on me because of the stage I was in the curriculum than it will do in a noob that has not even done CS50 yet. So to make a real impact I think it should definitely be moved to core, maybe just after CS50 as I suggest in my draft of [comment-660886018](https://github.com/ossu/computer-science/issues/751#issuecomment-660886018)

---

## Core Theory
**Knowledge Areas**: `SDF - Software Development Fundamentals` `PL - Programming Languages` `DS - Discrete Structures` `AL - Algorithms and Complexity` `CN - Computational Science`

| KA | **Course** | **Hrs** | **Optional Support** | **Prerequisites** |
|---|---|---|---|---|
| `SDF`| [How to Code Part 1](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x "edx.org ") [Part 2](https://www.edx.org/course/how-code-complex-data-ubcx-htc2x "UBCx edx.org") | 117 | [Book](https://htdp.org/2003-09-26/), [Basics](https://www.edx.org/course/programming-basics-iitbombayx-cs101-1x), [khan](https://www.khanacademy.org/computing/computer-programming/programming)| none
| `SDF`| [Intro to CS - CS50](https://www.edx.org/course/introduction-computer-science-harvardx-cs50x#! "Harvard edx.org ") | 132 | [I](https://www.edx.org/course/computing-in-python-i-fundamentals-and-procedural-programming-0), [II](https://www.edx.org/course/computing-in-python-ii-control-structures-0), [III](https://www.edx.org/course/computing-in-python-iii-data-structures-0), [IV](https://www.edx.org/course/computing-in-python-iv-objects-algorithms-0) | none
| `SDF` | [CS Missing Semester](https://missing.csail.mit.edu/ " MIT mit.edu") | 24 | [IT Support](https://www.coursera.org/learn/technical-support-fundamentals?specialization=google-it-support#syllabus) | -
| `PL`| [PL Part A](https://www.coursera.org/learn/programming-languages "UW coursera.org") [Part B](https://www.coursera.org/learn/programming-languages-part-b "UW coursera.org") [Part C](https://www.coursera.org/learn/programming-languages-part-c "UW coursera.org")| 66 |  [Java](https://www.coursera.org/specializations/java-programming#courses), [Book 1](http://cs.brown.edu/~sk/Publications/Books/ProgLangs/), [Book 2](https://papl.cs.brown.edu/2018/) | `SDF` , [Instructor's](https://www.coursera.org/lecture/programming-languages/recommended-background-k1yuh)
| `DS` |[Introduction to Logic](https://www.coursera.org/learn/logic-introduction "Stanford coursera.org") | 60 | [Effective](https://www.edx.org/course/effective-thinking-through-mathematics-utaustinx-ut-9-01x-0), [Thinking](https://www.coursera.org/learn/mathematical-thinking) | [Set Theory](https://www.youtube.com/playlist?list=PL5KkMZvBpo5AH_5GpxMiryJT6Dkj32H6N)
| `DS` |[Mathematics for CS](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/index.htm "MIT ocw.mit.edu")| 65 | [Discrete Math](https://www.coursera.org/specializations/discrete-mathematics)|  [Calculus 1A](https://www.edx.org/course/calculus-1a-differentiation "MIT edx.org") [1B](https://www.edx.org/course/calculus-1b-integration) [1C](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series)
| `AL` | [Algorithms](https://www.coursera.org/specializations/algorithms "Stanford coursera.org") | 96 | [Khan](https://www.khanacademy.org/computing/computer-science/algorithms), [UCSD](https://www.coursera.org/specializations/data-structures-algorithms), [Algo](https://visualgo.net), [freecodecamp](https://www.freecodecamp.org),<br /> [geeksforgeeks](https://www.geeksforgeeks.org/fundamentals-of-algorithms/), [Princeton 1](https://www.coursera.org/learn/algorithms-part1) [2](https://www.coursera.org/learn/algorithms-part2), [MIT 1](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/index.htm) [2](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-design-and-analysis-of-algorithms-spring-2015/index.htm)|`SDF` `PL` `DS`
| `CN` |  [Theory of Computation](http://aduni.org/courses/theory/index.php?view=cw), [Videos](https://www.youtube.com/watch?v=FeT7iohSsPA&list=PLTke5lHMAdSNmi57H0DOTzClHPK6UwSTN&index=2&t=0s "aduni.org youtube.com")|  80 |[Princeton](https://www.coursera.org/learn/cs-algorithms-theory-machines), [Intro Book](https://www.amazon.com/Introduction-Theory-Computation-Michael-Sipser/dp/113318779X) |`DS` `AL`

**Comment by Isoaxe** [comment]
I think the proposal makes a lot of sense. No need to burden the students with topics that will not be useful or relevant right away. It would be better to do the courses later as proposed, where the student might get practical application from them soon after completion.

**Comment by krishnakumarg1984** [comment]
In this case (or moving it to a later stage), we need to insert the software carpentry's phenomenal git course, which can help to version control their homeworks (for all courses).

**Comment by waciumawanjohi** [comment]
### Close of the Comment Period

**Findings**:
The majority of contributors agree with the reasoning for moving The Missing Semester.

**Conclusion**
The Missing Semester will be placed before Core Systems.
