### ISSUE TITLE
OSSU Partnership Statement

### ISSUE THREAD

**Issue by mattoy77** [ossu/computer-science#793]
Dear Mr. John Hanson alias "hanjiexi",

This is a response in reference to the post you made several days ago. As you have made some defamatory remarks against our institution which has partnered with the OSSU, we shall answer the charges you have indirectly attacked us with on the advise of our lawyers and solicitors. 

For the reference of the public, this is the comment made by the above mentioned person which we have screen captured in the event that the said statement will be deleted.

https://github.com/ossu/computer-science/issues/784#issuecomment-693727969 

In June of this year and with proper email trail entered as evidence of the foregoing, we contacted the founder and creator of the OSSU programme, Mr. Eric Douglas, to request for his permission and legal consent to establish a partnership with the OSSU. Mr. Douglas, being the said owner and creator of this programme gave his authorisation to help provide opportunity for students who take the courses listed in the OSSU curriculum to be eventually recognised for their own achievements with a degree granted by our institution.

Our Institution, the Asia Caribbean Open Institute, is an educational advocacy initiative of the Caribbean ASEAN Council. It is  a non-traditional online school established in response to one of our objectives of supporting the United Nations Sustainable Development Goal on Education or Goal No. 4 of the 2030 Agenda for Sustainable Development.

As an international non-governmental organisation working with various governments and non-state actors, the Caribbean ASEAN Council is duly registered under the laws of Switzerland with a coordinating representative for the United Nations Office at Geneva. We have representatives in Europe, Southeast Asia, and the Caribbean. The Council Secretariat which also performs the duties of Registrar for the Institute is the Eastern Caribbean-Southeast Asia Chamber which itself, is a non-government organisation registered in England and Wales. Our organisation is recognised by the United Nations Office of the High Representative for the Least Developed Countries, Landlocked Developing Countries and Small Island Developing States. We have registered with the NGO Branch of the United Nations Economic and Social Council and with the Transparency Register of the European Parliament and the EU Commission. We are a signatory to the United Nations Global Compact and an Associate Member of the Conference of NGOs in Consultative Relationship with the United Nations. I can go on about proving the legitimacy of our organisation but that would take much space so in the interest of this statement, I shall move forward and request readers to visit our websites for more information.

The objective of the Asia Caribbean Open Institute is to provide accessible and affordable education to students from developing countries. We primarily serve students in Southeast Asia as well as less developed countries in the Caribbean such as Haiti. The Institute does not directly develop its own courses but instead works with various educational providers that are engaged in Open CourseWare (OCW), Open Educational Resources (OER), and Massive Open Online Courses (MOOC) to be able to provide a platform for our students who cannot afford to enroll in money making colleges and universities. Hence, the partnership with the OSSU.

You mentioned in your post and I quote:

_"As an example of a threat, recently we were contacted by an organization that appears to be a diploma mill and may be committing fraud. On a few days notice, and without permission from the board, this organisation created a website asking students to pay them for a degree in partnership with Open Source Society University."_

Dear sir, if you thoroughly read our website, all the legal information contained therein with due reference and links to all the government agencies are present. Swiss law specifically allows our Institute to issue degrees related to the courses we offer without the need for any sort of accreditation. We can provide you with a list of educational providers in Switzerland to support this fact. On top of this, our Registrar has registered with the United Kingdom Register of Learning Providers to comply with the requirements in the United Kingdom and Commonwealth countries. Our Institute does not issue degrees without actual coursework done by the student and it is very clear to our students that each programme they enroll in will take much more than a swipe of a credit card to finish. We can provide student references upon legal request. Similar to the University of the People, our Institute has no tuition fees and our programmes cost only a few hundred Euros in total from enrollment to graduation! That is much less than the cost of a computer, laptop, tablet or mobile phone that most people have in the North America and Europe. Also, for your information, all of our currently enrolled students are on a 100% scholarship and have not paid a single cent thanks to our supporting partners.  

Our advocacy was developed and implemented with poor people from poor countries in mind! Calling our institution a "diploma mill" and a "fraud" is an insult to myself and every other person in our organisation who have tirelessly worked on establishing it where it is today. Not to mention, our students who rely on open educational resources to have a brighter future. Unfortunately, not everyone in the world is as fortunate as you and the others in this online community.

Furthermore, I wish to reiterate that in the email conversation with Mr. Douglas, there was no mention of any other needed approval as we were granted the explicit consent of the owner and creator of the aforementioned OSSU programme. Mr. Waciuma Wanjohi was also part of this email conversation and he did not inform us either of any such requirement.

In reference to the foregoing facts, it is our belief that whatever personal issues you may have with Mr. Douglas is beyond our original agreement with him. As far as our organisation is concerned, we have fully respected international copyright laws owned by Mr. Douglas as the creator and owner of the OSSU Computer Science programme. Whatever development in the management of this open source community has transpired, only Mr. Douglas has the sole right to cancel the said agreement he has conferred upon our institution as the original accord also lies with him.

We must also vehemently remind you not to slander our institution further or risk legal prosecution to the full extent of the laws of your country and international laws related thereto.

This statement is for the information of the general public and shall be filed with attached evidence by our legal representative to the Cyber Division of the Federal Bureau of Investigation.

Yours faithfully,

**(Amb.) Datu Sadja Matthew Pajares Yngson, DCPS KCR FRSA**

Advisory Board Chair of the Asia Caribbean Open Institute
Representative Councillor of the Caribbean ASEAN Council
Envoy for Diplomatic Affairs of the Eastern Caribbean-Southeast Asia Chamber

**Comment by waciumawanjohi** [comment]
Dear Matt,
I am sorry to hear that you read a comment about a diploma mill and assumed that it was referring to you.

You wrote that I "was also part of this email conversation". You have received exactly one email from me. It ends with this:

> We certainly appreciate the enthusiasm and egalitarian mission of your organization. However, we are sure you understand that we need to conduct thorough due diligence before we can consider a partnership. We cannot attach our organization’s name to your endeavor until we have further details about your organization. While this due diligence is taking place we must ask that you **please remove all reference to OSSU from your organization’s site**.

Your response to that email read, in part “We specifically opted not to have our courses accreditted (sic)”. It’s not clear to the Board why OSSU would advise students to pay money to your institution for courses that are not accredited.

You're welcome to advertise a course in partnership with any individual, including Eric Douglas. But no such partnership will be made with Open Source Society University unless you have the agreement of the Board of OSSU. You do not have that agreement.

Please consider this public notice that **OSSU is not working in partnership or cooperation with you**. Please remove any language that would suggest otherwise from your website. We have emailed you directly; no future communication between OSSU and ASEAN will happen through Github.

Sincerely,
Waciuma Wanjohi
OSSU

**Comment by s7oev** [comment]
I saw the original post about the cooperation between OSSU and this university, and the whole thing felt dodgy. Especially after seeing the university website. Glad to read it isn't happening.

**Comment by AsiaCaribbeanOpenInstitute** [comment]
> I saw the original post about the cooperation between OSSU and this university, and the whole thing felt dodgy. Especially after seeing the university website. Glad to read it isn't happening.

Thank you for your feedback sir. We are not a university and we do not claim to be. We are an Institute under a non-government organisation. It is unfortunate that our website is not up to your standards. We can only afford a part-time web developer who helps us with our online presence. Perhaps you can donate some of your time to help our NGO in creating a better one so it won't feel "dodgy"?

**Comment by s7oev** [comment]
Your first post is titled:

OSSU Bachelor of Science in Computer Science Degree

How can you claim the ability to issue Bachelor of Science degree without being a university?

**Comment by AsiaCaribbeanOpenInstitute** [comment]
> Your first post is titled:
> 
> OSSU Bachelor of Science in Computer Science Degree
> 
> How can you claim the ability to issue Bachelor of Science degree without being a university?

In fact, there are numerous colleges and institutes across the globe that are specifically categorised as non-universities and have the right to issue higher education degrees. As mentioned in my post above and also specifically outlined on our website, we follow and abide Swiss law which allows private institutions to offer higher education degrees. This is not some loop hole unlike in the United States but actually enshrined in the Swiss constitution. Private educational institutions in Switzerland are not regulated by the Swiss government unless they offer degrees that lead to certain regulated professions such as medicine or law. Some examples of private institutes that are not classified as colleges or universities in Switzerland but offer higher education degrees including post-graduate degrees are the Graduate Institute of International and Development Studies which I have personally received a certificate from, and the International Hotel and Tourism Training Institute, the International Institute for Management Development, the International School of Business Management, and the Swiss Institute for Management and Hospitality among many others.

For your reference, here is an official circular from the Directorate of the State Secretariat for Education, Research and Innovation of the Federal Department of Economic Affairs, Education and Research of Switzerland stating this fact. [https://www.sbfi.admin.ch/content/dam/sbfi/en/dokumente/2017/12/titel-privater-institutionen.pdf](url)

Working with governments and the private sector across many regions, our organisation prides itself in being transparent with our intentions which is why the Board of Advisors of our Institute is varied and composed of educators, diplomats and professionals to provide checks and balances in our affairs. None of us get paid to do this voluntary work so if we wanted to defraud people, why would we put our names, photos, addresses and activities online? Moreover, why would we even subject ourselves to communicating officially with the OSSU community when we can simply copy everything here without anyone's knowledge?

When we reached out to the OSSU founder months ago, we were not informed of any kind of Board of Directors and he only introduced Mr. Waciuma Wanjohi as a programme maintainer which is also what is publicly stated on the information of this forum. When we received the email from Mr. Wanjohi and Mr. Hanson the other day, we were unaware that we have been included in their management conflict with Mr. Douglas until it was too late. As far as we were concerned months ago, there was no official documentation written anywhere here in the OSSU forum that publicly states the existence and composition of such a Board so imagine our surprise when we received an email from them making demands from us. Had we known this earlier, we would have approached this entire matter differently.

What is regretful for us is that they questioned and slandered our integrity months after an agreement has been reached with Mr. Douglas. Had we known there were management issues here in OSSU, we would have clearly not launched our programme. We are a legitimate international non-government organisation that admired the concept of the OSSU and wanted to share it with the underprivileged persons in the regions we serve. That is still our primary intention with or without OSSU. Had we known their were political factions and other issues in this online community, we would have not wasted our time. As mentioned, we don't want to be involved in the internal affairs of this community but we have every right to defend ourselves from persons who discredit our organisation which we have worked very hard to build. 

Unlike many persons in this online community, we do not have the luxury to hide behind aliases and pseudonyms. As a diplomat, I have personally met more than my share of government and business leaders from America, Europe, Africa, Asia, and Oceania, as well as personally meeting royalty including Her Royal Highness Princess Anne, The Princess Royal. Being the daughter of Her Majesty Queen Elizabeth II, a Head of State in many countries, my family and I were subjected to an intense scrutiny and background check including a home visit. 

So why would we dare tarnish our global reputation in some online community only to be questioned of our intentions?
