### ISSUE TITLE
Request for Comment: Switch some courses from OCW/edX to OLL

### ISSUE THREAD

**Issue by Alaharon123** [ossu/computer-science#832]
**Background:**

MIT relatively recently started a third platform for their materials called Open Learning Library (OLL). It looks like edX, but it's completely free and always available like ocw. The courses in OSSU that are available in OLL are:

* 18.01 Single Variable Calculus
* 18.06 Linear Algebra
* 6.042J Mathematics for Computer Science

I took a cursory look and here were my findings:

[Single Variable Calculus](https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.1x+2T2019/about): has the unit 0 on limits from edX, but has lots of references to edX and skips homework a, homework b, and the final exam. I did not look at Calculus [1B](https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.2x+3T2019/about) and [1C](https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.3x+1T2020/about) because I am lazy.

[Linear Algebra](https://openlearninglibrary.mit.edu/courses/course-v1:OCW+18.06SC+2T2019/about): makes you click more without providing more value

[Math for CS](https://openlearninglibrary.mit.edu/courses/course-v1:OCW+6.042J+2T2019/about): interleaves the materials so you don't have to keep looking at the resource index and bouncing between different parts of the site

**Proposal:**

* Make the ocw link to Math for CS an alt link with the OLL link as the primary link.
* Make OLL alt links for Single Variable Calculus. Maybe even make OLL the primary since edX does not follow the run regularly rule of OSSU only running once or twice a year?

dunno if this is worthy of a RFC rather than a Pull Request, but hoping to get some eyeballs and opinions on this

**Comment by waciumawanjohi** [comment]
Good find! My spot check is in line with yours, this looks like a better wrapper around high quality material that MIT already offers.

Given that it's largely the same underlying content, and that it looks like MIT is trying increase the ease of use for students, I say let's make this the primary link for Calc and Math for CS.

**Comment by dougc85** [comment]
I'm currently in the middle of MIT's Calculus 1B course on edX.  I posted a bit about my experience on the Discord a week or two ago.  I know you're asking about OLL, but it looks like the video content is the same on OLL as the edX content, as mentioned by Alaharon123, so I'll give my opinions about edX.  

Basically, I haven't found the edX course to be particularly helpful, as far as instruction goes.  I've been doing OCW alongside edX and, for me, OCW has been much, much more helpful in learning the material.  The EdX course copies some problems and some videos from OCW, but it cuts some of the most useful content only to replace it with content that I found to be less useful.  

1. EdX cuts many of the recitation videos, which were among the most helpful bits of the OCW course.  The two (student?) instructors take time to walk the viewer through each step of a problem, and they help to fill in any gaps you may have had after watching just the lectures.  

2. EdX cuts much of the lecture content of OCW and replaces it with their own shorter lectures.  I guess personal preference, but I found the OCW lectures more helpful to a student like me who had not studied calculus before. The edX lectures move quicker and explain less.  Additionally, the OCW lectures are videos of actual classes, so they are occasionally punctuated by students asking for clarifications about things that I myself wished I could ask about.

3.  OCW has a massive problem bank with answers to all of the hundreds of problems offered there.  OCW assigns selective problems for you to work on, but if you need more practice, the extra problems are there for you. No such extra practice exists in the edX class.

4. OCW provides free exams with solutions; edX's exams are behind a paywall

-----
What edX does add to the learning experience is at the loss of what it cuts from OCW.  The videos they add are definitely provided to have fun and heighten student engagement (Professor Jerison gets pulled over and talks math with a cop, two of the instructors pretend they're math operations), but they are presented alongside a lack of clarity regarding the actual mathematics. The original classroom videos presented by OCW are more 'boring' but also clearer and more thorough.

Finally, the interactivity of the edX course, an advantage it has over OCW, often led me to be more discouraged about math, rather than feeling like I understood the topic better.  There are occasionally 4 or 5 part problems for which I could not even do the first part and failed to understand the problem even after staring at the provided answer for an hour. Yes, this speaks to my inability to do some more advanced problems, but I'm taking the course to learn how to think better and learn such things, and I'm just left feeling stupid and frustrated.  For some context, I am able to arrive at the correct answer for a good 90% of the OCW problems I've worked through, so it's not as though I can't do calculus at all.  In edX's course 1A, there were strings of comments about how difficult a particular unit was, and they were being posted by commenters who clearly already knew calculus (and much more) quite well.  If even these commenters were finding trouble with a whole unit's worth of problems, I was left wondering who the course is designed for?  It seems not to have been designed for someone learning the material for the first time.

----------
Anyway, that's been my experience with these courses.  As I posted in the Discord, I'm curious what experiences other learners are having. My own approach I've landed on: I learn the material from the instruction, problem sets, and tests provided by OCW, and then I look to edX for some harder problems that I may or may not be able to solve.

I'd finally like to say that, regarding the recommendation here to switch to OLL, yes it's true that OLL won't have limitations as to when you can and can't sign up, but that will be at the expense of the instructor-moderated comments section in edX, which I have found useful.  In addition to that OLL will have all the problems, as I see them, that edX has.  

My own recommendation, as someone who is not a mathematician or a computer scientist (yet!), would be to recommend to learners the OCW course.

**Comment by dougc85** [comment]
An update on my last post:  

Here are some posts from the current cohort of edX's Calculus 1B (found in the forums attached to Unit 3, Problem set 3A-9:

I'm quoting them without their screen names here.  Not sure what the right move is.  I figured privacy is better than citing in this case.  I can come back and attribute as necessary.

"Original MITOCW lectures have saved me. Edx materials are well constructed, but they are like patchwork, and I lost coherency. Edx way must be good for learners having knowledge, they can get information efficiently, but for me, it did not work. Then I found original lectures, and wow! Original lectures are theoretical and consistent, telling me where I am. Important thing is, original lectures have contexts! Contexts are very important for me to construct things. Only essence like edx is not enough."

"I'm doing fine at the regular class exercises, but when it comes to the Problem Sets, I've been consistently whacked. I think I read somewhere that people usually study from 5 to 10 hours a week for MITx Calculus programs, but for this last Problem Set I've been doing at least 3 hours a day. I almost gave up the course while doing this Problem Set 3A!"

"Try watching the lectures only in the OpenCourseware series, then memorize the basic concepts so they can be recalled immediately. At the end of the day I listen to these lectures only, they are more concise and accessible in OpenCourseware."

"I agree with watching the OCW videos that are very sequential."

"the gap between the exercises (which are already harder than what you would see in a typical calculus course) and the problem sets is so large as to be demoralizing even for a student with good math skills and a strong work ethic like myself. Maybe if I were at university taking physics and other technical courses in conjunction with this it would be a different story. I don't know."

Now, admittedly, I'm picking and choosing the comments that support my argument above, but I find it interesting that even students who had *already* taken calculus courses were saying that the problem sets here were beyond them.  There's nothing wrong with problems being difficult, or even too difficult; I just wonder what the purpose of these classes are in the OSSU curriculum.  Does OSSU require taking calculus so that learners learn calculus?  Then I don't think edX is the right class.  Does OSSU require calculus as a bank of mental puzzles to be worked through? Then maybe edX is a good fit.

**Comment by waciumawanjohi** [comment]
@dougc85 Your proposal is different from the one highlighted above AND your proposal is well supported by evidence. Can you create a new RFC that is laser focused on switching OSSU from using MIT's edx course to using MIT OCW?

At the end of your most recent post you asked about OSSU's reason for including calculus in the curriculum. This comment in an earlier issue gives a good accounting for how the math section came to its current form:
https://github.com/ossu/computer-science/issues/768

**Comment by Alaharon123** [comment]
I'd been pushing off making the pull request for this and closing the issue. Thanks Waciuma for the comment to Doug and great job on that RFC Doug.

**Conclusion**: #839 switches Math for Computer Science to OLL and keeps Linear Algebra with OCW. dougc85 has made a separate RFC on Calculus, #838, to potentially switch that to OCW rather than OLL or edX.

Now closing this RFC, thanks everyone

**Comment by timeneverdie** [comment]
Very nice!

It lets OCW has better UI and interactive. It is an update of OCW.

**Comment by timeneverdie** [comment]
@dougc85

I agree what you said. 

In the case of 6.00.1:

EDX version cuts in pieces and saves your time, but it lacks some good recitation videos and exercise explanations.

That means it seems like edx saves your time, but in fact you will spend much more time thinking about how to solve the problems because of lack something. And the experience will be gapped.

But anyway, edx keeps the core knowledges, I don't think it is a bad idea to go through it. But now I prefer to use OCW. It's full and the same as what students in MIT took.

That's why I really like CS50 because what we did is the same as Harvard students did.

**Comment by dougc85** [comment]
@timeneverdie 

Check out this request for comment I made regarding EdX and OCW calculus.  It's still open for discussion.

https://github.com/ossu/computer-science/issues/838

Thanks for chiming in!
