### ISSUE TITLE
Request for Comment: Remove CS50 from Core Systems

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#833]
**Problem:**
CS50 is a time consuming course that does not match the learning goals of Core Systems.

**Duration:**
Jan 1, 2020

**Background:**
CS50 is currently in the curriculum "because it is one of the few chances the student has to play with manual memory management in a (relatively) low-level language. By learning C, students will also have a much easier time getting through the following course, Nand2Tetris." [FAQ](https://github.com/ossu/computer-science/blob/master/FAQ.md#why-do-you-recommend-skipping-the-second-half-of-cs50)

However, C pointers and memory management (malloc, etc) are elective topics in the Programming Languages knowledge area in our curriculum guidelines. [CS2013](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=165)

The authors of Nand2Tetris do not list C or understanding of manual memory as a prerequisite. "The course and the book are completely self-contained, requiring only programming (in any language) as a pre-requisite." [Nand2Tetris About Page](https://www.nand2tetris.org/copy-of-cool-stuff)

Meanwhile, CS50 is one of the most time consuming courses in the curriculum, with an upper bound estimate of 240 hours for completion. [Timeline Spreadsheet](https://docs.google.com/spreadsheets/d/1bkUU90y4rKYQHwY5AR2iX6iiPTrPEsYs75GkCAkrgm4/edit#gid=0) While OSSU encourages students to stop the course after the section on C, in practice many students continue in the course. If a student is devoting ~20 hours per week to study, removing CS50 from the curriculum will move up the student's completion date by 1 to 3 months. Given that the overall time commitment is ~24 months, this means removing the CS 50 recommendation can reduce a student's time to completion by about 10%.

**Proposal:**
Remove CS50 from Core Systems.

**Alternatives:**
Replace CS50 with a course more targeted to learning C pointers and memory management:
- I have long hoped to work with the author of [Aalto University's course on C](https://moocfi.github.io/courses/2016/aalto-c/en/) to get the autograder back online.
- Alternatively, we could recommend [Learn-c.org's](https://www.learn-c.org/en/Welcome) Advanced track
- Or [LearnCpp.com's](https://www.learncpp.com/) Chapter P.

**Note:**
This RFC is not a forum for discussing CS50's strengths as an intro to programming course. That is not the role it serves in the OSSU curriculum. Arguments for its retention should focus on whether it appropriately fills its roll as a mid-curriculum course.

**Comment by Exkywor** [comment]
If it's not really needed for the following course, and a suitable alternative for learning pointers can be found I'd say go for it.

**Comment by waciumawanjohi** [comment]
Are you advocating the Alternative (replacement instead of removal)?

**Comment by I-GiM** [comment]
I say leave it be

**Comment by mehtaRohit** [comment]
There is no problem with the CS50 problem sets, right? I say they are good practice.

**Comment by saerosV** [comment]
If there's a sounder choice, I'd say replace it. CS50 could be an alternative or just optional.

**Comment by rdansie** [comment]
As someone who found OSSU after completing week 3 of CS50 as a beginner, I can say that I don't really know too much about pointers or memory management. There is talk of big O notation in week 3 but we aren't asked to focus on it particularly in the problem sets.  So that would suggest it serves more as an intro to programming from week 0 to week 3 and only weeks 4 and 5 are focused on really solidifying manual memory management (although I have not started those weeks). 

I do think it would be a shame to not use CS50 in some capacity as I think the lecturer is great at hooking people into computer science, it should at least be listed on the site as an optional resource.

**Comment by mehtaRohit** [comment]
> I do think it would be a shame to not use CS50 in some capacity as I think the lecturer is great at hooking people into computer science, it should at least be listed on the site as an optional resource.

I totally agree with @rdansie

**Comment by Alaharon123** [comment]
>I do think it would be a shame to not use CS50 in some capacity as I think the lecturer is great at hooking people into computer science, it should at least be listed on the site as an optional resource.

Dw it'd still be in extras/courses. As stated in the op, this rfc is not about its value as an intro course, we don't use it as one anyway

**Comment by pcolt** [comment]
Concepts of **memory management** are already present in Nand to Tetris part II and in Operating Systems Three Easy Pieces. 
After reading the curriculum guidelines, probably the problem here is that such argument is not covered in any of our courses in Core Programming [[CS2013, pag.164](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=164)].

In particular OSTEP already gives you plenty of opportunities to play with pointers and malloc, in fact one of the learning outcomes of the course is to improve skills of the student in the C language [[see this lesson at minute 7:30](https://youtu.be/5H5esXbVkC8?t=450)]. But in the OSTEP book's page is written that **"Of course, we assume some background in The C Programming Language"** pointing to the book _C Programming Language, by Brian W. Kernighan_. So I would at least put some explicit information about such requirement in the OSSU curriculum. 
Furthermore I found most of the work done around assignments in Introduction to Computer Networks **written in C**, and only some others in Python. So I would consider to shift position order in the curriculum of OSTEP with Intro to CN, so that students already have strong skills in C AND Python.

About the time effort I agree that we should reduce the overall time needed to complete the curriuclum, but we should be aware that there are many courses listed that are declared for fewer hours then they are in reality.

Because of the great quality of CS50 in particular for newcomers in the field of self-taught education, I would propose to move it into **Intro CS** as a more comprehensive alternative to both courses Python fro everybody and Intro to CS and programming with Python, considering that the goal of Intro CS is: "Students [...] should take this course for a flavor of the material to come. If you finish the course wanting more, Computer Science is likely for you".

**Proposals:**
- Move _CS50_ to Intro CS as an alternative to _Py4e_ and _Intro to CS and Programming with Python_
- Add link to a C language resource in the prerequisites of _OSTEP_
- Shift _OSTEP_ with _Intro to CN_
- Consider changes in the Core Programming section to include memory management

**Comment by Exkywor** [comment]
I'm advocating for replacement. I like pcolt's proposals, I think having CS50 as an alternative in Intro rather than a required course could be a good middle ground to keep CS50, but not have it be mandatory

**Comment by lorenzolewis** [comment]
I just completed CS50 last week and agree that as an intro it would be valuable. I didn't learn much aside from pointers (which has been discussed) given that I have a background in programming, but I feel it would fit very well in as an intro course.

**Comment by agilvarry** [comment]
Could something like the mentored C track on [exercism.io](url) be good fit? I haven't dug into it at all but found the Python and JavaScript tracks helpful in learning those languages to the point I could use them for my own purposes.

**Comment by tommcginty** [comment]
I'm new here, but has anyone looked into these courses from Dartmouth on EdX?

https://www.edx.org/professional-certificate/dartmouth-imtx-c-programming-with-linux
Ignoring the certificate, 
there are individual modules for memory management and pointers in C.

**Comment by waciumawanjohi** [comment]
### Close of the Comment Period

**Findings**:
There is general agreement that CS50 does not serve the purpose of teaching manual memory management.
There is interest in CS50 as an introductory course.
There were a number of suggestions:
- Move CS50 to Intro CS as an alternative to Py4e and Intro to CS and Programming with Python
- Add link to a C language resource in the prerequisites of OSTEP
- Shift OSTEP with Intro to CN
- Consider changes in the Core Programming section to include memory management

**Response**:
- Regarding having an alternative intro course, OSSU has previously tried [offering two alternate introductory courses](https://github.com/ossu/computer-science/issues/589). Ultimately we decided that it wasn't serving students well, and [we returned to recommending one intro sequence](https://github.com/ossu/computer-science/issues/763).
- That said, the primary issue with CS50 has been that it was too steep of a learning curve to be the first course in OSSU. But with Py4E as the first course, perhaps CS50 could replace intro to computer science. That would be a complicated change, requiring looking at the parts of our curricular guidelines are covered by _Introduction to Computer Science and Programming Using Python_ and which are covered by CS50. If it led to missed coverage, that RFC would need to propose ways to maintain coverage. It's not an RFC that I will write, but if someone wanted to write it up, I would be interested in reading it.
- The reasoning to swap the order of OSTEP and Intro to Networking is well put.
- Adding a link to C language resources for OSTEP makes sense.
- Because manual memory management is not a Core topic in our curricular guidelines it doesn't belong in core programming. It could be added to Advanced Programming. I won't make that addition with this issue as Advanced Programming has become a collection of both programming languages courses and software engineering courses. I believe those should be broken apart before adding more courses.
- I will note that a long time critique of OSSU has been that it has too many courses. Removing this single course shortens the expected study hours for OSSU completion by 10%. That's a great improvement!

**Conclusion**
- CS50 will be removed from Core Systems. It will be added to Extras/Courses.
- OSTEP and Intro to Computer Networking will switch places.
