### ISSUE TITLE
RFC: Make Calculus required, move other elective math to Advanced

### ISSUE THREAD

**Issue by waciumawanjohi** [ossu/computer-science#841]
**Problem:**
Currently Math for CS is a required course. It has a pre-req of Calculus. Calculus is listed as an elective course, but this dependency means that it is actually required.

**Duration:**
Jan 23, 20201

**Background:**
For an excellent writeup of how the Math curriculum arrived at its current state, I direct readers to here:
https://github.com/ossu/computer-science/issues/768#issuecomment-672637354

In short, our curricular guidelines do not require calculus, but do require a college level math course that enables students to build mathematical maturity. As such calculus is offered as one of 4 math options. Our curricular guidelines _do_ require discrete math, which we meet with MIT's Math for CS. But MIT's Math for CS lists calculus as a prerequisite.

This tension has been pointed out before. There have since been users on Github and in Discord that ask whether calculus is actually elective. Also when the math requirements were reduced, there were [calls to make Calculus required](https://github.com/ossu/computer-science/issues/637). This ambiguity needlessly confuses learners.

**Proposal:**
List Calculus as required and move Math Electives to Advanced.

**Alternatives:**
* Replace Math for CS with a discrete math course that does not have calculus as a prerequisite.

**Comment by waciumawanjohi** [comment]
Machine Learning is in Core Applications and lists Linear Algebra as a pre-requisite. How will moving Linear Algebra affect this core class?

I will quote from @spamegg:

> The approach taken by Andrew Ng in that course is to minimize students' need for math background knowledge. He explicitly says, many times, out loud, "don't worry if you haven't taken Multivariable Calculus or Linear Algebra", etc.

> The partial derivatives taken for optimizing Cost Functions are extremely simple. Definitely no need for Multivariable Calculus. And he explains everything else in the formulas, and provides them for implementation. All you need to do is convert it to code.

> The Linear Algebra required here is mostly matrix multiplication, understanding how rows and columns work, how to match the dimensions of the matrices correctly, and how taking transposes will swap row size and column size. THAT'S IT! Matlab/Octave has stuff that can help you automatically "vectorize" your formulas and optimize them. Ng teaches these.

> He does not get into the deep math of PCA, which involves finding a basis of eigenvectors for a vector space (a theorem from Linear Algebra guarantees the existence of such a basis under certain conditions), and doing a "change of basis" for your matrix. Wisely so, I don't think data scientists need that much. This theorem is somewhat deep and I learned how to prove it as a pure math major.

Notably, "matrix multiplication, understanding how rows and columns work, how to match the dimensions of the matrices correctly, and how taking transposes will swap row size and column size" are high school math expectations. This can be seen in the US Common Core high school math standards. [High School: Number and Quantity » Vector & Matrix Quantities](http://www.corestandards.org/Math/Content/HSN/VM/)

This suggests that MIT's Linear Algebra can be moved to Elective Math without affecting this course.

**Comment by waciumawanjohi** [comment]
Computer Graphics is in Core Applications and lists Linear Algebra as a pre-requisite. How will moving Linear Algebra affect this core class?

Again, I quote from @spamegg:

> The math required here is: matrix/matrix multiplication, matrix/vector multiplication, normalizing vectors, taking cross-products of two vectors to obtain a third one in order to create an orthogonal set of vectors in 3D, and normalizing those to obtain an "orthonormal basis" as we say in linear algebra (although this is somewhat of an intersection of LA and Vector Calculus), a solid understanding of what matrices do on the 2D plane and in 3D space and some ability to visualize it (you can't solve the first Transformations assignment without this). The course provides some third party visualization tools but they are very outdated and difficult to make work.

This does require college level Linear Algebra. Moving Linear Algebra will affect this course.

I argue that this is reason to reevaluate our choices for a Computer Graphics course. [Our curricular guidelines expect only an introduction to graphics in core classes](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf#page=85). The topics expected to be covered are:

_[Core-Tier1]_
* Media applications including user interfaces, audio and video editing, game engines, cad, visualization,
virtual reality
* Digitization of analog data, resolution, and the limits of human perception, e.g., pixels for visual display,
dots for laser printers, and samples for audio (HCI/Foundations)
* Use of standard APIs for the construction of UIs and display of standard media formats (see HCI/GUI
construction)
* Standard media formats, including lossless and lossy formats

_[Core-Tier2]_
* Additive and subtractive color models (CMYK and RGB) and why these provide a range of colors
* Tradeoffs between storing data and re-computing data as embodied by vector and raster representations of
images
* Animation as a sequence of still images

However, our [Computer Graphics course](https://www.edx.org/course/computer-graphics-2) objectives go far beyond these:
* Understand the concepts of 3D graphics
* Write and develop programs that create images of a 3D scene with lighting
* Learn the basics of graphics programming with OpenGL and GLSL

In addition, the computer graphics course includes a final assignment so difficult that the University's own follow-on MOOC specifies "You do not need to have done the final raytracer assignment".

Based on this, contributors should expect an RFC from me to move Computer Graphics into Advanced.

**Comment by spamegg1** [comment]
@waciumawanjohi  Oof! I feel *super* responsible now... Hope people don't get mad at me in the future.
The overall direction is good. Math for CS remains required of course, just in case people get confused about that.

Ditto on your first comment about LA and ML. But I have a feeling that people will take ML and complain...
CG could probably go into Advanced Systems? OpenGL is a pretty complicated system.

I should add that vectors and matrices in *ONLY* 2 or 3 dimensions is not considered *real* Linear Algebra.
Not aimed at solving systems of equations, but rather geometry.
(It's *real* LA when it's in higher dimensions and focused on systems of equations, like in the ML course.)
That's rather ***"basics of geometry in 2D and 3D space"*** for lack of a better title. 
It's mostly about vectors (high school material). Matrices are mostly used for convenience/shorthand. 
For example the cross product formula for two 3D vectors becomes extremely easy to remember with a determinant!
```
| i  j  k|
|x1 y1 z1|
|x2 y2 z2|
```
I taught this to many students who never saw matrices before.

This material is taught *somewhere* along the Calculus sequence before proper Multivariable Calculus.
It's not *really* MVC either... but it is used all over MVC as a basic building block.
It's a topic that doesn't fit anywhere, and is usually taught by squeezing it *somewhere* in a syllabus.
It should be learned in high school but many high schools don't teach it unfortunately, or students forget it.
It is often *tacked on* at the end of an Infinite Sequences/Series course as a refresher: 
"this is irrelevant to this course, but you'll need this in the next course!"
I taught it that way for years.

That's why I had difficulty describing it ("intersection of LA and Vector Calculus"), hope this clarifies things a bit.
Best description for CG prereq would be:
***"Solid understanding of Geometry in 2D and 3D space, mastery of computations with 2D/3D vectors and matrices"***
Now you can understand why MVC and LA were such overkill prerequisites and I opposed them.

**Comment by bradleygrant** [comment]
I know we tend to quote curricular guidelines, but they tend to be much more permissive than reality. I feel that this is one manifestation of such a disconnect. While the curriculum guidelines allow a school to build a CS degree that's light on math, actual practice suggests otherwise.

I've looked at CS degree requirements at several state universities and private colleges, and I've noticed a tendency to require Discrete Math AND Calculus 1 and 2 AND Linear Algebra, as well as a choice of additional math credit. It's common to not specifically require multivariate calculus, differential equations, probability, or mathematical statistics, though these are frequently available as electives to fulfill the additional requirement.

For OSSU, I firmly agree that Single-Variable Calculus (A-B-C or 1-2) should be required, and that Math for CS should remain required.

I further believe we should either specifically require linear algebra, or specifically require one additional elective math credit. This would truly drive parity with most of the actual CS degree programs I see.

**Comment by bradleygrant** [comment]
It may be worthwhile to conduct a meta-analysis of the US News Top 100 CS degree programs, to ensure that our requirements are on parity with many/most of these schools - and to provide documentation/reality check of the same.

**Comment by Alaharon123** [comment]
I believe MIT covers what @spamegg1 is talking about in 18.02 Multivariable Calculus Unit 1 Parts A and B. 


The disconnect between CS2013 and reality is likely because ABET requires 15 credits of math in a cs degree. To get away with just Single Variable Calculus and Math for CS, Calculus 1 and 2 need to be 5 credits each as does Math for CS. They're usually 3-4 credit courses though so there needs to be another 1-2 math courses. ABET also requires 6 credits of lab science too so you'll often see a two course sequence in physics or chemistry. I like the thinking of CS2013 of not worrying about either of those, leaving them to the gened side of things, but I'm not advanced enough to know a lot about the intersection between math and cs.

It's worth noting that US News only ranks graduate level cs programs, not undergraduate. The only undergraduate cs ranking that I know of is TimesHigherEducation, which has the advantage of being international

**Comment by waciumawanjohi** [comment]
> It may be worthwhile to conduct a meta-analysis of the US News Top 100 CS degree programs

A significant reason for adopting the curricular standards is to free OSSU from doing this work. It's not a trivial effort. As far as I know, the only time an OSSU contributor has undertaken such an effort was [2 years ago when I looked into trends for languages used in intro programming courses](https://github.com/ossu/computer-science/issues/440#issuecomment-397150554). My stunning conclusion was that the evidence on the ground matched what was reported by in the CS2013.

Quite simply, I don't think OSSU has the capacity to duplicate or improve on the investigations undertaken by the ACM and IEEE. And it's not clear that we would derive significant value even if we could. Having adopted the standards, we still have non-zero work to do in order to match them (see this issue). And there are lots of other efforts that OSSU can put energy into once we're confident that we fulfill the standards. (For example: mentorship)

**Comment by wuphysics87** [comment]
2 cents from a theoretical physicist (glorified mathematician with a cooler origin story): IMO calculus past basic integration/differentiation to understand the conceptual underpinnings is not as important to Computer Scientists as Linear Algebra.  And even more important than either Linear Algebra or Calculus.  **Discrete Mathematics** and **Finite Element Analysis**

**Comment by RTFerraz** [comment]
I think this curriculum is well suited https://www.smcm.edu/mathcs/academic-offerings/what-you-learn-cs/requirements/#option1.
It's not a good idea to avoid calculus. Things get complicated later without it.

**Comment by wuphysics87** [comment]
It's good they replace Calc 3 with Discrete Mathematics.   (Relative to what I learned and what I was exposed to teaching engineering students.) And I otherwise agree depending on the content of the courses.  

Two semesters of Calculus can get into a lot of integration techniques which are cool on their own, but you'd never use again unless you do pen and paper calculations.  

If they spend two semesters really hammering home the conceptual underpinnings of Calculus and get into applications that would be the most ideal.

**Comment by waciumawanjohi** [comment]
The comment period for this RFC has passed.

Findings:
There is general agreement that calculus should be required. There continue to be calls for the same in the Discord (see the conversation [here](https://discord.com/channels/744385009028431943/744971809056751687/864421713390338060) for example).
There are calls to make linear algebra required as well. I'm going to ask that proponents open a separate RFC for that proposal. (I'll certainly have comments, as previewed above!)

Conclusion:
Calculus will move from math electives to math core. Other electives will move to math advanced.
