### ISSUE TITLE
Restore CS50 as CORE CS

### ISSUE THREAD

**Issue by Elpuma** [ossu/computer-science#852]
As someone who tried many times to self-teach CS, CS50 does a great job motivating and opening the scope of a Computer Science path, also, it has one of the biggest communities one could ever wish for accountability and support/help. 

The multiple areas of practice taught in CS50 also guide in a friendly way a newcomer to see if they really want Computer Science as a carreer and with increasing numbers of "not succesful" Engineers/Programmers a tremendous amount of people are riding the wave of "programming" thinking they will be succesful, as a matter of fact, there is a current spike in people complaining all over the internet that CS stinks, Youtube channels, Quora posts, StackOverflow and countless blogs all over the internet, doing harm against a beautiful knowledge area. 

Many people with 'programming background' arguably form an opinion based on depth or difficulty of CS50's intensive program, but I might be biased saying this, since my 8 year old daughter is about to finish OSSU and she constantly tell her friends that CS50 was the reason she loved computers "and how to dominate them" to do whatever she wanted, But the current roadmap is a bit depressing by removing one of the arguably "most fun courses" ever created.

OSSU since its conception was designed to provide a structured path of knowledge, but the recent change, in my educated opinion, does more harm than good by removing  the "what you will be able to do / the sky is the limit" kind of thinking that is common in Computer Science. Almost All* serious curricular courses from top Universities in the world, try to structure their study plans and/or topics in a "motivating way" to avoid desertion/incompletion and keep students "hooked" on their studies. By removing CS50 We are most likely contributing to increase the already high levels of incompletion on OSSU which We don't want.

Based on the aforementioned, I'm againt the decision of making CS50 an "Extra course" and removing it from CORE CS. Based on the freely available statistical data about CS Study Programs, OSSU is doing an strategic failure by doing such change. What would be the goal of OSSU if people doesn't ever complete it?

So my Request is: Restore CS50 to CORE CS

Note: I understand the point of the people who suggested the change in the first place, but We need to analyze all these decisions with a "cost/benefit" kind of thinking, to see if such change that satisfies a small sample, will benefit or harm the OSSU efforts.

**Comment by mehtaRohit** [comment]
I share the feelings of your daughter. I myself have found cs50 fun and engaging. The instructor is awesome (David J Malan).
I hope🤞 CS50 is restored as Core CS

**Comment by waciumawanjohi** [comment]
_You have an 8 year old daughter that's finishing OSSU? That's incredible. I'd love to talk with you both!_

I'll quote from our [guidelines on making substantive changes to the curriculum](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md):
> OSSU’s curricular guidelines are [here](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md). Successful critiques of the curriculum will point out ways that OSSU is failing to uphold these guidelines.

You mentioned "freely available statistical data about CS Study Programs". OSSU _should_ use such information. That's why we adopted the 500 page report by the Joint Task Force on Computing Curricula from the Association for Computing Machinery (ACM) and the IEEE Computer Society as our curricular guidelines. That's why substantive changes should reference our guidelines.

Originally you titled this issue, "Put CS50 as Intro CS". This matches many of your assertions about the benefits of CS50:

- an explicit goal of intro courses is to give students a feel for the breadth of the domain
- another goal is to excite learners.

But Core CS is the the midpoint of the curriculum. At this point in the curriculum students should not need to take another introduction to computer science course. CS50 doesn't belong in Core CS.

[The RFC that removed CS50 from Core CS](https://github.com/ossu/computer-science/issues/833) welcomed a future RFC for replacing _Introduction to Computer Science and Programming using Python_ with CS50. To quote, "That would be a complicated change, requiring looking at the parts of our curricular guidelines are covered by _Introduction to Computer Science and Programming Using Python_ and which are covered by CS50. If it led to missed coverage, that RFC would need to propose ways to maintain coverage." That's a lot of work. But it's better that contributors put in that work, rather than saying "take both intro courses" and directing tens of thousands of OSSU learners to take hundreds of hours of duplicate curriculum.

Your concerns about retention are very appropriate. One issue that OSSU has had with retention in the past has been students in our forums who found CS50 to be too steep of a learning curve, were demoralized and considering dropping. My hypothesis is that placing OSSU after Py4E would mitigate such outcomes, but it's certainly something we would need to be ready to address if that pattern of student complaints re-emerged.

It's great to see passion around OSSU, as well as learners interested in putting in the work to become contributors!

**Comment by gshaikov** [comment]
Sadly I am late to the discussion as I took CS50 in Oct-Nov 2020 when it was still in Core Systems and noticed the change only now.

Having basic experience with C is paramount for CS education, especially for those who want to make career in the industry. In the same time, it is best learnt after the Core Programming and particularly Functional Programming (just as they do it in Oxbridge).

Its placement in Core Systems was a necessary compromise - after all, it is a systems language. It is also a prerequisite in OS course in the same section.

I would strongly advocate to keep it as optional in Core Systems, next to OS course.

Thanks.

**Comment by waciumawanjohi** [comment]
It will be very helpful for all participants if assertions are supported by evidence.

"Having basic experience with C is paramount for CS education"
This assertion is contradicted up by our curricular guidelines. The ACM and the IEEE do not believe that learning to program in C is of paramount importance. This is why the only reference to C in the CS2013 is in a discussion of how university introductory courses are moving away from C.

"CS50 [teaches C] better than the alternatives"
CS50 is long (again, 10% of the entire OSSU curriculum). 50% of the material is not C. And students who took CS50 reported, "I don't really know too much about pointers or memory management". The RFC that moved CS50 to extras also added a note that "familiarity with C is useful" as a prereq to OSTEP, as well as a link to Hackr.io's page on C. Hackr.io is a community driven list of resources for learning different languages. There are hundreds of votes for resources to learn C, including courses from Dartmouth and from Duke. CS50 is not even in the list.

(CS50 _is_ listed in Hackr.io's list of resources to learn "Intro to Programming".)

I point out again, for those who feel passionately about including CS50 in the curriculum, there is some work to do.
- It should replace some of the current intro work. _Why?_ CS50 is a long intro course and OSSU currently has 2 intro courses.
- It should not be the first course in the curriculum. _Why?_ CS50 used to be the first course in the curriculum and OSSU had students who dropped the curriculum because they found the learning curve too steep.
- In replacing a course, any necessary coverage of our curricular guidelines that is dropped should be addressed.

**Comment by epikkoder** [comment]
>since my 8 year old daughter is about to finish OSSU

@Elpuma Wow, really? The entire curriculum? For an 8-year-old? She must be a prodigy!

**Comment by saerosV** [comment]
I don't see any reasons to restore CS50. The rest of the curriculum already covers much of what's taught in the course, and IMO, does it better. As previously discussed, there are better alternatives for teaching C (and Manual Memory Management, an _elective_ topic in OSSU's curricular guidelines) to students, without spending a fraction of the time CS50 takes.

**Comment by bradleygrant** [comment]
Perhaps the biggest blow to OSSU from removing CS50 is **losing CS50's ecosystem.** I don't think OSSU fully recognizes and appreciates what CS50 provides, for free from an endowed budget, to the open source CS self-study community -- interest, engagement, resources, and (perhaps most importantly) members.

Lots of people take CS50. Lots of people *love* CS50 -- and for good reason; it's an extraordinarily well-developed course with an extraordinarily-engaging professor, extraordinarily well-supported TAs, extraordinarily ambitious coverage (for an intro course), and extraordinarily mind-bending problem sets. Plus it's completely free and available all over the world.

People who take CS50, who love it, excel at it, and want more -- these are exactly the type of students which OSSU should be actively recruiting. Furthermore, they're likely to share many of OSSU's core values, and they often find their way to OSSU themselves. (And then talk about OSSU on class discussion boards, and send several more people to OSSU.)

*Why wouldn't we roll out the red carpet for them??!?*

I understand that CS50's a bit inconvenient and doesn't fit nicely into the curriculum as it's currently designed. So if OSSU is your first stop, we don't require CS50. We have plenty of good reasons for that, and that's fine.

**But CS50 DOES fit nicely in one place: as transfer credit for Py4E *at minimum*.** It MAY even take the place of 6.00.1x.

The simplest way to make that change is to enact the following

**Proposal: OSSU should provide a second entry point into Core CS** -- if you've completed CS50, skip the first two intro courses and move directly to Core CS.

Pros:

- This is an easy move to make. OSSU don't have to do much to recognize another school's Intro CS course as a valid introduction to CS.
- This is already OSSU's *de facto* recommendation; former CS50 learners already come onto the Discord and ask where they should begin the curriculum, and they are frequently told to begin in Core CS with How To Code. Occasionally someone will steer them into 6.00.1x, but many go into How To Code anyway. Having a unified written recommendation would prevent inconsistencies (and perhaps a few of the questions.)
- Providing an on-ramp that allows CS50 students to bypass redundant coursework is more accommodative to those who found CS50 before they found OSSU - and encourages them to stick around, because "hey, I've already completed 10% of the curriculum!"

Cons:

- For an intro course, CS50 is both unusually wide *and* unusually deep, but where a choice between the two must be made, CS50 tends to go wide rather than deep.
- CS50 famously doesn't teach object-oriented design principles. 6.00.1x does (but may not be the best choice for the task...). Object-oriented design isn't deeply emphasized again in the OSSU curriculum until ____________________ (fill in the blank). (The point here may be that OSSU doesn't actually emphasize OOP *at all* -- forgoing it for the design patterns taught in How To Code.)

**Comment by Elpuma** [comment]
> _You have an 8 year old daughter that's finishing OSSU? That's incredible. I'd love to talk with you both!_
> 
> I'll quote from our [guidelines on making substantive changes to the curriculum](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md):
> 
> > OSSU’s curricular guidelines are [here](https://github.com/ossu/computer-science/blob/master/CURRICULAR_GUIDELINES.md). Successful critiques of the curriculum will point out ways that OSSU is failing to uphold these guidelines.
> 
> You mentioned "freely available statistical data about CS Study Programs". OSSU _should_ use such information. That's why we adopted the 500 page report by the Joint Task Force on Computing Curricula from the Association for Computing Machinery (ACM) and the IEEE Computer Society as our curricular guidelines. That's why substantive changes should reference our guidelines.
> 
> Originally you titled this issue, "Put CS50 as Intro CS". This matches many of your assertions about the benefits of CS50:
> 
> * an explicit goal of intro courses is to give students a feel for the breadth of the domain
> * another goal is to excite learners.
> 
> But Core CS is the the midpoint of the curriculum. At this point in the curriculum students should not need to take another introduction to computer science course. CS50 doesn't belong in Core CS.
> 
> [The RFC that removed CS50 from Core CS](https://github.com/ossu/computer-science/issues/833) welcomed a future RFC for replacing _Introduction to Computer Science and Programming using Python_ with CS50. To quote, "That would be a complicated change, requiring looking at the parts of our curricular guidelines are covered by _Introduction to Computer Science and Programming Using Python_ and which are covered by CS50. If it led to missed coverage, that RFC would need to propose ways to maintain coverage." That's a lot of work. But it's better that contributors put in that work, rather than saying "take both intro courses" and directing tens of thousands of OSSU learners to take hundreds of hours of duplicate curriculum.
> 
> Your concerns about retention are very appropriate. One issue that OSSU has had with retention in the past has been students in our forums who found CS50 to be too steep of a learning curve, were demoralized and considering dropping. My hypothesis is that placing OSSU after Py4E would mitigate such outcomes, but it's certainly something we would need to be ready to address if that pattern of student complaints re-emerged.
> 
> It's great to see passion around OSSU, as well as learners interested in putting in the work to become contributors!

Hello!! sorry for the long time to respond! COVID has been hitting us hard recently but We came out victorious. My daughter says She would love to talk to you aswell! we can use discord if you would, or let me know what would be best for you so We can arrange the when and where haha!

**Comment by waciumawanjohi** [comment]
@Elpuma Discord works for me. Why don't you direct message me (I'm Waciuma in the OSSU Discord) and we can find a time that works!

**Comment by rachel83az** [comment]
> This is an easy move to make. OSSU don't have to do much to recognize another school's Intro CS course as a valid introduction to CS.
> This is already OSSU's de facto recommendation; former CS50 learners already come onto the Discord and ask where they should begin the curriculum, and they are frequently told to begin in Core CS with How To Code. Occasionally someone will steer them into 6.00.1x, but many go into How To Code anyway. Having a unified written recommendation would prevent inconsistencies (and perhaps a few of the questions.)
> Providing an on-ramp that allows CS50 students to bypass redundant coursework is more accommodative to those who found CS50 before they found OSSU - and encourages them to stick around, because "hey, I've already completed 10% of the curriculum!" 

I agree with these points, especially the first one. Also, a lot of schools don't just give you a list of classes and say that you must take all of these, and give you no choice in the matter. Depending on the institution, there may be a number of "intro to computers" and/or "intro to programming" courses that are available to students wanting a CS degree. I count at least three at my school and there are a bunch more that I can transfer in to fill my degree requirements. 

The straightforward nature of OSSU is great because, on the one hand, it is easy to understand. Start at the top and work down. On the other hand, if you don't happen to like a given course then that's too bad. There are no other options. It would be nice if, just as with "real" universities, OSSU were to implement some sort of credit system. CS50 might then count as 6 or 9 credits instead of the standard 3.

**Comment by AbdullahAlAzzawi** [comment]
Hello,

I had programming courses during my bachelor's degree. it was more practical ones with lab work. 
this went for 3 semesters long.

I decided to check cs50 two years back, and I would like to not be crucified for this statement. it is a terrible beginners course, I think it is very flashy and attractive for people new to cs, to the point where it is magical. I actually liked it a lot and enjoyed the content. that being said I think it is very time consuming and it touches on a lot of different aspects of cs.

within the first 3 lectures the professor finished 3 semesters work from my university.
I think it is a course for people who do not know which elective to choose and would like to see what is there in computer science. before deciding their electives.

that being said there is an only python intro course coming up from cs50 in april I believe [CS50X intruduction to programming with python](https://www.edx.org/course/cs50s-introduction-to-programming-with-python?index=product&queryID=e7986207e4189d300242d5460955df0c&position=1)

this might be a suitable alternative. It can also be an optional course for people who do not have an idea about their electives.
