### ISSUE TITLE
A List Of Students That Went Through The Curriculum

### ISSUE THREAD

**Issue by loannaflip** [ossu/computer-science#869]
We could compile a list of all the students who have completed the entire curriculum and became successful in their pursuits, using the skills they learned from courses in the curriculum to change their lives for the better.

Other Pros:
- We can keep track of the students who have taken and completed the curriculum.

- Ask for their feedback and comments.

- It would be inspiring for new students/learners as well.

It is meant to be a community-curated list that we can all strive to have. It's our goal that the list gets LONGER over time.

**Comment by spamegg1** [comment]
Sign me up! 
I already gave tons of feedback and made myself fairly known.
The inspiration part is true. Learners told me.

**Comment by rachel83az** [comment]
I know new people are very interested in OSSU alumni, so to speak, so I think that this is a good idea.

**Comment by epikkoder** [comment]
I would love this. I'd like to hear what people have to say about the curriculum.

**Comment by Saif-XI-Coderz** [comment]
This is a great idea. How would we go about implementing it?

**Comment by Uniminin** [comment]
Ideas are very welcome.

**Comment by rohitmehtainventor** [comment]
How about creating a GitHub page?

**Comment by Saif-XI-Coderz** [comment]
It would be much easier if each alum added themselves into the list, instead of someone else compiling and maintaining this list.

So perhaps an alum.md file somewhere, then each individual can create a PR adding themselves into it?

**Comment by spamegg1** [comment]
@Saif-XI-Coderz 
There is PROJECTS.md where you put your final project with a PR. 
So those people would be finishers. I put mine in there.
But I'm guessing that's not good enough???

**Comment by Saif-XI-Coderz** [comment]
Yes am guessing so too. The intention of the projects page is to showcase course projects by the community. Nothing suggests that the project submitter is an alumn or not. The intention of the alumn page will be to showcase a list students that have indeed went through the curriculumn.

This may also be the opportunity for alumn to link to some article/issue they have written to give feedback to the community, just like you did. The appeal to get one's name on such a list may also act as a great motivator for students to finish the course.

**Comment by mardisworld** [comment]
If you go on LinkedIn, you can do a search for Open Source Society
University. From there, you can click to see alumni. It might be helpful to
start there if the goal is to build a mailing list.

**Comment by Darknez07** [comment]
I have a general question about contributing on projects. I am very confused in how to go about contribution.

**Comment by spamegg1** [comment]
@Darknez07 Not here, come to [Discord](https://discord.gg/wuytwK5s9h).

**Comment by PupkinLangford** [comment]
I finished the OSSU curriculum and then moved on to The Odin Project. I'm happy to provide guidance or feedback.

Technically I didn't entirely finish the OSSU because I didn't complete "Software Engineering: Introduction" or "Software Development Capstone" (and don't intend to, given the reviews).

**Comment by JoseDeFreitas** [comment]
I also think this is a nice idea!

**Comment by AlexisCodeBO** [comment]
Excellent to complement the knowledge being a computer engineer/Excelente para complementar los conocimientos siendo un ingeniero de computación
________________________________
De: José De Freitas ***@***.***>
Enviado: domingo, 11 de abril de 2021 19:37
Para: ossu/computer-science ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [ossu/computer-science] A List Of Students That Went Through The Curriculum (#869)


I also think this is a nice idea!

**Comment by Exkywor** [comment]
I'd love to see something like this implemented!

**Comment by aayushsinha0706** [comment]
Let's create a GitHub page for that. With their LinkedIn profiles, GitHub and discord profiles

**Comment by Ahmed1545** [comment]
> انتهيت من منهج OSSU ثم انتقلت إلى مشروع أودين. يسعدني تقديم التوجيه أو الملاحظات.
> 
> من الناحية الفنية لم أكن تماما الانتهاء من OSSU لأنني لم أكمل "هندسة البرمجيات : مقدمة" أو "تطوير البرمجيات كابستون" (ولا تنوي ، نظرا للاستعراضات).

What do you think ossu or mit opencourseware computer science

**Comment by Ahmed1545** [comment]
> I finished the OSSU curriculum and then moved on to The Odin Project. I'm happy to provide guidance or feedback.
> 
> Technically I didn't entirely finish the OSSU because I didn't complete "Software Engineering: Introduction" or "Software Development Capstone" (and don't intend to, given the reviews).

What do you think ossu or mit opencourseware computer science

**Comment by PupkinLangford** [comment]
> What do you think ossu or mit opencourseware computer science

OSSU includes a few courses from mit opencourseware. I would recommend completing OSSU, and if you feel there are any gaps in your knowledge, then check out the additional courses on opencourseware.

**Comment by ChrisNzoka** [comment]
This is my first time here. The reviews are awesome. I have a degree in Chemistry but I hope to become a full stack developer in 1 year and then walk myself through the Computer science program here Within 2 years. Any good advice will be highly appreciated.

**Comment by waciumawanjohi** [comment]
I've been watching this proposal with interest. I was skeptical about it, but wanted to give time to be shown wrong. 9 months after the original proposal, I'd like to share my thoughts.

In my experience, the best sign of folks that are powering through the curriculum are is that they propose changes to the curriculum and put work into the community. The moderators, tutors, contributors, etc are the students you are looking for. (There's unquestionably bias here, I become familiar with those people that want to give back to OSSU.)

I am very aware that there are people that work through the curriculum and never make themselves known. But I don't think that's because of a lack of opportunity. I think it is a lack of interest on their part. In this thread commenters have pointed out that for years OSSU has had a section for [final projects](https://github.com/ossu/computer-science#final-project). But it has had almost no traction. Students see great value in having a clear roadmap to mastery of CS, but they are not seeing value in posting in the OSSU repo.

A contrast to this is LinkedIn. On that platform [over 500 people have tagged themselves as students of OSSU](https://www.linkedin.com/search/results/people/?schoolFilter=%5B%223160022%22%5D). This has been far more successful than any list that OSSU has hosted on its site. (When it began years ago, OSSU had a list of students that were following the curriculum as part of the repo. It was deprecated long ago). The LinkedIn list is also very easy to maintain --- OSSU need not do anything.

There are mentions of getting learner's Discord handles. There's a very easy way to connect with OSSUnians on Discord. Come to the [OSSU Discord](https://discord.gg/wuytwK5s9h)! There are live weekly meetings held in timezones around the world. There is constant chatter in the random channel. There is a vibrant community of the OSSUnians most likely to engage with you, inspire you, and to ask you to inspire them.

**Comment by KelvinJPS** [comment]
@PupkinLangford I'm trying to accomplish almost the same thing how can I contact you?

**Comment by TheChronicMonster** [comment]
Hi Kelvin,

You can email me at ***@***.***

Looking forward to connecting.
