### ISSUE TITLE
RFC: Change MITx 18.01 to edX instance of MIT

### ISSUE THREAD

**Issue by Jack-Works** [ossu/computer-science#886]
Alternative address (MIT own edX instance):

https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.1x+2T2019/about
https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.2x+3T2019/about
https://openlearninglibrary.mit.edu/courses/course-v1:MITx+18.01.3x+1T2020/about

Reason: edX no longer allows course access after the audit expired. See: https://support.edx.org/hc/en-us/articles/360021149373-How-can-I-get-access-after-a-course-expires-

**Comment by Alaharon123** [comment]
typo in the title, should be 18.01 rather than 18.03. Relevant RFCs: #832 and #838

**Comment by oNjEncUREn** [comment]
We had a discussion about the MIT calculus sequence a few weeks back while developing the math curriculum.  There are some thoughts that all the programs should move to the 3-course Calculus sequence (18.01, 18.02, 18.03) using the MIT OCW courses since they can be completed quicker, while learning the same material.  For example, each 18.01 (a, b, c) course is 13-weeks each whereas you can complete the MIT OCW 18.01 in 15-weeks.  The OCW course covers all the same material, just 14-weeks quicker.
