### ISSUE TITLE
Create a bridged Matrix room

### ISSUE THREAD

**Issue by ghost** [ossu/computer-science#903]
#### Is your enhancement request related to a problem? Please describe.
Discord has numerous privacy concerns and many people like me just dislike it in general. Discord is a proprietary software while Matrix is made up of free software.

#### Describe the solution you'd like.
Create a Matrix room bridged to Discord to allow people to talk about OSSU without using Discord. Matrix is a decentralized platform for communication used by many open source projects.

#### Describe alternatives you've considered.
Creating an IRC channel is also an option.

### End Result:
![image](https://user-images.githubusercontent.com/85154041/120592308-75aad800-c45f-11eb-9908-192db1838b47.png)

**Comment by waciumawanjohi** [comment]
An interesting issue!

You bring up 3 points:

- _Discord has numerous privacy concerns_
More details would be appropriate here.
- _many people like me just dislike it in general_
This is not a description of a problem.
- _Discord is a proprietary software while Matrix is made up of free software._
This is a valid point.

This issue has been open for a month and has received 2 upvotes. A concern that I have about adopting this bridged system is that it will entail OSSU running a server on our own hardware in order to support 1-3 participants (out of nearly 10,000 Discord users).

I will also point out that OSSU does make use of closed source platforms, Github for example!

I've highlighted this issue with the Discord moderators, as ultimately the responsibility for moderating the Discord communication lies with them.
