### ISSUE TITLE
RFC: Read the Tos of edx

### ISSUE THREAD

**Issue by empZealoth** [ossu/computer-science#915]
EDX tos is the most abusive one i have ever seen, why are so many courses requiring me to basically waiver any and all of my rights?

**Comment by waciumawanjohi** [comment]
I'm sorry to hear that you find edX's terms of service abusive. edX is a platform partnering with many of the world's most respected educational institutions to bring free and low cost educational content to users. We've found that on many topics they offer the best option for learners.

If you feel that edX courses should be replaced, we welcome feedback on specific reasons why (the assertion that the tos is abusive needs to be backed up with concrete examples). As stated in our [contributing guidelines](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md), "While it is acceptable to point out problems, all successful changes naturally require a plan for fixing the problem."

**Comment by krishnakumarg1984** [comment]
@waciumawanjohi In the case of EdX, there may be some real concerns in the near future. This is because, EdX was acquired last week by a private organisation who has sort of announced that EdX will no longer be non-profit.

As per [this class-central article](https://www.classcentral.com/report/2u-edx-acquisition-analysis/),

> In an unexpected turn of events, a nonprofit made hundreds of millions of dollars for its two nonprofit owners. Last week, we learned that the public company 2U is acquiring Harvard and MIT-backed edX for $800 million in cash, and that edX will __no longer be a nonprofit__. 

A suggested alternative for EdX might be to look for equivalent courses that are directly run by professors themselves through their own course sites. py4e would be a good example.

**Comment by waciumawanjohi** [comment]
Very true that edX is no longer a non-profit. (I've been reading about the sale, I'm glad to see other OSSUnians doing so as well!) We should keep in mind that Coursera is not a non-profit organization either. As you've pointed out, there have been some cases, like py4e, where the course creators have made materials available on their own site. RFCs to replace courses, backed up with evidence of specific advantages to students, are always welcome!

**Comment by rachel83az** [comment]
I find edX to be a terrible platform in general. It's not always clear that you _never_ get to take a course again after the deadline if you don't pay. Suggesting that students simply create another account is something that goes against edX's TOS. Since most edX courses have an alternate source (OCW, etc.), I propose making those the main and linking to edX as an alternative.

**Comment by waciumawanjohi** [comment]
Linking issue opened by @rachel83az : https://github.com/ossu/computer-science/issues/920

**Comment by riceeatingmachine** [comment]
I think the longer term solution is to find alternative courses on different platforms that are better in qualitty. Most EdX courses do not have a free substitute (like OCW), only the MIT ones do. 

Even in case of MIT, the edx versions have active TAs which make the edx version superior. 

For example, please see the RFC I created (#933) which replaces 2 EdX courses with coursera ones.
